### ISSUE TITLE
Word categorisation of -овать in the Khakas lexicon

### ISSUE THREAD

**Issue by ftyers** [tuffnatty/suddenly#1]
Is this a noun in Khakas ? and are they even used in Khakas ?

$ cat dev/kjh.lex | grep овать | grep '^n' | wc -l
43

**Comment by tuffnatty** [comment]
Oops, I have missed this question. I hope someone more proficient in Khakas language will answer soon.

**Comment by ftyers** [comment]
Hmm, I'm pretty sure that they aren't nouns. Where did you get the stem lexicon from ? Was it automatically extracted from somewhere ?

**Comment by tuffnatty** [comment]
The dictionary was OCRed and cleaned manually, but part-of-speech tagging has been performed semi-automatically. Of course these Russian borrowings are not nouns, they are uninflected and, in my opinion, should be marked as *i* in the dictionary.

**Comment by adybo** [comment]
I prefer not i, but invar, Nouns were set as default after automatic setting of Verbum (-arga) and Invar (частица, союз, междометие) extracted from scanned Subrakova 2006.

**Comment by ftyers** [comment]
Is that the same scan as used on http://www.sostik.info/ ? Would it be not possible to subcategorise some of the invariants/nominals using the POS information from the dictionary ? e.g. 'оортах' has the category 'нареч.'. Would it also be possible to get access to a copy of the scan ?

**Comment by adybo** [comment]
Yes, I think it is the same. The idea was that we have only Nomen, Verbum and Invariabile as morphologic cathegories. Pronomen, Particulum etc. belong rather to the semantic. So they are in the field "SemTag". But Russian borrowings of such kind are not cathegorised in the Sostik.

**Comment by veramal** [comment]
танцевать et al. are Invariabile now
