### ISSUE TITLE
датив после й

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#10]
Не разбираются: хомай-га - плохой-dat, ай-ға - месяц-dat  и т.п.
Потому что после й сейчас допускается только датив в форме а. Хотя из таблицы 15 про выбор падежных вариантов следует, что после Й должен быть га/ге.

**Comment by adybo** [comment]
Уже не помню, почему так получилось.

**Comment by asheimovich** [comment]
Почему "допускается только датив в форме а" и где это сказано? Выбор вариантов падежных аффиксов описан ведь только в табл. 15

26.12.2015, 01:42, "adybo" <notifications@github.com>:

**Comment by veramal** [comment]
По факту.

26 декабря 2015 г., 1:47 пользователь asheimovich <notifications@github.com>
написал:

**Comment by veramal** [comment]
актуально

**Comment by tuffnatty** [comment]
исправилось
