### ISSUE TITLE
переделка грамматики: Pl1, Poss1, Case1

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#100]
Переписала правило 16, где регулируется появление в словоформе атрибутивизатора и первого блока именных категорий. Получилось ненамного короче, но не настолько ad hoc, как было. Старый вариант перенесла в подвал документа.

**Comment by adybo** [comment]
Да, эти мне нравятся!

**Comment by veramal** [comment]
Пожалуй, стоит запретить All1 САР + Dat2 ГА (неместоименного типа). Иначе у нас половина инфинитивов будут иметь ложную омонимию.

**Comment by veramal** [comment]
ниме-лер-і-біс имеет паразитический разбор:
что-Pl₁-3pos₁-1pos.pl

(наряду с что-Pl₁-1pos.pl)

Надо подумать, как его исключить.

**Comment by veramal** [comment]
А также
что-Pl₂-1pos.pl (верный)
что-Pl₂-3pos-1pl (возможный)
что-Pl₁-3pos-1pl (невозможный)
что-Pl₁-1pos.pl (невозможный)

+ еще на каждый разбор три варианта перевода основы, итого всего 15

Это к вопросу о том, чем мешает неограниченное сочетание чисел и посессивов.

**Comment by veramal** [comment]
Сейчас остались разборы только через Pl₂ (верный и возможный в предыдущем комментарии). Кажется, проблема закрыта.
