### ISSUE TITLE
переделка грамматики: Adv Ли

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#101]
Adv Ли переместился на поз. 9, где живет Comit ЛЫГ, т.к. не нашли перед ним других аффиксов, кроме причастных. Правило 18 изменилось. Про поз.9 непонятно, как ее теперь называть (раньше она называлась Comit, там быть только один аффикс).

**Comment by adybo** [comment]
Как там называется конверсия? есть какое-то слово, в смысле изменить категориальную принадлежность

**Comment by veramal** [comment]
Как-то называется, но ЛЫГ ее не очень меняет (разве что со склоняемого
имени на несклоняемое).

8 декабря 2017 г., 22:23 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Ну да, у нас же нет части речи "прилагательное", а несклоняемое имя это и есть это самое прилагательное, так что для нас эта самая словоизменительная конверсия оно и есть. 

О, вспомнила! Транспозиция. Назовем столбик Transp

**Comment by veramal** [comment]
Вообще-то надо бы завести, конечно, но для этого надо очень внимательно
смотреть на треть словаря.

9 декабря 2017 г., 1:06 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Нет! Это не грамматический класс. Слова, которые с некоторой более высокой частотностью выполняют такую-то синт. функцию - это семантическая помета, а не частеречная. Чтобы делать по таким характеристикам какой-то отбор, надо смотреть частотный словарь сбалансированного корпуса.

**Comment by veramal** [comment]
Тут обсуждение ушло в сторону, меж тем Adv Ли надо ввести в парсер на поз.9 (пока). Про него см. правило 18. Категорию Аня назвала Transp (транспозиция), ну пусть так и будет.

**Comment by veramal** [comment]
Ли работает - см., например, ибли.
