### ISSUE TITLE
диалектные окончания

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#102]
Было бы неплохо их тоже ввести в парсер, раз уж часть есть. Вот такие:
- варианты после гласных и звонких согласных: ДЫНГ - генитив, ДЫ - аккузатив, ДАНГ - инструменталис (хотя последний не так нужен, всегда есть разбор через аблатив), -ДИ - Gen3.Poss
- САРЫ (или САРА)  - аллатив
- БАНГ, БЛАНГ, БА - инструменталис

Д-формам нужен только непосессивный вариант, прочим - оба.

**Comment by veramal** [comment]
А ее есть презентное причастие чАн.

**Comment by veramal** [comment]
А еще в бельтырском -бын обратно превратилось в мин: _семьялыгмин_.

**Comment by adybo** [comment]
Ух. Но это все же вряд ли для парсера. Точгно мин, а не мiн? Тогда это вообще новое образование с новой подстановкой местоимения.

**Comment by veramal** [comment]
Давайте на след. неделе обсудим и внесем в документ.

**Comment by veramal** [comment]
Сделали вот что: все диалектные формы вынесли в нижние строки таблицы, там есть старые и новые. Им всем надо приписать в глоссах <...>.dial (не подстрочными символами, а через точку, как и раньше). Из новых внесли презентное причастие PresPt чАн , Gen.3pos Ди, и несколько вариантов падежных аффиксов. Просьба все это ввести в парсер - чем раньше, тем лучше. Падежи и Gen.3pos особых условий не требуют, PresPt чАн я добавила в ограничения зеленым цветом в нужных местах.

**Comment by tuffnatty** [comment]
Вношу, но хорошо бы еще накидать примеров на каждую форму, а в случае чАн - и на каждое правило, где он упоминается. Тогда я сразу добавлю соответствующие автотесты, и это поможет избежать регрессий в будущем.

**Comment by veramal** [comment]
Ага, кидаю.
Gen.3pos Ди - сірерди ‘принадлежащее вам’ (вы-Gen.3pos.dial)
Gen ДIӊ - олардыӊ 'их' (они-Gen.dial)
Acc ДI - марығды (спор-Acc.dial) утыр саларзың 'проиграешь спор'
Instr ПАӊ - палабаӊ 'с ребенком' (ребенок-Instr.dial)
Instr мАӊ - паламаӊ 'с ребенком' (ребенок-Instr.dial)
Instr ПЛАӊ - палаблаӊ 'с ребенком' (ребенок-Instr.dial)
All САрI - тайғазары 'в тайгу' (тайга-All.dial)
All СА - тайғаза 'в тайгу' (тайга-All.dial)

PresPt чАн -  килчен кізі 'пришедший человек', тіпчен осхас 'типа говорит', * парчанох 'тоже идущий' (пока не встретилось), * парахчан 'тот, кто хочет уйти' (тоже не припомню, но может встретиться)

**Comment by tuffnatty** [comment]
Диалектные Prosp АК, Conv.пас, Imp.1.Incl.pl, 1.sg, 1.pl, 2.pl - теперь продублированы в таблице.

2.pl САр, видимо, случайно попало в диалектные. 1.pl СIПIС в нижних диалектных продублировано (т.е. вместе с верхним - встречается трижды).

тіпчен - тіп нет в словаре, так что тест не очень хороший выходит.

**Comment by veramal** [comment]
тіп, конечно, не в словаре, потому что это ті+ып 
САр убрала, дубли убрала
