### ISSUE TITLE
Семьяларынаңар - два разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#104]
n семья <+rus> ‛семья’
-----------лар-----ы-наңар----
-----------Pl₁-----3pos-Delib----
n семья <+rus> ‛семья’
---------------лар-ы-наңар----
---------------Pl₂-3pos-Delib----

Pl1 не может стоять непоредственно перед 3pos, если есть возможность разобрать через Pl2.

**Comment by tuffnatty** [comment]
А где такое правило?

**Comment by veramal** [comment]
В конце 16.5: "Poss2 не может следовать непосредственно за Pl1."
