### ISSUE TITLE
Мындох - два разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#105]
n мында ‛этот.Loc’
------------------ох---
------------------Ass₂---
n мында ‛этот.Loc’
---------------------ох
---------------------Ass₃

Первый разбор избыточен - Ass2 присоединяется только между временем и личным окончанием.

**Comment by tuffnatty** [comment]
Где про это написано?

**Comment by veramal** [comment]
В 27, где про конец словоформы, но когда-то выпало. Вписала обратно.
