### ISSUE TITLE
датив после велярных

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#106]
Сейчас различается присоединение датива к ғ и к ң:
суға
n суғ ‛вода’ суу
-----------------ға----
-----------------Dat----

маңа
n маң ‛досуг’
-----------------ға----
-----------------Dat----

Хотя правило совершенно одинаковое, Г+Г = Г.

**Comment by tuffnatty** [comment]
Ничего не понял.

**Comment by veramal** [comment]
Это про то, что у суг в основе выписано суу, что лечится обновлением словаря.
