### ISSUE TITLE
парчатпас - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#107]
Почему-то перестал сочетаться дуратив с отрицательным будущим (раньше разбиралось). Форма довольно частая. С остальными временами нормально сочетается. В правилах не нашла того, что может мешать.

**Comment by tuffnatty** [comment]
чат бывает только с NF, а Neg.Fut только при незаполненной п.2. Т.е. как только мы вставляем 0 в п.2, надо менять/проверять все правила, говорящие о его незаполненности

**Comment by veramal** [comment]
Поняла, затык в ограничении 11, исправила. Думаю, поз.2 можно отпустить на свободу.
