### ISSUE TITLE
перфект после выпадающих согласных

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#108]
У нас не учтено, что в перфекте, как и с формами на -ып, выпадающие согласные тоже выпадают: саабысхан (сап-ыбыс-хан) 'покосил'. Добавила к соответствующему месту в сандхи (выделено желтым), надо включить в парсер.

**Comment by adybo** [comment]
Ой, да, это надо, действитедльно, включить

**Comment by tuffnatty** [comment]
чыыбысхан всегда работало, потому что там Г. А про выпадение п там написано "см.примеры ниже", и ниже есть п.3.3, где разъясняется выпадение п+ып. И никакие другие выпадения п парсер не реконструирует. А про п+ыбыс в документе даже примера нет.

**Comment by veramal** [comment]
А, я смотрела только общее правило про Г+п на с. 51 (пункт 3.1).  Дописала примеры и нужные аффиксы в 3.3.
