### ISSUE TITLE
предикативный показатель 3sg

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#11]
В таблице 16 при вариантах аффикса дыр/дiр нужно учесть, что он бывает после имен (это такой маркер частного вопроса): 
синын' адын' кем-дыр? - как тебя зовут?
нинже пала-дыр? - сколько детей?

Оглушается ли, не знаю - нет примеров.

**Comment by asheimovich** [comment]
Так. Приехали. Что за дыр в таблице 16? Пир том, что падежные афф. у тебя вроде в табл. 15, что правильно. Я же всем рассылала последний вариант файла со всеми правилами и таблицами.
И по существу: в таблицах алломорфов хотелось бы избежать чего бы то ни было кроме фонетических вариантов. А остальное - в ограничения (II)

26.12.2015, 03:15, "veramal" <notifications@github.com>:

**Comment by adybo** [comment]
Он и просто для фокуса бывает после имен, в повествовательном предложении. Но пишется через черточку, надо отдельно собрать все, что через черточку и подумать, надо это в анализатор вставлять, или как.

**Comment by adybo** [comment]
Это Вера говорит про дыр, который локальный показатель 3го лица, при именах и еще кой-когда.

**Comment by asheimovich** [comment]
Все равно не 16!
Вера, затри, пожалуйста, свой файл вот этим

26.12.2015, 03:37, "adybo" <notifications@github.com>:

**Comment by veramal** [comment]
Ну ок, 18.
Если он пишется через дефис, надо добавить в словарь, значит. Но 

Оглушается. Вот из грамматики:
Хайдағ маңаттыр! 'Как прекрасно!’; Хайдағ сидіктір! 'Как тяжело (трудно)!’ 

А нет дефиса-то.

А в Казановки есть примеры того, что этот -дыр - не то чтобы совсем ЛЧ показатель:
pu kiziler kem-ner-dyr?
Кто эти люди? (кто-pl-дыр)
kemzerdyr sler?
кто-2pl-дыр
Кто вы?
kemdyrzyN sIn andax?
кто-дыр-2sg
Кто ты такой?

**Comment by adybo** [comment]
Может быть, его - вот этот конечный - надо считать вообще не показателем 3 л., а припредикатной фокусной частицей, и отправить в позицию после показателей лица. Зависит, встретится ли в литературном kemzerdyr.
А вот это kemdyrzyN  это уж и точно на частицу канает.

Про оглушение и правила с черточкой или нет надо бы направить запрос Эльвире - она этим правилам должна детей учить. Спрашивать, бывает ли kemzerdyr, это надо Л. И. Чебодаеву как поборницу чистоты хакасского литературного, но она что-то перестала отзываться.

**Comment by veramal** [comment]
Ну можно всем написать, кто-нибудь да ответит. Чертыкова еще есть.

26 декабря 2015 г., 15:28 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
Как мы его предварительно глоссируем тогда, Foc?

**Comment by adybo** [comment]
Давай так.

**Comment by veramal** [comment]
фокус работает
