### ISSUE TITLE
Pl от дагы

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#110]
_холдағылар_ не разбирается, хотя _холдағы_ - вполне
в описании причину не смогла найти

**Comment by tuffnatty** [comment]
> 16.3. Pl2 может следовать непосредственно за Case1, только если Case1 выражен генитивом: пістіңнер ‘наши’ (см. также 1.25). В прочих случаях перед нами не Pl2, а PredPl: ибделер ‘они дома’.
А если это не Pl2, то это должен быть PredPl. А правило 21 не разрешает его после позиции 14.
