### ISSUE TITLE
чуртабохчабыс - лишние разборы

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#111]
Во-первых, есть разбор через Hab - видимо, это как-то связано с тем, что частицы иногда появляются  не только при чат и ыбыс. Во-вторых, непонятно почему каждый из разборов выдается два раза:

чуртабохчабыс
v чуртирға ‛жить’ чурта
--п-ох----ча------------быс--
--NF-Ass₁----Pres------------1pl.mix--
v чуртирға ‛жить’ чурта
--п-ох----ча------------быс--
--NF-Ass₁----Pres------------1pl.mix--
v чуртирға ‛жить’ чурта
--п-ох----ча------------быс--
--NF-Ass₁----Hab₁------------1pl.mix--
v чуртирға ‛жить’ чурта
--п-ох----ча------------быс--
--NF-Ass₁----Hab₁------------1pl.mix--

**Comment by tuffnatty** [comment]
Дубли убрал, остался Hab - это плохо?

**Comment by veramal** [comment]
Пока пусть живет, некритично. Но когда-то надо о нем подумать.

**Comment by tuffnatty** [comment]
@veramal Добавление в правило 20 про полные формы "Pres чА" добавило третий разбор:
```
v чуртирға ‛жить’ чурта
-(Ы)п-ОК-----чА-----------ПЫс---
-NF-Ass₁-----Pres-----------1pl---
v чуртирға ‛жить’ чурта
-(Ы)п-ОК-----чА-----------ПЫс---
-NF-Ass₁-----Pres-----------1pl.mix---
v чуртирға ‛жить’ чурта
-(Ы)п-ОК-----ЧА-----------ПЫс---
-NF-Ass₁-----Hab-----------1pl.mix---
```

**Comment by adybo** [comment]
Мы вроде выбрасывали такой хабитуалис? Вера?

**Comment by veramal** [comment]
Нет, все правильно. И хабитуалис, и полные формы.

**Comment by tuffnatty** [comment]
еще один дубликат разбора убрался из-за #201.
