### ISSUE TITLE
еще загадочный разбор

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#112]
кіртӧңӧк
n кіртӧң ‛волк’
-----------------ге-ӧк---
-----------------Dat-Ass₂---
n кіртӧң ‛волк’
-----------------ге----ӧк
-----------------Dat----Ass₃

Интересно, почему только с дативом. Из-за выпадения велярных?

**Comment by adybo** [comment]
Ага, там г выпало бы, а ок заел бы конечный гласный. Так что имеет право

**Comment by tuffnatty** [comment]
Разбор с Ass₂ устранен

**Comment by veramal** [comment]
Перед -ох, конечно, Г не очень-то любит выпадать: например, _андағох_ 'такой же' только в этой форме встречается, иначе его было бы не отличить от _андох_ 'там же' (анда+ох). Но и не только поэтому - всегда забываем, что в непервом слоге обрамляющие гласные только краткие.

**Comment by tuffnatty** [comment]
Похоже, тут неопределенное поведение: кіртӧңӧк > *кіртӧңі+ӧк > **кіртӧң+гі+ӧк. По отдельности каждая из этих реконструкций вроде бы не запрещена.

**Comment by veramal** [comment]
Но все-таки о и ӧ - долгие гласные, поэтому запрещена.

**Comment by tuffnatty** [comment]
Когда выпадает г, справа от нее і - краткая гласная. Это не запрещено. Когда выпадает і, она выпадает по правилу "поглощение гласных перед -ох".

**Comment by veramal** [comment]
А, вот как. Она, правда, тут не i, а _е_, но неважно. Значит, порядок другой должен быть: сначала поглощение перед -ох, потом восстановление Г.

**Comment by tuffnatty** [comment]
Порядок восстановления именно такой. Сначала восстанавливается то, что было до поглощения перед -ох, затем то, что было при поглощении на стыке ГГ. Т.е. на этом уровне (когда не произошло интервокальное озвончение) сандхи применяются слева направо, по мере нанизывания аффиксов. А отменяются, соответственно, справа налево. Это точно неправильно? Только в данном случае?

**Comment by adybo** [comment]
Ох, кажется, не озвончает?

**Comment by tuffnatty** [comment]
Не озвончает, не озвончает, а значит, должны примениться (или - при анализе - отмениться) всякие выпадения. Порядок их применения/отменения не указан, но интуитивно кажется, что они должны применяться на границах аффиксов слева направо, а отменяться справа налево.

**Comment by adybo** [comment]
Да, по-моему так.

**Comment by veramal** [comment]
Да нет, не так. Именно перед -ох ничего не выпадает, потому что иначе невозможно отличить одно от другого. Просто -ох, конечно, не аффикс, а клитика, в сагайском особенно - но при текущей орфографии мы этого различать не умеем. Так что спецправила для -ох не противоречат общей логике.

**Comment by tuffnatty** [comment]
Так где они, эти спецправила?

**Comment by veramal** [comment]
Дописала в сандхи про -ох.

**Comment by adybo** [comment]
Да, это особый тип границы.


>Понедельник,  5 февраля 2018, 9:33 +03:00 от veramal <notifications@github.com>:
>
>Да нет, не так. Именно перед -ох ничего не выпадает, потому что иначе невозможно отличить одно от другого. Просто -ох, конечно, не аффикс, а клитика, в сагайском особенно - но при текущей орфографии мы этого различать не умеем. Так что спецправила для -ох не противоречат общей логике.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
В статье-то есть


>Понедельник,  5 февраля 2018, 10:12 +03:00 от Phil Krylov <notifications@github.com>:
>
>Так где они, эти спецправила?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by tuffnatty** [comment]
В статье не нашел. И вопрос: Как тогда будет выглядеть кіртӧң+ге+ӧк? кіртӧңгӧк?

**Comment by tuffnatty** [comment]
В статье не нашел. И вопрос: Как тогда будет выглядеть кіртӧң+ге+ӧк? кіртӧңгӧк?

**Comment by tuffnatty** [comment]
И еще: про -ох дописано:
>  (действует до выпадения Г в интервокале)

А в данном случае у нас не интервокал, а "Выпадение Г после Г, ң без стяжения".

**Comment by veramal** [comment]
В дативе будет _кіртӧңеӧк_, с выпаденем, но без стяжения.
Значит, надо исправить там "действует до всех стяжений". Тогда здесь оно применяться не будет.

**Comment by adybo** [comment]
Тогда неверно, что ок убивает любую предшествующую гласную - или же е в дативе долгий и это где-то надо вписать

>Вторник,  6 февраля 2018, 19:06 +03:00 от veramal <notifications@github.com>:
>
>В дативе будет  кіртӧңеӧк , с выпаденем, но без стяжения.
>Значит, надо исправить там "действует до всех стяжений". Тогда здесь оно применяться не будет.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by tuffnatty** [comment]
Так может, тут просто такой же случай, как с 3pos, когда стяжения не происходит? Или если бы г не выпало, то стянулось бы?

**Comment by adybo** [comment]
Да, такой же


>Вторник,  6 февраля 2018, 20:25 +03:00 от Phil Krylov <notifications@github.com>:
>
>Так может, тут просто такой же случай, как с 3pos, когда стяжения не происходит? Или если бы г не выпало, то стянулось бы?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Так и неверно, что -ох убивает любую гласную - это опционально. Но с дативом и 3pos в виде ы/i  -ох не стягивается никак.

**Comment by adybo** [comment]
Значит, надо написать, какие гласные не падают вообще никогда, а какие падают опционально. 


>Вторник,  6 февраля 2018, 21:23 +03:00 от veramal <notifications@github.com>:
>
>Так и неверно, что -ох убивает любую гласную - это опционально. Но с дативом и 3pos в виде ы/i  -ох не стягивается никак.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Ну вот я и написала: гласные в дативе, в 3pos без начального согласного и гласные первого слога.

**Comment by tuffnatty** [comment]
Тогда, значит, убираем "(действует до выпадения Г в интервокале)" и добавляем датив к 3pos? Или только такой датив, от которого только гласная осталась (как и в 3pos)?

**Comment by veramal** [comment]
Давайте еще раз. -ох не стягивается в четырех случаях:
- с дативом (любым)
- с 3pos (не любым, а без согласного)
- с гласной первого слога (это уже учтено)
- с долгой гласной (это тоже учтено)

В прочих случаях может стягиваться, может не стягиваться.

**Comment by tuffnatty** [comment]
С посессивным дативом тоже не стягивается? С 3pos учтено

**Comment by veramal** [comment]
Да, тоже.

**Comment by tuffnatty** [comment]
В парсер добавил, осталось в грамматику добавить.

**Comment by veramal** [comment]
Добавила.

**Comment by tuffnatty** [comment]
Да, еще хочу пример для теста, где опционально не стягивается.

**Comment by veramal** [comment]
мындох / мындаох

**Comment by veramal** [comment]
Но вроде реализовано, обе формы разбираются.

**Comment by veramal** [comment]
Здесь осталось, собственно, разобраться с -г, чтобы разбирался кіртӧңӧк (без датива).

**Comment by tuffnatty** [comment]
Разбор с дативом уже исключен. Но разбора без датива не было и раньше, датив ни при чем.
