### ISSUE TITLE
тапхыс - загадка

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#113]
В словаре при парсере сейчас у этого слова основа "с", поэтому оно вылезает в самых неожиданных местах. Видимо, ошибка при компиляции словаря была какая-то - в базе все ок.

тапхыс
n тапхыс ‛загадка’ с

**Comment by veramal** [comment]
Еще одно такое:
n торлас ‛шум крыльев’ й

**Comment by veramal** [comment]
И еще сюда же ізіг имеет разбор "дверь", т.к. в онлайн-словаре у слова ізік в Alternaten прописана основа ізіг. В оффлайн-версии это давно исправлено. Видимо, основа у "воды" суу вместо "суғ" тоже сюда, т.к. основа для 3pos получается чистой морфолоногией, и из словаря ее надо убрать.

**Comment by tuffnatty** [comment]
у тапхыс в поле ALTERNATEN стоит с, у торлас - й, у ізік - ізіг. Может быть, парсеру вообще этот alternaten не нужен? Не помню.

**Comment by tuffnatty** [comment]
Еще в словаре в слове сӧктӱӌек ӧ латинское.

**Comment by veramal** [comment]
ALTERNATEN нужен вроде для слов типа орын > орн-ы (теряют гласную в посессиве), специалист > специализi и глаголов ис(т), сис(т). 
Поправила сӧктӱӌек, если есть еще баги, лучше письмом.

**Comment by veramal** [comment]
Оказывается, искала не в том поле  - Alternat,  а не Alternaten. Сейчас убрала.

**Comment by tuffnatty** [comment]
@veramal Вроде тут все работает, можно закрыть?

**Comment by veramal** [comment]
Да.
