### ISSUE TITLE
-чых как причастие

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#115]
поларӌыхсар - первый разбор

v поларға ‛мочь’ пол
-------ар---ӌых-------сар----
-------Futₐᵣ---Affirm-------All----

В принципе -чых дает финитность, но мы об этом забыли (а т.к. Fut причастие, то падеж прикрепляется, хоть и не должен после -чых).

**Comment by adybo** [comment]
Вот не пойму, правильно ли, что чых дает финитность


>Среда, 31 января 2018, 0:23 +03:00 от veramal <notifications@github.com>:
>
>поларӌыхсар - первый разбор
>v поларға ‛мочь’ пол
>-------ар---ӌых-------сар----
>-------Futₐᵣ---Affirm-------All----
>В принципе -чых дает финитность, но мы об этом забыли (а т.к. Fut причастие, то падеж прикрепляется, хоть и не должен после -чых).
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
НУ бывает лыг+чых, там не дает. А в причастиях вполне.

**Comment by veramal** [comment]
Сейчас разбора с аллативом нет.
