### ISSUE TITLE
Prosp+Pres

### ISSUE THREAD

**Issue by tuffnatty** [tuffnatty/suddenly#117]
Недавно в документе была исключена возможность постановки Pres после Prosp АК (правило 16). Если так сделать, перестает разбираться узу+ах+ча > узихча

**Comment by veramal** [comment]
Можно слова сюда скопировать? В 16 сейчас вижу правила только про именные показатели.

**Comment by tuffnatty** [comment]
Не, не 16! 26 было:
>26. Показатели Dur чАТ, Dur.Iter чАдIр, Indir тIр возможны только при наличии показателей позиции 2: NF или NF.Neg. Pres чА возможен только при наличии NF, NF.Neg **или Prosp АК**.

Стало:
>26. Показатели Pres чА, Dur чАТ, Dur.Iter чАдIр возможны только при наличии показателей позиции 2 (NF или NF.Neg) или 4. Indir тIр возможен при тех же условиях или при одновременном наличии показателей Neg ПА и Past ГАН.

**Comment by veramal** [comment]
Ну так АК в позиции 4 сидит, вместе с перфектом.

**Comment by tuffnatty** [comment]
Не понял. Вышеприведенное изменение запретило сочетание АК+чА.

**Comment by tuffnatty** [comment]
а, теперь понял. не заметил "или 4"

**Comment by veramal** [comment]
Не запретило.  ... только при наличии показателей позиции 2 (NF или NF.Neg) **или 4**. АК сидит в 4.
