### ISSUE TITLE
неизменяемые

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#12]
Все-таки не вижу, где у нас написано правило номер 0: "Основы с пометой i не присоединяют ничего". Или есть возражения?

**Comment by adybo** [comment]
Да, наверное, надо написать, правда. 
А точно ничего? Вот верно ли, что не бывает мяу-ох?

**Comment by asheimovich** [comment]
i - Это Invar? Во-первых, нет еще такой пометы. Аня сейчас не помнит, но изначально у нее были какие-то формальные возражения против ее проставления в словаре, хотя все вроде хотели... Так что я проставляю ее только сейчас. А уж что она там присоединяет или нет (хотя по смыслу не должна ничего) - жизнь пусть покажет.

26.12.2015, 17:18, "veramal" <notifications@github.com>:

**Comment by tuffnatty** [comment]
i - помета в формате словаря парсера, назначается всем, которые не NOMEN и не VERBUM

**Comment by asheimovich** [comment]
Тогда точно еще нельзя правило писать, потому что сейчас в этой куче бывают и наречия, и междометия и разные всякие местоимения и т.п. Постараюсь пройти их побыстрее.

26.12.2015, 20:00, "Phil Krylov" <notifications@github.com>:

**Comment by veramal** [comment]
Ну, "ничего" можно менять по мере обнаружения новых фактов, но сей

26 декабря 2015 г., 20:03 пользователь asheimovich <notifications@github.com

**Comment by veramal** [comment]
но сейчас про них в приницпе ничего не написано, и цепляют они всё, что
плохо лежит.

26 декабря 2015 г., 20:06 пользователь Vera Maltseva <malt.wh@gmail.com>
написал:

**Comment by adybo** [comment]
Если цепляют, то долой. Надо вписать.

**Comment by veramal** [comment]
Впрочем, ох, конечно, будет, т.к. в invar попадают застывшие формы
местоимений. А еще гы будет, увы. Впрочем, сейчас они почему-то nomen.

26 декабря 2015 г., 21:24 пользователь adybo <notifications@github.com>
написал:

**Comment by asheimovich** [comment]
Да, местоимения были Nomen. И частично, наверное, и останутся.

27.12.2015, 00:39, "veramal" <notifications@github.com>:

**Comment by veramal** [comment]
Вообще пока там всё кривововато сделано. В выводимом значении нужно писать
не 'у него', а 'тот.Loc'. А почему они номен - вроде хотели инвар еще
недавно?

27 декабря 2015 г., 0:41 пользователь asheimovich <notifications@github.com>
написал:

**Comment by adybo** [comment]
Да, но супплетивные формы местоимений по идее должны быть инвар

**Comment by asheimovich** [comment]
А какие вообще NOMEN? Если мы все падежные формы личных мест. ввели отдельными статьями, то они все invar. Только, напр., ".Loc" в SEMGLOSS писать нельзя.

27.12.2015, 00:51, "adybo" <notifications@github.com>:

**Comment by veramal** [comment]
А какие должны быть не инвар?

27 декабря 2015 г., 0:51 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
Ну, как-то должно быть понятно, что там локатив. Почему нельзя писать, там
только кириллица?

27 декабря 2015 г., 0:56 пользователь Vera Maltseva <malt.wh@gmail.com>
написал:

**Comment by asheimovich** [comment]
Может и можно...

27.12.2015, 00:57, "veramal" <notifications@github.com>:

**Comment by adybo** [comment]
Несупплетивные. Которые не сидят отдельным входом в словаре

**Comment by adybo** [comment]
Вообще semgloss это же не перевод, Аль, а то, что выводится в глоссировке. Поэтому, да, пусть будет с лок-ами и дат-ами

**Comment by veramal** [comment]
Ну, в смысле, в форме без падежей которые? Ну, это понятно.

27 декабря 2015 г., 0:59 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
сделали
