### ISSUE TITLE
чан: ошибочное ограничение

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#123]
После введения PresPt -чан я не очень подумала, когда добавила его сюда:
"25. После деепричастных показателей позиции 7 (Lim  ГАли, Convп (I)П,Convа; Convпас; Neg.Conv и Neg.Conv.Abl), а также PresPt чАн  может стоять только показатель Ass ОК из позиции Ptcl3 или пробел."

После него могут также стоять посессивно-падежный блок, так что ограничение надо снять - лучше в ближайшее время. В документе исправила.

**Comment by tuffnatty** [comment]
а можно мне пример для тестов?

**Comment by veramal** [comment]
Вот это еще хорошо бы сделать, довольно частотная штука. 
парчанда - д.б. разбор идти-PresPt.dial-Loc
