### ISSUE TITLE
Prosp после Perf не работает

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#126]
атыбызахчалар 'они хотят застрелить' - нет разбора
Где-то, видимо, стоит ограничение. Сейчас лень смотреть, пусть повисит.

**Comment by tuffnatty** [comment]
так они (Perf и Prosp) в одном и том же слоте.

**Comment by veramal** [comment]
а, значит, надо перестраивать. припоминает ли кто пример, где проспектив был был перед -чат? если нет, надо его пока пересадить к -чат пока

**Comment by tuffnatty** [comment]
Если так сделать, перестают разбираться полахча, узихча в соответствии с правилом сочетаемости **26. Показатели Pres чА, PresPt чАн, Dur чАТ, Dur.Iter чАдIр возможны только при наличии показателей позиции 2 (NF или NF.Neg) или 4. Indir тIр возможен при тех же условиях или при одновременном наличии показателей Neg ПА и Past ГАН.**
Правило 6 тоже надо обновить соответственно

**Comment by veramal** [comment]
Хорошо, попробую завтра подумать, сегодня мозги про корпус не хотят уже.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 9 апр. 2019 г. в 23:27, Phil Krylov <notifications@github.com>:

**Comment by veramal** [comment]
Передвинула в слот 5, обновила правила 5 и 26 (первую часть).

**Comment by veramal** [comment]
Сделано.
