### ISSUE TITLE
хариб - еще один повод ввести смену ряда после И

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#127]
Слово _хариб_ 'тюрьма', несмотря на то, что композит (<_хара иб_ 'черный дом'), пишется без дефиса. Но это не мешает принимать ему аффиксы переднего ряда даже по словарю: _харибде_ - в тюрьме. А парсер по лит.норме допускает только задний ряд. Т.о., смена ряда после И встречается:
- в сагайском и бельтырском диалектах сплошняком, в шорском диалекте местами 
- в русских заимствованиях, т.к. они ориентируются на последний слог
- в неразложимых композитах.

**Comment by adybo** [comment]
Первые два случая у нас отмечены. Композиты следует, вероятно разметить в словаре, иначе это будет безобразие - иб ведь только потому передний (в литературном), что это на самом деле первый слог. Т.е. надо ввести, что и непервого слога работает как переднерядный, если в поле deriv оно принадлежит к первому слогу непервой части композита (т.е. первый слог после символа +)

**Comment by veramal** [comment]
Слово с нарушением сингармонизма, но без И: акелерге - кыз. приносить. Хорошо бы завести словарную помету для таких слов, которым нужно сингармонировать с последней гласной.  На практике можно обойтись пометой rus, но идеологически странно.

**Comment by adybo** [comment]
Это прямо-таки общетюркский феномен, потому что это а(лып) кел-. Надо вносить акел  в словарь, а сингармонизм что по последней гласной основы , у нас вроде и так в правилах. Заметь, что с И совсем другое нарушение, а именно, и — пустой по сингармонизму гласный.

**Comment by veramal** [comment]
Акел внесла в последнюю версию. Как обновится, посмотрим, будет ли работать.

**Comment by veramal** [comment]
Акел работает. идет по переднему ряду, хорошо бы и хариб поправить.

**Comment by veramal** [comment]
Внесла в словарь помету "composite" в поле ETYM у хариб. Нужно, чтобы это приводило к переднерядности, если последняя гласная И.

**Comment by veramal** [comment]
Кстати, что-то для rus это правило сейчас не действует: автомеханигi не анализируется, а автомеханигы - да.

**Comment by adybo** [comment]
О, да, чтоб слог считался первым

**Comment by tuffnatty** [comment]
Добавил поддержку пометы composite

**Comment by veramal** [comment]
Работает.
