### ISSUE TITLE
никтерімді - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#128]
Д.б. ник-pl-pos1sg-Acc.dial. Посессивного склонения диалектных окончаний в парсере так пока и нет, но здесь-то не посессивное.

**Comment by tuffnatty** [comment]
Acc.dial ДI должно реализовываться как ні после м, нет?

**Comment by veramal** [comment]
Нет, нi после м разбирается просто через литературный вариант.

**Comment by tuffnatty** [comment]
Имею в виду, что Д не может реализоваться как д после м и потому и не рассматривается. Чтобы рассматривалось, надо сделать Т. Тогда запрещена для разбора как Acc.dial станет форма никтерімні

**Comment by veramal** [comment]
Да, верно. Исправила Д на Т в Acc.dial и Gen.dial.

**Comment by tuffnatty** [comment]
Внес в парсер. Теперь не срабатывает из-за как минимум одного из ограничений:
>16.5. Case2 не может следовать непосредственно за Pl1 или Poss1. Poss2 не может следовать непосредственно за Pl1.
>17. В поз. 13/17 Case набор аффиксов посессивного склонения выбирается: а) в случае заполнения позиций 12/16 (Poss) соответственно аффиксами не-множественного числа (т.е. 1pos.sg, 2pos.sg, 3pos и Gen.3pos); ~~б) при заполнении поз. 17 (Apos);~~ в) непосредственно после основ, у которых в поле FORM есть помета poss (неотделяемая принадлежность).

**Comment by veramal** [comment]
А, никтерiмнi все-таки идет через посессивное склонение. Тогда остается только внести Acc Т(I) в диалектные посессивные падежные показатели. Генитив пока не встречался. Заодно можно ввести прочие диалектные посессивные падежи в парсер, в описании они давно есть.

**Comment by adybo** [comment]
Следует однако понимать, что на самом деле там, видимо, в диалекте не морфонемы другие, а правила. 


>Среда,  3 октября 2018, 11:09 +03:00 от veramal <notifications@github.com>:
>
>Да, верно. Исправила Д на Т в Acc.dial и Gen.dial.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by adybo** [comment]
Пипл, у нас давно уж нет позиции 17 Apos, который аффикс мы обозвали Gen.3pos
А что именно не срабатывает?


>Среда,  3 октября 2018, 14:51 +03:00 от Phil Krylov <notifications@github.com>:
>
>Внес в парсер. Теперь не срабатывает из-за как минимум одного из ограничений:
>>16.5. Case2 не может следовать непосредственно за Pl1 или Poss1. Poss2 не может следовать непосредственно за Pl1.
>>17. В поз. 13/17 Case набор аффиксов посессивного склонения выбирается: а) в случае заполнения позиций 12/16 (Poss) соответственно аффиксами не-множественного числа (т.е. 1pos.sg, 2pos.sg, 3pos и Gen.3pos); б) при заполнении поз. 17 (Apos); в) непосредственно после основ, у которых в поле FORM есть помета poss (неотделяемая принадлежность).
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
Я уже написала выше, что не срабатывает из-за отсутствия диалектных вариантов в посессивном склонении.

**Comment by tuffnatty** [comment]
Про 17 Apos - это зачеркнутый пункт правила, который потерял зачеркивание при копипасте

**Comment by adybo** [comment]
ага, я нашла тоже


>Среда,  3 октября 2018, 21:50 +03:00 от Phil Krylov <notifications@github.com>:
>
>Про 17 Apos - это зачеркнутый пункт правила, который потерял зачеркивание при копипасте
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by tuffnatty** [comment]
Добавил диалектные поссессивные падежи

**Comment by veramal** [comment]
Ага, вроде все работает как надо.
