### ISSUE TITLE
полтырохчых: Ptcl2 продвигается к началу словоформы?

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#129]
_Аӌа іди **полтырохчых**._ - Дядя так же был. (Варвара Терентьевна, Чиланы)

Если найдутся еще примеры, то место Ptcl2 надо пересмотреть. Вообще, конечно, странно, т.к. обычно интраклитики вставляются на место бывшей границы словоформы, а между ТЫр и ЧЫК межсловную границу никак не заподозрить.

**Comment by veramal** [comment]
Форма разбирается правильно.

**Comment by adybo** [comment]
Таинственное все-таки это обращение во 2 лице; мне кажется, его надо разбирать как 2 лицо — или сделать днля него 1 лицо ласкательное? Но как это сделать автоматом?

  
>Пятница, 5 июня 2020, 14:45 +03:00 от veramal <notifications@github.com>:
> 
> 
>Closed  #129 .
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo
