### ISSUE TITLE
ох не работает

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#13]
Не разбирается: пар-ох - имеется-Ass, хыз-ох - девочка-Ass.

**Comment by adybo** [comment]
Оно пишется вместе или через черточку?
Хызох должно, согласно таблице

**Comment by veramal** [comment]
Вместе.

27 декабря 2015 г., 2:42 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
тогда должно

**Comment by tuffnatty** [comment]
хыз+ОК = хызоғ

**Comment by adybo** [comment]
Разве перед пробелом озвончается? Аль, не должно так быть! Глянь, пожалуйста, что написано!

**Comment by veramal** [comment]
Да, похожпе, дело в реализации К - вот ЧIК тоже не работает - что парарӌых,
что парарчых не разбираются.

27 декабря 2015 г., 17:06 пользователь adybo <notifications@github.com>
написал:

**Comment by asheimovich** [comment]
не вижу такого. Про ох - табл. 3. В правилах сандхи про такое тоже нет.

27.12.2015, 17:06, "adybo" <notifications@github.com>:

**Comment by veramal** [comment]
давайте все-таки это починим. ну и вообще как-то продолжим. тут все просто: морфонема К реализуется в х/к, если нет поводов для озвончения. т.е. когда К стоит в начале морфемы, важно, есть ли гласная/зв.согл. перед ней, а когда в конце - после нее. а морфонема Г реализуется как ғ/г во всех контекстах (кроме случаев слияния). кстати, Assum КАдАК  д.б. записан как КАдАГ. и Attr КI, как когда-то обсуждалось, не сливает свою согласную. если правило про выпадение К фонетическое, то надо или переделать его в морфонемное, или придумать новую морфонему для КI (но не Г, потому что оно бывает глухим)

**Comment by adybo** [comment]
Разница между Г и К состоит в том, что Г в интервокале обязательно выпадает. А К озвончается. В основах бывает, что и К выпадает, но вроде как эти случаи можно убить, введя возможный вариант конца основы Г. Т.е. в правилах про выпадение К сейчас написана лирика, которую я не вычеркивала, чтоб не забыть, в том числе, найденные примеры, а так про него там не надо писать (это когда мы будем писать академический граммар хакасского языка, то там надо будет делать ср-ист комментарии, так это туда пойдет). Надо, видимо, выправить правила озвончения для К и еще выправить сам морфонемный состав морфем, поскольку иногда напортачено. Щас допишу отчот и займусь.

**Comment by veramal** [comment]
парох разбирается, не работают сандхи типа андох <анда+ох

**Comment by veramal** [comment]
андох - есть два разбора, один из которых противоречит ограничению 27 (Ptcl2 не может стоять на конце словоформы)

**Comment by tuffnatty** [comment]
исправил работу правила 27

**Comment by veramal** [comment]
Тогда можно закрывать.
