### ISSUE TITLE
туғлап - нет разбора через Distr КЛА

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#130]
А должен бы, т.к. ГГ->Г по фонетическому правилу, а не морфологическому.

**Comment by veramal** [comment]
А, нет, КЛА же с К начинается. а не с Г. Пардон.

**Comment by adybo** [comment]
Да, верно!


>Среда,  7 ноября 2018, 23:03 +03:00 от veramal <notifications@github.com>:
>
>А должен бы, т.к. ГГ->Г по фонетическому правилу, а не морфологическому.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by adybo** [comment]
Вообще там будет мфнл выбор -глА, потому что после звонкого, а потом фонетика потребует устранить второе г, разве не так?



>Среда,  7 ноября 2018, 23:03 +03:00 от veramal <notifications@github.com>:
>
>А должен бы, т.к. ГГ->Г по фонетическому правилу, а не морфологическому.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
Что-то я уже запуталась. Но вроде у нас так написано, что устраняется только г из Г.

**Comment by adybo** [comment]
надо проверить!


>Четверг,  8 ноября 2018, 11:30 +03:00 от veramal <notifications@github.com>:
>
>Что-то я уже запуталась. Но вроде у нас так написано, что устраняется только г из Г.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by adybo** [comment]
Вот правило из статьи, которое должно потом обеспечивать устранение Г из любого!

Морфонема К выбирает репрезентацию К после гласной и глухой согласной, Г после звонкой, в том числе носовой согласной.


>Четверг,  8 ноября 2018, 11:30 +03:00 от veramal <notifications@github.com>:
>
>Что-то я уже запуталась. Но вроде у нас так написано, что устраняется только г из Г.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo
