### ISSUE TITLE
качинско-кызыльский презенс -тур

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#132]
Пора ввести в описание, довольно частотный показатель. По действующей орфографии он пишется отдельно: _пар турлар_ 'они идут', т.к. не сингармонирует и не меняет согласную. Но если у качинцев он еще сохраняет форму _тур_, то у кызыльцев отбрасывает -р при спряжении: _мин партум_ 'я иду' - и тут уж совсем странно писать его отдельно. Так что в расшифровках пишу слитно.
Нужны две формы: _тур_ и _ту_. Распределение такое же, как у ЧАнг и ЧА. Начальное т не озвончается (как бы это провести мимо интервокального правила?)

Для литературного написания нужно будет ввести, видимо, лексический вход тур со значением Pres.dial и определить ему новый грамматический класс, который может спрягаться, но не склоняться (вообще-то он не один такой, заодно включить в этот класс настоящие предикативы).

**Comment by adybo** [comment]
Слушай, тогда надо всем этим видовым глаголам разделить лексические входы на собственно лексические и грамматические.
Да, для качинского, в том числе для старых романов, это важно. 
Давайте соберемся и проверим грамматическую таблицу!!!!!


>Суббота, 22 декабря 2018, 12:49 +03:00 от veramal <notifications@github.com>:
>
>Пора ввести в описание, довольно частотный показатель. По действующей орфографии он пишется отдельно:  пар турлар 'они идут', т.к. не сингармонирует и не меняет согласную. Но если у качинцев он еще сохраняет форму  тур , то у кызыльцев отбрасывает -р при спряжении:  мин партум 'я иду' - и тут уж совсем странно писать его отдельно. Так что в расшифровках пишу слитно.
>Нужны две формы:  тур и  ту . Распределение такое же, как у ЧАнг и ЧА. Начальное т не озвончается (как бы это провести мимо интервокального правила?)
>Для литературного написания нужно будет ввести, видимо, лексический вход тур со значением Pres.dial и определить ему новый грамматический класс, который может спрягаться, но не склоняться (вообще-то он не один такой, заодно включить в этот класс настоящие предикативы).
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
Слитное написание работает. Раздельное написание будет работать при обновлении словаря.
