### ISSUE TITLE
итератив -ады/-шады

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#133]
Сейчас у нас есть показатели итератива "адыр" и "чадыр" (Dur.Iter). Но в кызыльских текстах встречаются формы без конечного -р: 
Анаң черковный ӱлӱкӱннердi **пiллидiм** [лит. пiл-глидiр-ім - знать-Distr:Iter-1sg]. 
Потом церковные праздники знаю.

Мин оңдайлабалғам, **шуртапшадым** [лит. чурта-п-чадыр-ым - жить-NF-Dur.Iter-1sg]. 
Я отремонтировала, живу.

Ой, ундудыбзадым [лит. ундуд-ыбыз-адыр-ым  - забывать-Perf-Iter-1sg] 
Ой, забываю

Ам мен, эбге келп, **одырчадым**.
Теперь я, домой вернувшись, сижу. [лит. одыр-чадыр-ым - сидеть-Dur.Iter-1sg]

Надо добавить в описание.

**Comment by veramal** [comment]
Встречается и на конце слова (а также будущее такое тоже есть, но скорее у качинцев):
_Абаканда **чуртапчады** Катя Ульчугачева._ 
В Абакане живёт Катя Ульчугачева.

_Ну, **чари**, тимнезiннер столларын._ 
Ну, хватит, пусть стол готовят.

**Comment by adybo** [comment]
Вера, наверное, надо завести отдельный раздел про диалектную грамматику и туда все это писать, чтоб не потерялось. Нам это нужно вставить в морфологическую зону опросника/карт.


>Суббота, 22 декабря 2018, 13:07 +03:00 от veramal <notifications@github.com>:
>
>Сейчас у нас есть показатели итератива "адыр" и "чадыр" (Dur.Iter). Но в кызыльских текстах встречаются формы без конечного -р:
>Анаң черковный ӱлӱкӱннердi  пiллидiм [лит. пiл-глидiр-ім - знать-Distr:Iter-1sg].
>Потом церковные праздники знаю.
>Мин оңдайлабалғам,  шуртапшадым [лит. чурта-п-чадыр-ым - жить-NF-Dur.Iter-1sg].
>Я отремонтировала, живу.
>Ой, ундудыбзадым [лит. ундуд-ыбыз-адыр-ым  - забывать-Perf-Iter-1sg]
>Ой, забываю
>Ам мен, эбге келп,  одырчадым .
>Теперь я, домой вернувшись, сижу. [лит. одыр-чадыр-ым - сидеть-Dur.Iter-1sg]
>Надо добавить в описание.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by adybo** [comment]
Вероятно фонетика


>Суббота, 22 декабря 2018, 13:53 +03:00 от veramal <notifications@github.com>:
>
>Встречается и на конце слова (а также будущее такое тоже есть, то скорее у качинцев):
>Абаканда  чуртапчады Катя Ульчугачева.
>В Абакане живёт Катя Ульчугачева.
>Ну,  чари , тимнезiннер столларын.
>Ну, хватит, пусть стол готовят.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
Ну я пока складываю в файл все это, как попадается в тексте.

**Comment by veramal** [comment]
Формы на -ады, -чады сделали, про -шады решили, что это вариант -чады.
