### ISSUE TITLE
PredPl ЛА и другое

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#134]
В качинских текстах нередко встречаются формы с отсутствием -р в ЛАр - причем, кажется, только у предикатов.
_Анаң олар аңнап парыбыстырла_
Потом они ушли на охоту

_оларның палалары тоже тадарлап чоохтасчаңна_
их дети тоже на хакасском разговаривали.

Будем это вводить в грамматику, или считаем фонетикой, как в инфинитиве? Еще у Варвары Егоровны (из Шира) и ее дочери есть варианты личных местоимений без -р: _ола_ 'они' и _ciре_ 'вы'. У остальных не отмечено Эльвирой, надо слушать. Но вряд ли это внутрисемейная особенность.

**Comment by adybo** [comment]
Фонетика ли это? Проверяется на формах будущего времени.


>Суббота, 22 декабря 2018, 13:49 +03:00 от veramal <notifications@github.com>:
>
>В качинских текстах нередко встречаются формы с отсутствием -р в ЛАр - причем, кажется, только у предикатов.
>Анаң олар аңнап парыбыстырла
>Потом они ушли на охоту
>оларның палалары тоже тадарлап чоохтасчаңна
>их дети тоже на хакасском разговаривали.
>Будем это вводить в грамматику, или считаем фонетикой, как в инфинитиве? Еще у Варвары Егоровны (из Шира) и ее дочери есть варианты личных местоимений без -р:  ола 'они' и  ciре 'вы'. У остальных не отмечено Эльвирой, надо слушать. Но вряд ли это внутрисемейная особенность.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
С введением нормализации эта проблема отпадает.
