### ISSUE TITLE
Past ГА + 1sg ПЫн

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#135]
Сейчас у нас это запрещено, но люди в Трошкино так говорят:

_Хара тоғыс, я, **тоғынғабын**._
Чёрную работу, да, я делала.

_мин анда ветеринарные работы полностью мин **иткебiн**_
я там ветеринарные работы полностью делала

**Comment by adybo** [comment]
Я англоязычную статью уже отправила Йохансону, а ведть это по той части.


>Суббота, 22 декабря 2018, 14:24 +03:00 от veramal <notifications@github.com>:
>
>Сейчас у нас это запрещено, но люди в Трошкино так говорят:
>Хара тоғыс, я,  тоғынғабын .
>Чёрную работу, да, я делала.
>мин анда ветеринарные работы полностью мин **иткебiн **
>я там ветеринарные работы полностью делала
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
В той статье был бельтырский диалект вроде как. А так-то тема довольно бесконечная. Но в целом ясно, что на севере есть -бын, а на юге его нет.

**Comment by adybo** [comment]
Просто рассматривались разницы в формообразовании хакасских диалектов; вообще-то у -ган исторически должен быть -бын в финитной форме, но у множества кыпчаков и у нас тоже туда в глагольную форму залезает -м (вероятно, срабатывает аналогия с прошедшим на -ды). -зынг, как мы наблюли, так и остается. 


>Воскресенье, 23 декабря 2018, 12:45 +03:00 от veramal <notifications@github.com>:
>
>В той статье был бельтырский диалект вроде как. А так-то тема довольно бесконечная. Но в целом ясно, что на севере есть -бын, а на юге его нет.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
тоғынғабын, иткебiн разбираются правильно
