### ISSUE TITLE
тартыплачалар - не работает

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#136]
Перед LA бывает ЫП после согласной, чтобы отличить от ГЛА, из которого Г нередко выпадает. Добавила в правило 4.1 такую возможность, надо реализовать.

**Comment by veramal** [comment]
Не только после скопления согласных так бывает - вот в качинском у музейщицы:
Хадар**ыпла**чадырбын аны - Сторожу его

**Comment by adybo** [comment]
А перед этим ла вообще когда-нибудь падает п? Это же отыменной глагол по происхождению, т.е. вобщем категориально другой тип границы, чем штуки на бывшей границе словоформы


>Пятница, 11 января 2019, 0:19 +03:00 от veramal <notifications@github.com>:
>
>Не только после скопления согласных так бывает - вот в качинском у музейщицы:
>Хадар ыпла чадырбын аны - Сторожу его
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo
