### ISSUE TITLE
внутренние падежи vs внешние

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#137]
Попробовала задать такой запрос: Loc в слоте 13 + 3pos в слоте 16. Таких штук в принципе не очень много, но нашлась куча примеров, где локатив стоит после посессива (например, соонда 'после')- то есть обычный внешний падеж. А весь смысл запроса в том, чтобы найти внутренний падеж.
Поэтому падежи из слота 13 надо отделить от падежей слота 17. И посессивность тоже - 12-ю от 16-й. Вот 3pos1 уже есть, другие надо так же пометить - в 12 и 13 слотах поставить морфемам индекс 1, в 16 и 17 - никакого.

**Comment by veramal** [comment]
Теперь в 17 слоте вообще нет локатива и обычного аллатива - это хуже, чем было, т.к. перестали разбираться субстантивированные причастия и прилагательные в этих падежах. А также те существительные, которым нужно два посессивных маркера. 
_пазыларын_ - ок, разбирается как причастие и как существительное
_пазыларыда_ не разбирается

**Comment by tuffnatty** [comment]
Добавил индекс в 12-13 слотах и переразобрал корпус. Неразбор пазыларыда не имеет отношения к названиям аффиксов, можно нажать на неразобранное слово и в трассировке попробовать понять, где отметается правильная гипотеза (если она там есть)

**Comment by veramal** [comment]
Это была опечатка вместо _пазыларында_. Теперь есть нужный разбор (через лексему "голова").
