### ISSUE TITLE
качинско-кызыльская частица чых

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#138]
Семантика типа фокусной -дыр, кажется. Возможно, это уже имеющийся у нас ЧЫК, а может, и нет.

Но Ӱӱсті, по-моему, Валентина **кемчік**-те ол, Янгулова пасхан.
Но про Июс, по-моему Валентина, как же ее, Янгулова писала.

Арғыстар, паза хайди-та аның ады. Вот ундудубзадым, ундудубзадым. Ой, **хайдичых** са?
Вот забываю, забываю. Ой, как же это? 

И чоохтаам анда в окошечко нашего надо... **хайдағчых** полған... поған ол?.
И рассказала там в окошечке нашего надо... как же был... был он?

Тiгi, ой, имечiк се те? 
Это, ой, что же это?

**Comment by adybo** [comment]
Похож!


>Воскресенье, 10 февраля 2019, 23:27 +03:00 от veramal <notifications@github.com>:
>
>Семантика типа фокусной -дыр, кажется. Возможно, это уже имеющийся у нас ЧЫК, а может, и нет.
>Но Ӱӱсті, по-моему, Валентина  кемчік -те ол, Янгулова пасхан.
>Но про Июс, по-моему Валентина, как же ее, Янгулова писала.
>Арғыстар, паза хайди-та аның ады. Вот ундудубзадым, ундудубзадым. Ой,  хайдичых са?
>Вот забываю, забываю. Ой, как же это?
>И чоохтаам анда в окошечко нашего надо...  хайдағчых полған... поған ол?.
>И рассказала там в окошечке нашего надо... как же был... был он?
>Тiгi, ой, имечiк се те?
>Это, ой, что же это?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
Анализируется даже, если пририсовать хвостик к ч. Так что к парсеру вопросов пока нет. Но надо не забыть эту деталь в принципе. -дыр тоже есть, в том числе у тех же информантов, что и -чых (В. Дьяконовой и Марии Романовны).

**Comment by adybo** [comment]
Вписать вопросик в Изоглоссы


>Воскресенье, 10 февраля 2019, 23:37 +03:00 от veramal <notifications@github.com>:
>
>Анализируется даже, если пририсовать хвостик к ч. Так что к парсеру вопросов пока нет. Но надо не забыть эту деталь в принципе. -дыр тоже есть, в том числе у тех же информантов, что и -чых (В. Дьяконовой и Марии Романовны).
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo
