### ISSUE TITLE
неверный разбор с Dat в позиции предиката

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#139]
тоғынғабыс имеет один из разборов такой:
тох-(з)Ы-(н)ГА-ПЫс
решётка-3pos-Dat.dial-1pl

Все же предикативные показатели возможны только после Loc и Abl. Пока аллатив не очень мешает,  а вот датив весьма. Если не найдется убедительных примеров, нужно запретить - порождать совсем уж паразитические разборы нехорошо. Дописала ограничение на датив в правило 29.

**Comment by adybo** [comment]
Что ди не бывает — мы — на его решетку?

  
>Понедельник, 3 августа 2020, 13:31 +03:00 от veramal <notifications@github.com>:
> 
> 
>тоғынғабыс имеет один из разборов такой:
>тох-(з)Ы-(н)ГА-ПЫс
>решётка-3pos-Dat.dial-1pl
>Все же предикативные показатели возможны только после Loc и Abl. Пока аллатив не очень мешает, а вот датив весьма. Если не найдется убедительных примеров, нужно запретить - порождать совсем уж паразитические разборы нехорошо. Дописала ограничение на датив в правило 29.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Ни одного примера, где личное окончание вешалось бы на датив, пока не встретилось. Эльвира вроде отрицала такого рода образования. Можно спросить еще раз, конечно.

**Comment by tuffnatty** [comment]
такое правило не поможет - в разборе не Dat, а Dat.dial

**Comment by veramal** [comment]
Дописала  диалектные варианты в правило.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 4 авг. 2020 г. в 15:15, Phil Krylov <notifications@github.com>:

**Comment by veramal** [comment]
Сейчас нет такого разбора.
