### ISSUE TITLE
прошедшее время на -ган

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#14]
Какое-то изысканное распределение ошибок - а между тем самая частотная глагольная форма.

Работает: парған, тiккен, санаан.
Не работает: пiрген, сыххан, тiлеен.

Т.е. если широкий гласный работает, то парный ему вариант с узким не работает - и наоборот.

**Comment by adybo** [comment]
Ой, это я не знаю почему

**Comment by veramal** [comment]
исчезло
