### ISSUE TITLE
нестяжение долгих гласных в Fut

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#140]
Все-таки вынесу в отдельный топик, т.к. это важно. Неверный анализ многих словоформ прошедшего времени как форм будущего возникает из-за того, что допускается нестяжение _АА_ в _и_. Например, _ойнаабыс_ ('мы играли') разбирается в том числе и так: 
ойна-А-ПЫс
играть-Fut-1pl.mix

Явный глюк.

**Comment by adybo** [comment]
Да. Но по идее в шорском диалекте может и не стягиваться — как с -баан-

  
>Понедельник, 3 августа 2020, 13:35 +03:00 от veramal <notifications@github.com>:
> 
> 
>Все-таки вынесу в отдельный топик, т.к. это важно. Неверный анализ многих словоформ прошедшего времени как форм будущего возникает из-за того, что допускается нестяжение  АА в  и . Например,  ойнаабыс ('мы играли') разбирается в том числе и так:
>ойна-А-ПЫс
>играть-Fut-1pl.mix
>Явный глюк.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
В шорском и будущее не стягивается. Но в хакасском такой опции нет.

**Comment by adybo** [comment]
а в диалектном?

  
>Понедельник, 3 августа 2020, 17:46 +03:00 от veramal <notifications@github.com>:
> 
> 
>В шорском и будущее не стягивается. Но в хакасском такой опции нет.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Нету таких диалектов. По крайней мере, не попадалось пока.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 3 авг. 2020 г. в 19:59, adybo <notifications@github.com>:

**Comment by tuffnatty** [comment]
принудил стяжение
