### ISSUE TITLE
ң не должен выпадать на конце аффикса

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#141]
Опять вылез какой-то фантастический разбор:
пічиин
n пічі ‛Биджа’
-----------(Ы)ң----(з)Ы-Н------
-----------2pos.sg₁----3pos-Acc₂------

Не могу вспомнить, в каком случае нам нужен один посессив сразу после второго. Но тут главное даже не это, а то, что в результате действия морфонологических правил не должен выпадать ң. маркирующий 2sg. Или даже скорее ң на конце аффикса - в генитиве тоже ведь не выпадет ни при каких условиях.

**Comment by tuffnatty** [comment]
На данный момент не воспроизводится

**Comment by veramal** [comment]
Да, этого нет сейчасю
