### ISSUE TITLE
сығыбоғысчых - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#143]
сығыбоғысхан при этом разбирается.

**Comment by veramal** [comment]
Правило 5.1 пропускает. Больше не вижу ничего про Perf0 или про ЧЫК.

**Comment by tuffnatty** [comment]
Думаю, тут срабатывает правило 5 - Ass₁ возможен с Past, но невозможен с Affirm

**Comment by veramal** [comment]
В правиле 5 вроде не сказано, что при  Ass₁ и  Past невозможны другие
морфемы.

**Comment by tuffnatty** [comment]
В правиле 5 перечислен исключительный список морфем, при которых возможен Ass₁. В сығыбоғысчых ни одной из этих морфем не обнаруживается, в отличие от сығыбоғысхан

**Comment by veramal** [comment]
Да, торможу. Подумаю еще завтра на свежую голову, чего там добавить.

сб, 21 нояб. 2020 г. в 23:34, Phil Krylov <notifications@github.com>:

**Comment by veramal** [comment]
Добавила, вроде и нечего больше, кроме ЧЫК.

**Comment by veramal** [comment]
Нет, надо все же 5 переписать, не чини пока.

**Comment by veramal** [comment]
Переписала правило 5, можно чинить.

**Comment by tuffnatty** [comment]
С новым правилом 5 починились сығыбоғысчых, чӧрібӧгісчік, иртібӧгісчік; но у чуртабохчабыс исчез разбор с Hab (см. #111)

**Comment by veramal** [comment]
Это правильно, что убрался.

пн, 23 нояб. 2020 г., 15:34 Phil Krylov <notifications@github.com>:

**Comment by tuffnatty** [comment]
Выкатил
