### ISSUE TITLE
не разбирается последовательность Perf-Perm

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#144]
Например, парыбыстах - нет разбора, парыбыс и пардах - есть разбор.

**Comment by tuffnatty** [comment]
> 22. Показатель Perm присоединяется только к императивным показателям из поз. Person, к отрицанию ПА или к чистой основе слов категории Verbum (имеющей значение Imp.2sg).

**Comment by veramal** [comment]
Добавила в 22 показатели, которые могут быть у императива.

**Comment by veramal** [comment]
сейчас разбирается.
