### ISSUE TITLE
Opt ГАй надо признать причастием

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#145]
Вот такое попалось в сказках ("Семь слепцов"):
_оолағы кіріп килгенде, сығара **чӱгӱртібіспейін** тіп, чадарын хадарып алып_ - когда её сын вошёл, [она], **чтобы [он] не выбежал**, решила подождать, когда [он] ляжет
Сейчас выделенная форма не разбирается, т.к. оптатив считается финитным и не может присоединять падежи и посессивность. Нужно записать его в правилах как причастную форму.
PS Еще тут пропущена долгота, форма, которая должна разбираться - чӱгӱртібіспеейін.

**Comment by adybo** [comment]
А это не презентное причастие-деепричастие на -а? Не оптатив

  
>Воскресенье, 16 августа 2020, 15:57 +03:00 от veramal <notifications@github.com>:
> 
> 
>Вот такое попалось в сказках ("Семь слепцов"):
>оолағы кіріп килгенде, сығара  чӱгӱртібіспейін тіп, чадарын хадарып алып - когда её сын вошёл, [она],  чтобы [он] не выбежал , решила подождать, когда [он] ляжет
>Сейчас выделенная форма не разбирается, т.к. оптатив считается финитным и не может присоединять падежи и посессивность. Нужно записать его в правилах как причастную форму.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Нет, оно с отрицанием не встречается.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 16 авг. 2020 г. в 17:03, adybo <notifications@github.com>:

**Comment by veramal** [comment]
А вот еще оттуда же причастие на -ай, но не ГАй, а чАй:
_Ах торғы алаты **ағылчийи** мин полып, алтын столға **одырчийи** ханың оолғы полтырно [полтыр ноо] тіп, тарыныбысты._ - Белый шёлковый платок мне приносить — а за золотым столом сыну хана сидеть суждено? — так сказав, рассердился.

То, что это именно причастие с показателем 3pos, видно в предыдущем предложении, где оно запараллелено с ГАн:
_аар чобағны **кӧргені** пасха кізі, алтын столға **одырчийи** ханың оолғы полтырно [полтыр ноо]._ - Тяжкое страдание другому человеку испытывать — а за золотым столом сыну хана сидеть суждено!

**Comment by adybo** [comment]
Еще причастие на чай! Это слитное ча-Гай, что ли?

  
>Понедельник, 17 августа 2020, 0:39 +03:00 от veramal <notifications@github.com>:
> 
> 
>А вот еще оттуда же причастие на -ай, но не ГАй, а чАй:
>Ах торғы алаты  ағылчийи мин полып, алтын столға  одырчийи ханың оолғы полтырно [полтыр ноо] тіп, тарыныбысты. - Белый шёлковый платок мне приносить — а за золотым столом сыну хана сидеть суждено? — так сказав, рассердился.
>То, что это именно причастие с показателем 3pos, видно в предыдущем предложении, где оно запараллелено с ГАн:
>аар чобағны  кӧргені пасха кізі, алтын столға  одырчийи ханың оолғы полтырно [полтыр ноо]. - Тяжкое страдание другому человеку испытывать — а за золотым столом сыну хана сидеть суждено!
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Переместила ГАй в причастия в таблице. На него теперь должно распространяться правило 2.

**Comment by veramal** [comment]
чӱгӱртібіспеейін - есть разбор
