### ISSUE TITLE
паритчадып: переселение дуративов

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#146]
Сейчас не разбираются формы типа _сыхпаанчатхан_ - а встречаются в шорских текстах (литературный аналог _сыхпинчатхан_).

**Comment by veramal** [comment]
Дописала эту возможность в правилах 4 и 26.

**Comment by tuffnatty** [comment]
Добавление Dur.dial чаТ в правило 26 ломает паритчадып из-за взаимоисключающего правила 7

**Comment by veramal** [comment]
Тут проблема не в самом правиле 26, а в том, что ЧАт образуется только от NF-основы, а ит - от чистой основы (иначе NF-основа у вылезла бы в виде п (и была бы форма _парыпит_ по правилам). Однако NF сидит на 2 позиции, а Dur1 - на 5, поэтому объявить в _паритчадып_ наличие нулевого NF мы не можем, поскольку перед _ит_ он будет ненулевой. Т.о. есть два пути решения: 1)(читерский) объявить, что ЧАт может не иметь NF-основы, если ему предшествует что-то из 5 позиции 2) (геморройный) переместить малые дуративы поближе к основе - прямо в первую позицию. Тогда не понадобится вот эта странная часть "Показатели Dur1 и(р), Dur1.dial.kac Ат и Dur1.dial.sag ит заполняются только, если предыдущие позиции (Distr, Voice, NF, Ptcl1, Perf) не заполнены".
Насчет Ат я не уверена, впрочем - он точно сочетается и с другими основами, но насчет возможности стоять после залогов надо уточнить.
Что скажете?

**Comment by adybo** [comment]
**парыбит
 
Если перед малыми дуративами никогда не вылазит -ып, это скорее всего свидетельствует о том, что они в реале (исторически) образуются с другим деепричастием (на -Ай), что возможно, поскольку их первая гласная показывает й-стяжение. Тогда их, конечно, надо ставить в одну позицию с НФ.

  
>Суббота, 22 августа 2020, 12:30 +03:00 от veramal <notifications@github.com>:
> 
> 
>Тут проблема не в самом правиле 26, а в том, что ЧАт образуется только от NF-основы, а ит - от чистой основы (иначе NF-основа у вылезла бы в виде п (и была бы форма  парыпит по правилам). Однако NF сидит на 2 позиции, а Dur1 - на 5, поэтому объявить в  паритчадып наличие нулевого NF мы не можем, поскольку перед  ит он будет ненулевой. Т.о. есть два пути решения: 1)(читерский) объявить, что ЧАт может не иметь NF-основы, если ему предшествует что-то из 5 позиции 2) (геморройный) переместить малые дуративы поближе к основе - прямо в первую позицию. Тогда не понадобится вот эта странная часть "Показатели Dur1 и(р), Dur1.dial.kac Ат и Dur1.dial.sag ит заполняются только, если предыдущие позиции (Distr, Voice, NF, Ptcl1, Perf) не заполнены".
>Насчет Ат я не уверена, впрочем - он точно сочетается и с другими основами, но насчет возможности стоять после залогов надо уточнить.
>Что скажете?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by tuffnatty** [comment]
_паритчадып_ по-прежнему сломан

**Comment by veramal** [comment]
Перенесла все дуративы для пар- и кил- в ту же позицию, где NF. Стерла лишнее в правиле 7.

**Comment by adybo** [comment]
Да, если после *bar-a- и -перед *yor- не втыкалась частица, то все так. Надо бы поглядеть, что в чулымском, там деепр. на -а, кажется, чаще употребляется.

  
>Понедельник, 23 ноября 2020, 15:22 +03:00 от veramal <notifications@github.com>:
> 
> 
>Перенесла все дуративы для пар- и кил- в ту же позицию, где NF. Стерла лишнее в правиле 7.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Если втыкалась, можно предположить, что выглядеть это будет иначе, т.к. не
появится И на стыке. Но пока Радлова не дочитаем, точно не наткнемся.

пн, 23 нояб. 2020 г., 15:54 adybo <notifications@github.com>:

**Comment by tuffnatty** [comment]
Перенес, все хорошо, только паритчадып опять противоречит правилу 26.

**Comment by veramal** [comment]
Добавила в 26 упоминание о Dur1.

**Comment by tuffnatty** [comment]
Поправил, паритчадып работает
