### ISSUE TITLE
посессив от основ на г

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#147]
_марығ_ - есть разбор, _марығы_ - нет разбора
стяженная форма марии рзбирается
при этом у обоих посессивов от _тағ_ (_таа_, __тағы_)  разбор есть
в переднем ряду то же самое: тiрiгi - не разбора, пигi - есть разбор.
форма 3pos от аншлаг - аншлагы - тоже не разбирается, хотя какие-то русские слова умеют быть с посессивом (залогы, айсбергi)

**Comment by tuffnatty** [comment]
> Выпадение конечной Г из основы делится на несколько случаев.: 
> - многосложная основа существительных [выпадает всегда]: улуғ ‘большой’ + -ы > улии ‘старший’, марығ ‘пари’ + -ы > марии ‘его пари’
>
> ...
> В прочих случаях на месте стяжения образуется длинная гласная, идентичная корневой:
> - односложная основа существительных [выпадает не всегда]: суғ ‘вода’ + -ы > суу (саңыс суу ‘сок калины’), пуғ ‘каприз, прихоть’ + -ы > пуу ‘его прихоть’, тағ ‘гора’ + -ы > таа ‘его гора’, сағ ‘сила’ + -ы > саа ‘его сила’, пағ ‘веревка’ + -ы > паа ‘его веревка’, кöг ‘песня’ + -i > кöö ‘его песня’, сиг ‘черта’ + -i > сии ‘его черта’; 
>
>   НО хан-пиг ‘правитель’ +-i > хан-пигі ‘его правитель’, ағ ‘сеть’ + -ы > палых ағы ‘рыболовная сеть’, соғ ‘жар’ + -ы > соғы (кӧс соғы ‘жар углей’), чӱг ‘перо’ + -i > чӱгi ‘его перо’.

Вроде бы все согласуется?

**Comment by veramal** [comment]
Это устаревший вариант, основанный на презумпциях грамматики. В прошлогодней статье уже не так: "По имеющимся в настоящее время данным г, ғ в этом случае в литературном языке выпадают обязательно, но для части диалектов это не так; в нормативном словаре зафиксированы разные варианты, иногда форма принадлежности в грамматической зоне словаря БХРС выписана одним образом, а в примере попадается форма принадлежности от того же имени, образованная иначе; в грамматике этот вопрос подробно не рассматривается. В набор диалектологических анкет для хакасско-шорского ареала мы включили полный список слов с такими финалами."
Правда, там отделены примеры типа _марии_, которые в лит. языке вроде как всегда стягиваются, и те, что гуляют в словаре - но это, видимо, связано лишь с частотностью.

Ни одного случая нестяжения не зафиксировано лишь от хабитуалиса ЧАң.

Исправила описание в месте многосложных основ на Г.

**Comment by veramal** [comment]
марығы - есть разбор
