### ISSUE TITLE
ПИн+чАт 

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#148]
Ай Хууӌын, Строки 2592-2593
_"Паза хатап **тӧрібинчат**, Паза хатап **пӱтпинчат**!"_
"Больше не возродись, Больше не сотворись!"

Выделенные словоформы не разбираются. Не вижу в правилах ничего такого, что бы им мешало.

**Comment by veramal** [comment]
Хм, чудеса какие-то. В окошке разбирается, а в корпусе почему-то неразобранным осталось. Хотя другой пример такого типа и в корпусе разобрался:
_— Мыннаң, — тидір, — **аспинчат**, мыннаң азыра **парбинчат**._
— Дальше, — говорит, — не переходи, дальше не переступай! (Ӧксіс оол)

**Comment by tuffnatty** [comment]
наверное, это починилось с последними изменениями, а корпус пока не перепарсирован

**Comment by veramal** [comment]
Ага. Корпус пока не надо перепарсировать, я хочу нормализовать сказки и отредактировать по ним словарь к концу августа, тогда вывешу и перепарсируем. Грамматику тоже хорошо бы подтянуть к этому делу.
