### ISSUE TITLE
ошибка разбора: параан

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#149]
n параан ‛секции в юрте’
----------------------
----------------------
v парарға ‛идти’ пар
-----и---ГАн--------------
-----Dur1ᵢ---Past--------------

Второй разбор неверный, не должно быть стяжения.

**Comment by tuffnatty** [comment]
а какой из трех разборов второй? (теперь они упорядочены по числу аффиксов) Приведенный?

**Comment by veramal** [comment]
Да, приведенный.
Третий, кстати, тоже нехорош:
n пара ‛вентерь’
-----------(Ы)ң----(з)Ы-Н------
-----------2pos.sg₁----3pos-Acc₂------

Вроде мы это убивали?

**Comment by tuffnatty** [comment]
Это это?
> После долгих гласных и перед ними (_о_, _ӧ_ (за исключением заимствований), _и_ и все двойные) выпадения и стяжения не происходит

**Comment by tuffnatty** [comment]
Запретил стяжение с долгими гласными в нерусских словах на любом стыке, а не только на первом. пар+и+ГАн убрался, пара+(Ы)ң+(з)Ы+Н остался.

**Comment by veramal** [comment]
Да, оно.
Вентерь сейчас вынесу в отдельную задачу.
