### ISSUE TITLE
хастади - неверный разбор Loc-Gen.3pos

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#152]
n хас 2 ‛гусь’
------------ТА---Ди-------
------------Loc₁---Gen.3pos.dial-------

Нужно запретить эту последовательность, т.к. на самом деле лишь один из показателей Loc и Gen, за которыми следует посессивный показатель, может занять позицию внутреннего падежа, а вместе они там стоять не могут. Данный разбор неверен.

**Comment by adybo** [comment]
А как сказать «Тот, который в гусе» диалектно?

  
>Воскресенье, 20 сентября 2020, 16:53 +03:00 от veramal <notifications@github.com>:
> 
> 
>n хас 2 ‛гусь’
>------------ТА---Ди-------
>------------Loc₁---Gen.3pos.dial-------
>Нужно запретить эту последовательность, т.к. на самом деле лишь один из показателей Loc и Gen, за которыми следует посессивный показатель, может занять позицию внутреннего падежа, а вместе они там стоять не могут. Данный разбор неверен.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
хастадагызы

**Comment by veramal** [comment]
Написала новое ограничение 16.6.

**Comment by adybo** [comment]
А почему диалектный не может, а недиалектный может?

  
>Воскресенье, 22 ноября 2020, 23:38 +03:00 от veramal <notifications@github.com>:
> 
> 
>Написала новое ограничение 16.6.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by tuffnatty** [comment]
внес в парсер

**Comment by tuffnatty** [comment]
(недиалектный, видимо, тоже не может - там скобочки вокруг (.dial) - но их не сразу заметно)

**Comment by veramal** [comment]
Да, одинаково

пн, 23 нояб. 2020 г., 15:57 Phil Krylov <notifications@github.com>:

**Comment by tuffnatty** [comment]
ну, я так и сделал
