### ISSUE TITLE
добавить ТАА в Ptcl2 (перед окончанием)

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#153]
Внесла в таблицу, надо добавить в парсер. 
Примеры:
— Аттардаң*, **кӧрбеендеебін**, — тидір. - — Не то чтобы убить — даже не видел их! — говорит. (Атығӌы Парачап)
Адамның чуртын **сағынадырдаабын**, адам-іӌемні дее сағынадырбын
Я скучаю о селении своего отца, скучаю и о своем отце и матери! (Радлов)

**Comment by tuffnatty** [comment]
добавил, но кӧрбеендеебін запрещено правилом 20, а  сағынадырдаабын еще почему-то, возможно, тоже оно

**Comment by veramal** [comment]
Вроде 20 должно пропускать сағынадырдаабын, т.к. адыр само по себе с
полными окончаниями тоже сочетается.

**Comment by tuffnatty** [comment]
сағынадырдаабын запрещено правилом 14

**Comment by tuffnatty** [comment]
кӧрбеендеебін после вчерашних других изменений заработало, осталось расширить пр.14

**Comment by veramal** [comment]
Расширила.

**Comment by tuffnatty** [comment]
Добавил, теперь работают оба примера.

**Comment by veramal** [comment]
Тут всё.
