### ISSUE TITLE
диалектные инструменталисы

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#154]
Добавила в таблицу варианты _мнАӊ (посс. и непосс.), бАӊ (посс.), ПЫнаӊ (посс. и непосс.), мАӊ (посс.)_. Теперь надо добавить их в парсер.
Примеры:
_палых тутчаң, палых **идібең** азранӌаңмыс_
рыбу ловила, мясом рыб мы кормились (Атығӌы Парачап)
_— **Худайбынаң**, чааласханымны таныхтааннарох орден - медальларнаң._
— Слава богу, не зря награды имею. (Г.Г. Казачинова.)
_Пулар **кӧрерібінең**, ах пора ат кӧріп ох саған._
Они его увидели, светло-серый конь их тоже увидел. (Хара Махашы)
_Анаң **палтымнаң** ӱш айхах кезип, **палтымнаң** пага илиндирип ахан._
Затем топором три когтя отрубив, вместе с топором на верёвку она их повесила. (Іки адыгжи)
_Ханнығ Хылыс, алып кізі, **Тайызымнаң** танысхан_
Богатырь Ханныг-Хылыс С троюродным братом своим познакомился. (Алтын Арығ )
_Атығӌы Парачапты, позрах аттығ ікі атығӌыны **инейлерімең** хараибтең анда сығар-килгеннер._
Атыгджы-Парачапа, двоих охотников, на рыжих конях ездящих, вместе с жёнами затем из темницы вывели. (Атығӌы Парачап)

Как видим, во всех этих случая необычна посессивная форма падежа - не подставляется н после аффикса 3Pos, ибо и так носовой.

**Comment by tuffnatty** [comment]
готово
