### ISSUE TITLE
диалектный императив АК

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#155]
Внесла в таблицу, надо добавить в парсер.
В отличие от Prosp АК и подобно прочим императивам, не стягивает в _и_ гласную основы и свою, оставляет долгую А. Однако не понимаю, где это сейчас записать.
Примеры:
— Че, **парах**, пу чарых тасты алып ал, — тиді.
— Ну, поедем! Этот алмаз возьми! — говорит. (Сағышнаң Чааска)
Алныбыста турган Ах тага **сых-кӧрек**.
Давай на впереди стоящую гору Ах-таг поднимемся. (Алтын Тана хыс)

**Comment by adybo** [comment]
Если это типа шорского, то он так и должен

**Comment by adybo** [comment]
Что очень-оченьь существенно для истории тюркского спряжения: это, может быть, (I)K, окончание 1Pl краткой серии, которое до сих пор считалось, что в южно-сибирских языках не представлено, а инновативно возникло в центрально-западной зоне (но я всегда была против).
Вопрос: как в этом тексте ведет себя -ок? Если может гармонироваться по негубности, то это оно, присаженное к императивам пар, кёр. Если нет, то это -(ы)к, присаженный к старому презентному деепричастию на -а(й).

**Comment by veramal** [comment]
Встретилось только в формах -ах и -ек, иногда с долгим гласным. О́х сложно
отловить, т.к. про него строится гипотеза о частице - но вроде
подозрительных случаев не было.

**Comment by adybo** [comment]
Я собственно имела в виду, что либо это презенс на ай, плюс ЫК, либо это императив плюс делаб. ОК. Если выставляют долготу, то скорее ок, наверное, с презенсом не д.б. стяжения.

**Comment by veramal** [comment]
Презенс в императиве не супер как идея

**Comment by adybo** [comment]
Не супер, но случается

**Comment by adybo** [comment]
Но в  общем проще всего посчитать частицей ок

**Comment by veramal** [comment]
Почему ОК-то, если это АК? Проще всего посчитать отдельным показателем.

**Comment by adybo** [comment]
Да просто там не нужен никакой показатель, в императиве-то.

**Comment by veramal** [comment]
Почему? Это ж не простой императив, а инклюзивный.

**Comment by veramal** [comment]
Этот показатель надо добавить в парсер независимо от его происхождения.

**Comment by tuffnatty** [comment]
Хорошо бы пример для теста, отделяющий его от Prosp АК, например, с нестяжением

**Comment by veramal** [comment]
_Обалы чох кічіг нимені **Ӧдірбеек**, иркем Ай Хууӌын!"_
Безгрешное юное существо Убивать не станем, милая моя Ай-Хуучин!"

Кроме того, Prosp АК возможен только в середине, а Imp.1.Incl АК только в конце.

**Comment by veramal** [comment]
Думаю, надо все-таки два варианта ввести: ААК и АК. В "Ай-Хуучин" и в "Алтын-Арыг" записывается с долгой гласной, в сказках - с краткой. Или я поищу его в сказках и перепишу его на долгую в нормализации, там десяток-другой примеров.

**Comment by tuffnatty** [comment]
Добавил

**Comment by tuffnatty** [comment]
Но пока что с краткой

**Comment by veramal** [comment]
Хорошо. Сейчас пойму через полчасика, каких больше.

**Comment by veramal** [comment]
Вот еще третье того же вида, но на самом деле это ConvA + OK. 
_Анызы килген оозынаң **узик** пиртір._
Как только пришел, так и заснул. (Катанов)

Сейчас, кстати, нет такого разбора. Но, может, и не надо, т.к. все три примера на -ик(их) из Катанова, и все с основой узу-.

**Comment by veramal** [comment]
Думаю, можно ограничиться краткой: всего 8 примеров на долгую, на краткую десятка полтора.
