### ISSUE TITLE
диалектный делибератив 

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#157]
Добавила диалектную форму Delib ДАӊАрЫ в таблицу, надо ввести в парсер.

Примеры:
ӰС ХАРЫНДАС АҢНАП **ПАРХАНАҢАРЫ** - О ТОМ, КАК ТРИ БРАТА НА ОХОТУ ХОДИЛИ (в нормализации ПАРХАННАҢАРЫ)

ТОРҒАЙАХ **ХУСХАӋАХТАҢАРЫ** - О ЖАВОРОНКЕ-ПТИЧКЕ 

PS В посессиве не встретилось пока, поэтому нАӊАрЫ вводить пока не будем.

**Comment by tuffnatty** [comment]
Добавил, но ПАРХАН не бывает

**Comment by veramal** [comment]
Ага, работает.
