### ISSUE TITLE
АдЫр перед деепричастиями

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#158]
АдЫр употребляется с ConvA и ConvП, расширила правило 14.
Примеры:
Хыйғыли **парадыра** хыс пала, Чылғы чіли кістебіскен,
Клич бросив, девочка По-конски заржала (Ай Хууӌын)
Иди **парадырып**, шолын шидирип, пасха шолха кирпарды
Когда так шла, свою дорогу потеряв, по другой дороге пошла (Іки адыгжи)

**Comment by tuffnatty** [comment]
готово. Кстати, перед ТАА не надо тоже разрешить?

**Comment by veramal** [comment]
Перед вторым ТАА можно, да.

**Comment by veramal** [comment]
Тут вроде всё, с деепричастиями и с ТАА работает.
