### ISSUE TITLE
двойной дистрибутив

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#159]
Встречается в форме КлАГлА у Радлова и лАГлА позже.
Кӧрзе, анаң на чыланнар, сыылазып - сығырызып, **сыхлағлап** турлар оор сыхчатхан чирдең.
Видит: тут же змеи, шипя-свистя, из того места, откуда пар поднимается, стали выходить. (Табанах Матыр)
Хытайған хымранып усхынчадыр, Ирке тӧреен Иркӱлестің азағынаң **тартлағлапча**. - Хытайган, пошевелившись, просыпается, Милого Иркюлеса за ноги дёргает. (Ирке тӧреен Иркӱлес)
Аттарына нимелерін артхлағлапчалар. 
Вещи свои они навьючили на коней и поехали теперь домой. (Радлов)

**Comment by adybo** [comment]
Да, надо редуплицированный вариант в таблицу вписать

**Comment by veramal** [comment]
Добавила в таблицу лАКлА, надо ввести в парсер как Distr.dial.

**Comment by tuffnatty** [comment]
Добавил

**Comment by veramal** [comment]
А почему тут К не подходит как морфонема? Вроде у нас не было пока контекстов, когда следующая согласная была бы однозначно звонкой (л, а не Л). В парсере можно и G использовать, но мне для теории интересно, вроде К не противоречит.

**Comment by adybo** [comment]
вроде у нас к и г различаются только тем, что г выпадает, а к не выпадает.

  
>Понедельник, 23 ноября 2020, 17:04 +03:00 от veramal <notifications@github.com>:
> 
> 
>А почему тут К не подходит как морфонема? Вроде у нас не было пока контекстов, когда следующая согласная была бы однозначно звонкой (л, а не Л). В парсере можно и G использовать, но мне для теории интересно, вроде К не противоречит.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by tuffnatty** [comment]
Ну, это уступка парсеру - при выборе репрезентации морфонемы он смотрит не на ближайшую предшествующую согласную, а на предшествующую согласную за левой границей аффикса, и если там глухая - будет лекле/лахла, что неверно. Поэтому там для внутреннего использования введены морфонемы G (репрезентация ғ/г) и Q (репрезентация х/к).
