### ISSUE TITLE
Fut + Foc

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#160]
Дописала в правило 23 возможность фокусу ТЫр сочетаться с будущим, т.к. встретился пример:
адай улуп сыхтыр: «Ниме **чимдір**?» — тіп. - тогда собака зашла, оказывается: «Что я буду есть?» — сказала. (Худай кізее чурт пиргенінеңер)

**Comment by adybo** [comment]
красота

**Comment by veramal** [comment]
Еще пример нашелся:
_чӧптирзің ікі хат таа **чуртирдір**, хада чуртирбыс, — тидір инейі._ - и две жены тоже живут, вместе будем жить, — говорит его жена. (Ир Тохчын (кач))

**Comment by tuffnatty** [comment]
Добавил, но в примере __чуртирдір__ нарушена гармония, так что он не разбирается

**Comment by veramal** [comment]
Но чимдір работает, так что тут всё.
