### ISSUE TITLE
чоохтаанохпын - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#161]
Причина в том, что сочетание ГА(н) и ПЫн допускалось только для формы ГА. Если эти показатели стоят рядом, то так и есть, а если между ними вклинивается частица, то ГАн употребляется в полной форме. Сделала разделение этих случаев в правиле 20.
Исходный пример:
ікінӌізін хатабох **чоохтаанохпын**: «Кӧр, Самсон, пістің чирге чағын чӧрбе», — тіп.
второй раз я тоже говорил: «Смотри, Самсон, к нашей земле не приближайся». (Самсон хайӌыдаңар)

**Comment by adybo** [comment]
Ну точно

**Comment by tuffnatty** [comment]
Разрешил, но не проще ли разрешить для обоих вариантов, не конкретизируя, что там вклинилось? оставил коммент в документе

**Comment by veramal** [comment]
Я не понимаю, работает ли сейчас правило 9.1. Если да, то можно убрать
конкретику, конечно.

**Comment by tuffnatty** [comment]
А чего бы ему не работать? Оно не вычеркнуто

**Comment by veramal** [comment]
Убрала лишнее.
