### ISSUE TITLE
NF ПААн + Perf0 Ыс

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#162]
Заимствование из шорского, вероятно: при шорском отрицательном деепричастии ПААн возможен перфект в форме Ыс (а в форме ЫбЫс пока не встретился). Дописала это в правило 5.1.
Примеры:
Семон оолах ағылған хызынға **хынмаанысханда**, Абахай Пахта чаратхан Семон оолахха ікі хатпаң хонарға. 
Когда Семон-парень приведённую девушку разлюбил, Абахай-Пахта разрешила Семону-парню с двумя жёнами жить. (Абахай Пахта)
Соонаң, сизін саларлар тіп, **чӧрбееністір**.
Потом, чтобы не догадались, перестал ходить. (Тағ кізілерінеңер)

**Comment by adybo** [comment]
Так и должно быть; у нас была для хакасского плеонастическая форма пын-ыбыс, но по идее -ыб это дубликат деепричастного показателя, который уже есть в пын/паан (другой, чем -ып). Интересно только, не нарушим ли мы этим твердую границу между шорским и хакасским языками.

**Comment by tuffnatty** [comment]
Сделал. чӧрбееністір работает, а хынмаанысханда запрещено правилом 4.

**Comment by veramal** [comment]
По идее 4 не мешает:
Показатели NF, NF.Neg могут встретиться  ... 3) Perf  (Ы)бЫС, Ыс

**Comment by tuffnatty** [comment]
Но тут не NF и не NF.Neg, а NF.Neg.sh, про который далее правило говорит:
>Показатель NF.Neg.sh ПААн допустим при сочетании с Pres чА, чА, чАр(Ы), Dur чАТ, Dur.dial чаТ и Indir ТЫр.

**Comment by veramal** [comment]
Переписала.

**Comment by tuffnatty** [comment]
Разрешил

**Comment by veramal** [comment]
Работает.
