### ISSUE TITLE
Imp.1.Pl АлЫс - новая морфема

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#163]
Ввела в словарь, надо добавить в таблицу. Примеров не слишком много, но достаточно.

Тастаң салған очыхты талап кӧрееңер, Талғаннығ чахсы кӱлді Тооладып, чилге **хаптыралыс**!
Каменный очаг давайте сломаем, Хорошую золу с талканом Рассыплем, по ветру пустим! (Ай Хууӌын)
Постай Арығ, Сап оғылым пу кӱннерде айлаңар, мында сахтап **алалыс**
Постай-Арыг и сын мой Сап на днях вернутся, здесь их подождём. (Ӧӌең пиг_долгий)
Абаа кізі Хан Мирген, Айланып, нан **кӧрееліс**" (в нормализации кӧреліс)
Старший брат Хан-Мирген, Домой поедем, вернемся". (Ай Хууӌын )
Андағда **инеліс** аалға.
Тогда давайте спустимся к аалу. (Хара Махашы)
«Одырып, иркелерім, Ас чіп, суғ **ічееліс**».
«Садитесь, милые мои, Поедим, попьем». (Алтын Арығ)

При основах после гласной не встретился, но вероятно, оставляет А, как и прочие императивы.

**Comment by adybo** [comment]
Оптатив общетюркский

  
>Вторник, 27 октября 2020, 23:18 +03:00 от veramal <notifications@github.com>:
> 
> 
>Ввела в словарь, надо добавить в таблицу. Примеров не слишком много, но достаточно.
>Тастаң салған очыхты талап кӧрееңер, Талғаннығ чахсы кӱлді Тооладып, чилге  хаптыралыс !
>Каменный очаг давайте сломаем, Хорошую золу с талканом Рассыплем, по ветру пустим! (Ай Хууӌын)
>Постай Арығ, Сап оғылым пу кӱннерде айлаңар, мында сахтап  алалыс
>Постай-Арыг и сын мой Сап на днях вернутся, здесь их подождём. (Ӧӌең пиг_долгий)
>Абаа кізі Хан Мирген, Айланып, нан  кӧрееліс " (в нормализации кӧреліс)
>Старший брат Хан-Мирген, Домой поедем, вернемся". (Ай Хууӌын )
>Андағда  инеліс аалға.
>Тогда давайте спустимся к аалу. (Хара Махашы)
>«Одырып, иркелерім, Ас чіп, суғ  ічееліс ».
>«Садитесь, милые мои, Поедим, попьем». (Алтын Арығ)
>При основах после гласной не встретился, но вероятно, оставляет А, как и прочие императивы.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
--
Anna Dybo

**Comment by tuffnatty** [comment]
> Оптатив общетюркский  

Это в смысле, что его надо назвать по-другому или просто замечание о происхождении?

**Comment by veramal** [comment]
Да нет, вроде назвать надо императивом, т.к. оптатив у нас уже задействован во временном слоте.

**Comment by tuffnatty** [comment]
Добавил, ічееліс не разбирается, он ненормализованный?

**Comment by veramal** [comment]
Да, с одной е в нормализации.

вт, 1 дек. 2020 г., 1:20 Phil Krylov <notifications@github.com>:

**Comment by veramal** [comment]
ічееліс, алалыс разбираются
