### ISSUE TITLE
неопущение ЫП между согласными

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#164]
Формы типа _полыптыр_, _полыпча_ - довольно частотная вещь, но мы все еще думаем, нужно ли упрощать правило про чередование ЫП с нулем и пускать их на разбор.
Однако если правило не упрощать, то делать все равно что-то надо, т.к. при добавлении залоговых показателей их не учли в правилах. И теперь ЫП, который стоит между выделяемым залогом и чА (или ТЫр), не ломает анализ, а тот, что стоит после других согласных - ломает.
Вот пример, который выдал эту прореху:
_Сарғалып киліп, таң атханда, **Сусталыпчадып**, кӱн сыххан_ - Когда, желтизной разливаясь, рассвет наступил — Лучами играя, солнце взошло (Ай-Хуучин). Т.к. есть основа _суста_-, словоформа отлично разбирается.

**Comment by veramal** [comment]
Обнаружила, что у нас введено уже разрешение на -ып в основах с кластерами согласных (типа _тарт_, _ирт_), однако это не было отражено в описании. Распространила на все согласные, т.к. примеров очень много (только на ыптыр 45).

**Comment by veramal** [comment]
Правило 4.1.

**Comment by tuffnatty** [comment]
Привел правило 4.1 в парсере в соответствие документу
