### ISSUE TITLE
частица LА +Perf0 ЫС

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#167]
Вот такая форма встретилась:
_Малды іди пирзе, **чіплеізеді**._
Когда скот ему принесёт — всё съедает. (Іки адыгжи)

И еще попадавшийся ранее:
_Ол (Пычон) **тыыплаысхан** одыр, чіӌеен не чіпче._
Он (Пычон) сидит как истукан (букв. окаменело) и только знает, что ест да ест. (Н. Доможаков)

В правиле 5.1 написано, что Perf0 ЫС возможен при Part1 вообще, однако по факту сейчас разрешено только сочетание с ОК в этой позиции. Надо расширить.

**Comment by tuffnatty** [comment]
В парсере Perf0 (Ы)С, а не ЫС, поэтому Ы после гласной должно выпадать. В табличке сейчас написано `Perf0 (Ыс`, что явная опечатка. Как правильно?

**Comment by veramal** [comment]
Видимо, правильно вообще без скобок, ЫС, случаев с выражением Ы мы не
наблюдаем. В таблице исправлю чуть позже

**Comment by tuffnatty** [comment]
Ок, тогда чіплеізеді запрещено правилом 5, а тыыплаысхан заработало.

**Comment by veramal** [comment]
Расширила правило 5.

**Comment by tuffnatty** [comment]
сделал

**Comment by veramal** [comment]
Ага, здорово, работает.
