### ISSUE TITLE
ефикация

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#168]
шахтер - нет разбора, шахтёр - есть разбор
Нужно делать так, чтобы у всех Е рассматривался также вариант, что они могут быть Ё.

**Comment by tuffnatty** [comment]
Сделал на этапе конвертации словаря. Есть свежая версия?

**Comment by veramal** [comment]
Постараюсь завтра доделать.

сб, 21 нояб. 2020 г. в 21:41, Phil Krylov <notifications@github.com>:

**Comment by veramal** [comment]
Работает.
