### ISSUE TITLE
Граждане, призываю вернуться сюда и проверить, насколько обсуждавшееся здесь внесено в гуглфайл!

### ISSUE THREAD

**Issue by adybo** [tuffnatty/suddenly#17]

**Comment by asheimovich** [comment]
насколько я понимаю, в гуглфайле версия 12, а не 11. А ча изъято отовсюду, кроме дуратива, его точно там не может быть  (имею в виду твой призыв вернуть "презенс ча во времена")

**Comment by adybo** [comment]
Это не мой призыв, а цитата из чата на садденли. Да, 12.

**Comment by adybo** [comment]
А проверить надо в основном правила, из которых многие были на садденли обнаружены в неработе.

**Comment by asheimovich** [comment]
Так может выгнать оттуда версию 12 и загнать 11? Я не умею.  И как делать поиск по всем чатам?

**Comment by adybo** [comment]
Откуда? Там уже не 12 и не 11, т.е. мы многое оставили из 12, но вернули про итератив и Conv на а. А правила, о кот. я говорю - это правила стяжений, напр. Ну вот как сейчас образуется датив от слова на -й?

**Comment by adybo** [comment]
Я говорю о  темах здесь вот. Открываешь список тем и последовательн смотришь.

**Comment by asheimovich** [comment]
Я о них же. Думала, есть сплошной поиск. На всякий случай.

**Comment by veramal** [comment]
Все посмотрела. Неактуальное лежит в Issues: Closed.
