### ISSUE TITLE
выпадение ң не всегда уместно

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#171]
У параан есть неверный разбор:

n пара ‛вентерь’
-----------(Ы)ң----(з)Ы-Н------
-----------2pos.sg₁----3pos-Acc₂------

В сандхи по этому поводу написано вот что: 
"3.2. В аффиксах Hab ЧАң и 2pos.sg (Ы)ӊ конечная ң может попасть в интервокал. В Hab выпадение происходит, а в посессиве не происходит:
Сыдаҷаа чох 'невыносимый’  < сыда ‘выносить’+ҷаң + ы чох ‘не’; Тасхар чöрҷее чох соох 'Такой мороз, что на улицу не выйти’ (чöрҷее < чöр ‘ходить’ + ҷаң + ы).
vs адыңа  (ат + ың 2pos + а Dat) - твоей лошади"

На 2pos.sg₁ это тоже должно распространяться, конечно. Дописала.

**Comment by tuffnatty** [comment]
Ну, реализовано было и так с расчетом на оба слота. Но в некоторых ситуациях было сломано, починил
