### ISSUE TITLE
Perf + ЧЫК

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#172]
В списке не имеющих разбора рядом обнаружились такие словоформы:
_килбинібӧгісчік, чӧрібӧгісчік, иртібӧгісчік, пирбинібізерӌік_

килібізерӌік - есть разбор
В последнем случае, похоже, запрещено NF.Neg Пин + Perf Ыбыс, хотя в какой-то момент вроде работало.
В первых трех, видимо, где-то запрет на Perf Ыс + Affirm ЧЫК.

**Comment by veramal** [comment]
А, в первом совсем интересно, т.к. там сразу Бин + Ып + Ыс, что никак не стыкуется с нашей системой. Тогда его оставим в покое, но _чӧрібӧгісчік, иртібӧгісчік_ надо починить.

**Comment by tuffnatty** [comment]
чӧрібӧгісчік запрещено правилом 5

**Comment by veramal** [comment]
Тогда случай с чӧрібӧгісчік  сводится к #143 , а тут остается  разобраться с _пирбинібізерӌік_.

**Comment by tuffnatty** [comment]
деоптимизировал отладочный вывод, теперь в нем находятся любые случаи нарушения правил сочетаемости (некоторое время зависящие только от правых контекстов были соптимизированы так, что не доходили до отладки).
[Там](https://khakas.altaica.ru/suddenly-debug/?parse=%D0%BF%D0%B8%D1%80%D0%B1%D0%B8%D0%BD%D1%96%D0%B1%D1%96%D0%B7%D0%B5%D1%80%D3%8C%D1%96%D0%BA) можно искать слово FAILED и находить: `constraint-10.1 FAILED`

**Comment by veramal** [comment]
Ослабила 10.1, оставила только Neg.

**Comment by tuffnatty** [comment]
Внес в парсер, пирбинібізерӌік разбирается
