### ISSUE TITLE
ДАГ спрягается

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#173]
_Школаны тоос салза, син улуғ кізі пол **парғандағзың**._
После окончания школы ты как будто стал взрослым человеком. (С. Чарков. Ах Ӱÿс хазында  (повесть), 94.)

Сейчас не анализируется, т.к. причастям запрещено одновременно склоняться и спрягаться. Придется для ТАК сделать исключение, написала в 20 правиле.

**Comment by adybo** [comment]
Это же уже не причастие, а компаратив, а компаративу почему и не согласоваться.

**Comment by tuffnatty** [comment]
> ТАК

ТАГ? и в правиле опечатка

**Comment by tuffnatty** [comment]
Добавил, надо поправить в документе

**Comment by veramal** [comment]
Поправила опечатку, работает.
