### ISSUE TITLE
пасхаларынинаң сломалась

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#174]
Верный разбор должен быть такой:
hypothesis:  n пасха 2  ‛другой’  8018 
 affixes:    ----------⑪лар-⑫ы----⑯ни-⑰наң------
 affixes(MP):----------⑪ЛАр-⑫(з)Ы----⑯Ни-⑰нАң------
 affix names:----------⑪Pl₁-⑫3pos₁----⑯Gen.3pos-⑰Instr------

Причина в формулировке 16.5: "Poss2 не может следовать непосредственно за Pl1, Gen1, All1 **_и за Poss1_**". Т.к. Gen.3pos сидит в слоте Poss2, он не может соседствовать с 3pos₁. Дописала для него исключение.

**Comment by tuffnatty** [comment]
Починилось, добавил тест

**Comment by veramal** [comment]
работает
