### ISSUE TITLE
сиихтир - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#175]
Есть глагола сиихта - пищать. Однако при анализе его форм Fut и ConvA парсер ищет в словаре только переднерядную основу и ничего не находит.

**Comment by adybo** [comment]
ух ты. Он *sajIx-. Значит, надо, чтоб он долгий в 1 слоге разбирал как непервый.

**Comment by tuffnatty** [comment]
> ух ты. Он *sajIx-. Значит, надо, чтоб он долгий в 1 слоге разбирал как непервый.

Мне кажется, тут это не поможет, и вообще не очень понятно, что имелось в виду.
Проблема в том, что "последний характеризованный по ряду гласный" был в основе задний, а после стяжения пропал и пришлось смотреть в первый слог и получать передний. Если считать долгий _и_ в первом слоге передним, сломается _тииннер_, например. Вероятно, тут при восстановлении выпавшего А нужно рассматривать обе возможности, раз основа может быть дисгармоничной.

**Comment by veramal** [comment]
Имеется в виду, что долгое И в 1 слоге (в отличие от краткого) должна анализироваться как нейтральная по ряду - т.е. как И в непервом слоге. В этом случае и будут обе возможности.

**Comment by adybo** [comment]
Точно!

**Comment by tuffnatty** [comment]
Понял. Но это довольно суровое изменение - парсер исходит из пресуппозиции, что любое слово характеризовано по ряду, и придется во множестве мест добавлять третий случай. Гораздо проще в конкретном случае отмены стяжения _V+A_ > _и_ предположить оба варианта, а лишние будут затем отсечены по словарю или по несоответствию рядов с уже восстановленной основой. Сделал пока что так, сиихти/сиихтир начали разбираться, имеющиеся тесты не сломались. Может ли это выскочить в каком-то другом месте?

**Comment by veramal** [comment]
Да вроде не должно, не могу  придумать.
