### ISSUE TITLE
форма будущего А перед 2 лицом

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#176]
Когда в рамках борьбы с омонимией мы разрешили разбирать формы типа _полам_ 'я буду', но запретили - типа _полазың_ 'ты будешь'. Кажется, что сейчас это бессмысленно. Добавила в правило 9.3 возможность будущего А перед 2 лицом тоже.
Можно еще подумать об инфинитивах (_параға_), очень частотная вещь. В письменных текстах, правда, подчищается, поэтому у нас нет разбора.

**Comment by tuffnatty** [comment]
Добавил

**Comment by veramal** [comment]
Не добавилось, видимо, полазың не разбирается пока, отладчик пишет, что мешает 9.3.

**Comment by veramal** [comment]
Кстати, про будущее. Можно ли объединить 10.1 и 11 в одно правило? Сейчас вижу, что по сути они одинаковы, так что вопрос не про описание, а каково это с точки зрения парсера.

**Comment by tuffnatty** [comment]
странно, у меня сейчас разбирается. Может, это я забыл выкатить в ночи?
Склеить правила можно, конкретно в этом случае парсеру все равно.

**Comment by veramal** [comment]
Да, сейчас ок. Убрала 10.1, Ар приписала к 11 правилу.
