### ISSUE TITLE
поправка ограничения 21: PredPl + ЛЫГ

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#177]
Обнаружила, что сочетание ЛЫГ + PredPl не учитывалось и было тем самым негласно запрещено. Соответствующие примеры анализируются сейчас через ЛЫГ + Pl2, поэтому формальных проблем у них нет. Однако синтаксически этот запрет неверен, например:
_ӱгренӌілерге аймах-пасха тоғазығлар уғаа **тузалығлар**._
ученикам очень полезны разные встречи (с разными людьми). (Л.И. Чебодаева. Ӧбекелернiң чолларынӌа) 

Здесь _тузалығлар_ употреблено как скауземое, поэтому должно анализироваться через PredPl.
Внесла поправку.

**Comment by tuffnatty** [comment]
Обновил

**Comment by veramal** [comment]
Да, работает.
