### ISSUE TITLE
перенос ЛЫГ и Ли в позицию 13

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#178]
Примеры из Катанова показывают, что посессив может не только следовать за ЛЫГ, но и предшествовать ему:
_Олар хара чирдең халды **ӱзіліг** тасты сығарып_
Они взяли с черной земли камней толщиною по 3 четверти

А посессив после ЛЫГ, например, вот:
_Кізінің иң **аарлии** — ол аның палазы._ 
Главное сокровище человека — это его дети. (В.М. Торосов. Хакастарның посты улуғлир киктезі )

Поэтому переселяем его в позицию между именными СИ-показателями. Заодно захватываем Ли за компанию, т.к. держать ради него отдельную позицию нет смысла. Позиция между Tense|Mood и Pl1 стирается. 
Поправила ограничения 2 и 16.1, больше вроде нечего.

**Comment by adybo** [comment]
Да, так гораздо лучше! Конечно ли и лыг должны сидеть в одном месте (в какой-то древней версии таблицы так и было)

  
>Вторник, 1 декабря 2020, 15:02 +03:00 от veramal <notifications@github.com>:
> 
> 
>Примеры из Катанова показывают, что посессив может не только следовать за ЛЫГ, но и предшествовать ему:
>Олар хара чирдең халды  ӱзіліг тасты сығарып
>Они взяли с черной земли камней толщиною по 3 четверти
>А посессив после ЛЫГ, например, вот:
>Кізінің иң  аарлии — ол аның палазы.
>Главное сокровище человека — это его дети. (В.М. Торосов. Хакастарның посты улуғлир киктезі )
>Поэтому переселяем его в позицию между именными СИ-показателями. Заодно захватываем Ли за компанию, т.к. держать ради него отдельную позицию нет смысла. Позиция между Tense|Mood и Pl1 стирается.
>Поправила ограничения 2 и 16.1, больше вроде нечего.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Да вот только вчера) А вот с КЫ они действительно разошлись давно.

**Comment by tuffnatty** [comment]
Сделал

**Comment by veramal** [comment]
ӱзіліг стало разбираться.

**Comment by veramal** [comment]
Всё может оказаться несколько сложнее. Наткнулась у Чебочаковой на форму _ибipтiгдегiлер_ ‘те, кто находится в окружении’ (ибip-ЛЫГ-ДА-ГЫ-ЛАР). Однако _ибipтiг_ (а также _ибipлiг_) не анализируются, т.к. _ибip_ - глагольная основа. Но в принципе это указывает на то, что в один цикл можно и не вписаться.

**Comment by adybo** [comment]
Это может быть другой суффикс, отглагольного имени -иг от каузатива эбир-т- окружать. см. Эрдал WF 760-763, все случаи основ на р- без вокалической прокладки перед каузативным т. Собственно эбир-т- у Эрдаля нету (т.е. в древнетюркском не попался), но есть эгир-т- ‘to let or get (oneself) su rro u n d ed and encircled, to be en closed’. А, нет, вот есть эвирт-, но по контексту перевод непонятен, в частности может быть «переводить». А на -ыг нормальное отглагольное имя. Но не ацки продуктивное в хакасском.

**Comment by veramal** [comment]
Все же здесь нет однозначной четкости в порядке: сегодня попалось, что жители Чилан называются _Чыланныгдагылар_. Тут никаких сомнений в том, что ЛЫГ предшествует КЫ, нет. Стоит ли писать об этом в статье?
