### ISSUE TITLE
разные разборы одного композита

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#179]
Сейчас в корпусе _чир-суун_ (земля=вода.3pos-acc) разбирается как два слова, которые находятся только если задать поиск одной из частей без дефиса:
_Илбек Ада чаада **чир - суун** арачылап, чаадаң айланмаан._
Защищая родину на Великой Отечественной войне, он не вернулся.

А _чир-суғлары_ (земля=вода=pl-3pos-acc) - как композит (ищется с дефисом):
_**Чир-суғларынаң** астығып, пасха чирге харбанчалар._
Удалившись от своей земли, хватаются за чужую землю.

Пока записала в поля alternaten и form форму _чир-суу_ - однако хорошо бы _чир-суу_ обрабатывалась правилами парсера, как и _суғ_ - у нее эти поля пусты, однако форма _суу_ работает. Возможно, дело в отсчете слогов - можно ли сделать так, чтобы в композите отсчет слогов начинался после дефиса.

**Comment by tuffnatty** [comment]
Сделал отсчет слогов после дефиса, можно убрать из словаря

**Comment by veramal** [comment]
Работает, в словаре вроде не мешается, когда-нибудь в следующих версиях уберем.
