### ISSUE TITLE
ЛЫГ + датив

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#182]
**_Иргектіге** пастырба_! - Не будь предметом нареканий для имеющих ногти!
Не разбирается _иргектіге_ с выделением ЛЫГ и датива. Разбирается, если изменить форму на  _иргектігге_, но это неправильно. Морфонология должна действовать на ЛЫГ так же, как на основу: например, _кичiг-е_ 'брод-DAT'.

**Comment by tuffnatty** [comment]
В документе так:
> 2. Выпадение Г после Г, ң без стяжения.
При стечении последней согласной основы на ғ-, г-, ӊ- и любого аффикса с начальной фонемой -ғ, -г, первая согласная аффикса (то есть -ғ, -г) выпадает, согласная основы остается: суғ + -ға > суғ-а ‘воде’, эг + -гей > эгей ‘пусть гнет’, тоӊ + -ған > тоӊан ‘замерз’. На месте стыка аффиксов правило не действует!

**Comment by veramal** [comment]
В статье так:

При стечении двух согласных, первой г, ғ, ӊ, Г, и второй Г, вторая согласная выпадает, первая остается: суғ ‘вода’ + Га Dat > суға ‘воде’, эг ‘гнуть’ + Гей Opt > эгей ‘пусть гнет’, тоӊ ‘мерзнуть’ + Ган Past > тоӊан ‘мерз’, чохса=Г (дремать=Sact ‘дремота’) + Га Dat > чохсаға (чохсаға тӱс парған ‘погрузился в дремоту’). В шорском диалекте это правило обеспечивает реализацию формы 2pos.sg-Dat адыңа ‘твоей лошади’ (ат ‘лошадь’ + ың 2pos.sg + Га Dat).

Правда, там тоже нет ни одного примера с ЛЫГ. Поискала в корпусе - есть только примеры с одной г/ғ на стыке ЛЫГ и датива (у Катанова иначе, но у него и суға пишется с двумя ғ, суғға). Ну вот, скажем:
_Пос кізізіне **аарлыға** сатпаспыс._
Своему человеку дорого не будем продавать. (Н.Ф. Трошкин.)
_чир пӧзігі **арғалыға** чайылған мында чӧрглепчалар._
на вершине земли — на высоком хребте [кони], разбредясь, ходят. (Кӧрбе хораттығ Кӧре Сарығ )

**Comment by tuffnatty** [comment]
Увидел исправление в документе. Только там осталось "При стечении последней согласной **основы** ".

**Comment by tuffnatty** [comment]
Убрал ограничение на левую часть преобразования

**Comment by veramal** [comment]
исправила в описании
