### ISSUE TITLE
новые префиксы с дефисом

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#183]
Добавляла в последний словарь несколько вариантов редуплицирущей приставки, но что-то они не работают. Например, уп-. Анализатор успешно разбирает как Magn, однако примеры в корпусе остались непроанализированными: https://khakas.altaica.ru/corpus/?word1_distance=&word1_wordform=%D1%83%D0%BF-&word1_wordform_lookup=istartswith&word1_lexeme_auto=&word1_lexeme_auto_lookup=iexact&word1_semgloss_auto=&word1_semgloss_auto_lookup=iexact&translation_ru=&text=13&text=182&text=181&text=35&text=40&text=37&text=36&text=15&text=38&text=28&text=29&text=178&text=1&text=5&text=112&text=164&text=146&text=111&text=51&text=145&text=32&text=124&text=168&text=179&text=125&text=56&text=55&text=142&text=157&text=104&text=165&text=148&text=44&text=73&text=139&text=69&text=71&text=77&text=126&text=119&text=140&text=127&text=159&text=163&text=162&text=161&text=89&text=54&text=72&text=59&text=74&text=110&text=138&text=123&text=53&text=42&text=133&text=45&text=154&text=129&text=118&text=143&text=103&text=39&text=58&text=63&text=46&text=98&text=97&text=151&text=169&text=152&text=80&text=43&text=176&text=167&text=116&text=88&text=62&text=49&text=113&text=108&text=131&text=65&text=101&text=128&text=75&text=117&text=64&text=153&text=107&text=61&text=93&text=96&text=177&text=94&text=130&text=114&text=166&text=171&text=57&text=78&text=85&text=141&text=81&text=109&text=155&text=149&text=50&text=47&text=48&text=175&text=84&text=76&text=2&text=68&text=180&text=79&text=158&text=92&text=52&text=173&text=174&text=95&text=91&text=67&text=106&text=86&text=120&text=121&text=170&text=87&text=83&text=160&text=105&text=41&text=115&text=136&text=137&text=147&text=172&text=66&text=134&text=102&text=82&text=122&text=60&text=90&text=144&text=70&text=135&text=156&text=132&text=99&text=100&context_width=&page=1

**Comment by tuffnatty** [comment]
а, это потому что я в корпус словарь залил только после перетокенизации по старому словарю. Сейчас переделаю

**Comment by tuffnatty** [comment]
Исправились
