### ISSUE TITLE
Ptcl1 - отсечение лишних разборов

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#184]
ӧзӧгіс имеет, в частности, такой разбор:
v ӧзирге ‛свежевать’ ӧзе
---ОК-Ыс-----------------
---Ass₁-Perf0-----------------

Не было четко прописано, что Ptcl1 образуется только от NF-основы - исправила в п.5.

Есть еще и такой разбор:
v ӧзерге ‛расти’ ӧс
---ОК-Ыс-----------------
---Ass₁-Perf0-----------------

Форма Perf0 для императива неграмматична, она встречается только перед временем. Добавила условие в п. 5.1.

Неверный разбор (наряду с верным) получают также глаголы, образованные с помощью аффикса ЛА, в перфективных формах. Например, _имнебiскен_. Вот верный разбор:
v имнирге ‛лечить’ имне
----(Ы)бЫс----ГАн-------------
----Perf----Past------------

А вот неверный:
v имерге ‛сосать’ им
---LА-(Ы)бЫс----ГАн-------------
---Cont₁-Perf----Past-------------

В принципе LA сочетается с перфектом, но крайне редко, и во всех встреченных примерах используется форма ЫС (напр, _тыыплаысхан_).  Частица ОК тоже сочетается только с формой ЫС, а с частицей ТАА есть только один пример в перфективе (с формой ЫбЫС), и он сомнительный, т.к. сконструированный (из ГХЯ). Поэтому дописала в п.5, что при LA возможен только ЫС - а на остальные мы еще посмотрим.

**Comment by veramal** [comment]
Посмотрела на остальные: со всеми частицами в первой позиции возможен перфект Ыс, а перфект ЫбЫс встретился только в одном примере с Add ТАА. Отразила это в правиле 5.

**Comment by adybo** [comment]
Слушай, их вообще так мало, что отражать, что ыбыс встретился в 1 примере с таа в правиле, мне кажется, все-таки не следует. А там возьмет и еще с чем-то встретится.

**Comment by veramal** [comment]
Ну, это пример из грамматики, который появился раньше всех. Жалко его выпиливать, раз не мешает.

**Comment by tuffnatty** [comment]
> ӧзӧгіс имеет, в частности, такой разбор:
> v ӧзирге ‛свежевать’ ӧзе
> ---ОК-Ыс-----------------
> ---Ass₁-Perf0-----------------
> Не было четко прописано, что Ptcl1 образуется только от NF-основы - исправила в п.5.

Внес такое изменение. Сломались тесты с NF₀:
```
пар+0̸+даа+ча             пардаача
пар+0̸+ла+ча              парлача
пол+0̸+даа+чат            полдаачат
пол+0̸+даа+чат+са                 полдаачатса
```

> Есть еще и такой разбор:
> v ӧзерге ‛расти’ ӧс
> ---ОК-Ыс-----------------
> ---Ass₁-Perf0-----------------
> 
> Форма Perf0 для императива неграмматична, она встречается только перед временем. Добавила условие в п. 5.1.

Нельзя ли другой отрицательный пример для теста, этот уже исключен изменением в пр.5.
От изменения в п.5.1 сломались тесты с Affirm, Iter: _сығыбоғысчых, чіплеізеді_.

**Comment by veramal** [comment]
Добавила NF0 в правило 5. Добавила время, сидящее в других позициях, в 5.1.

**Comment by tuffnatty** [comment]
Кажется, в 5.1 надо поменять Dur.dial.kac на Dur₁.dial.kac и убрать слово "позиции", а так вроде заработало.

**Comment by veramal** [comment]
Ага, в документе пока не ловила.

пт, 30 апр. 2021 г. в 20:11, Phil Krylov ***@***.***>:

**Comment by veramal** [comment]
Эльвира подтвердила, что этот разбор неграмматичен:
v ӧзерге ‛расти’ ӧс
---ОК-Ыс-----------------
---Ass₁-Perf0-----------------

Поправила Dur.dial.kac на Dur1.kac. Здесь вроде всё.

**Comment by veramal** [comment]
Так и не нашлось примеров, для которых нужно было бы непременно сочетать ЫС с временами. А морфонологически верная императивная словоформа _ӧз-іб-ӧг-іс_ (S-NF-Ass1-Perf1) ничему не помешала бы. Завтра подумаю, совсем ли стереть 5.1 или что-то подправить, дальше нужно будет внедрить.

**Comment by adybo** [comment]
Про пример с LA. Наск. я понимаю, морфонема L, в отличие от Л, не ассимилируется с носовыми, а всегда будет с л, нет? Поэтом имне- с ней не должно путаться и так?

  
>Воскресенье, 7 ноября 2021, 23:38 +03:00 от veramal ***@***.***>:
> 
> 
>Reopened  #184 .
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Anna Dybo

**Comment by veramal** [comment]
L имеет варианты л и н, а глухого не имеет.

**Comment by veramal** [comment]
Зачеркнула пункт про время в 5.1.

**Comment by veramal** [comment]
тут все работает как надо
