### ISSUE TITLE
пазыбыстаң - неверный разбор (Loc+2pos.sg)

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#185]
Есть верный разбор через Abl, а есть такой:

n пас ‛голова’
----------(Ы)бЫс-ТА---(Ы)ң-------
----------1pos.pl₁-Loc₁---2pos.sg-------

В правиле 16.5 сказано: "Poss2, исключая Gen.3pos, не может следовать непосредственно за Pl1, Gen1, All1  и за Poss1". Тут не указан локатив из-за серии примеров типа _аның ибдезіне ӧрінген_ 'обрадовался тому, что он дома'. Но в 1-2 лицах такие формы не попадаются. Не стоит ли тут усилить ограничение, добавив что Poss2 не третьего лица не может также непосредственно следовать за Loc1?

**Comment by adybo** [comment]
Ты уверена, что невозможно мени ң ибдем(г)е  ӧрінгем «обрадовался тому, что я дома»? Почему бы ему быть невозможным?

**Comment by veramal** [comment]
Ну не то чтобы непредставимо, но так не говорят. надо ещё Эльвиру
поспрашивать

**Comment by adybo** [comment]
Может, просто пока ни разу не попалось. А с 3 лицом больше 1 раза попалось?

**Comment by veramal** [comment]
Да, штук 7 примеров, но сильно мешает харындас.

**Comment by adybo** [comment]
Э, а что у харындаса на конце он ловит?

**Comment by veramal** [comment]
Разбивает на харын-да-зы

**Comment by veramal** [comment]
Еще похожий случай с Pl1: очень мешает всем формам на данг и дангар.

улуғлардаң
n улуғ ‛большой’
---------ЛАр--ТА---(Ы)ң-------
---------Pl₁--Loc₁---2pos.sg-------

n улуғ ‛большой’
-------------ЛАр--ДАң------
-------------Pl₂--Abl₁------

Первый разбор неверен. улуғлардаңар - то же самое, только вместо 2pos.sg  - 2pos.pl.

**Comment by adybo** [comment]
Слушай, а как это после Pl2 может идти Abl1?

**Comment by veramal** [comment]
Это из-за разнобоя в разметке - в таблице так:

   - Abl нАң
   -  Abl₁ ДАң
   -  Abl₂ тЫн

Надо бы  нАң переназвать в Abl.dial, а за ДАң оставить название Abl.
Вообще ужасная путаница с тем, что у нас цифры используются и для
обозначения мест, и для обозначения вариантов. Фил, можно в слоте 15 с
падежами не использовать цифры вообще? Надо только придумать тогда, как
лучше назвать тЫн, если не Abl2.

**Comment by adybo** [comment]
Ablarch в смысле архаический.

**Comment by veramal** [comment]
Тогда с точкой: Abl.arch. А то непонятно.

**Comment by adybo** [comment]
Я думала не точкой , а нижним индексом

**Comment by veramal** [comment]
Лучше точкой - читать проще. Dial тоже через точку пишем.

**Comment by adybo** [comment]
а ну ладно

**Comment by tuffnatty** [comment]
Переименовал аблативы в парсере

**Comment by veramal** [comment]
Переименовала в документе. Надо еще в табличке поиска. Лучше заведу про это новую рекламацию.

**Comment by veramal** [comment]
Возвращаемся к основному вопросу. Нет, в принципе, никаких принципиальных невозможностей (кроме семантической) тому, чтобы _пазыбыстаң_  трактовалось как "то, что ты в нашей голове". Однако в имеющихся примерах субстантивированные локативы употребляются как дополнения, а не как подлежащие:
_Че **хайдазын** кем пілтір аның._  - Но **где она**, кто знает?
_Таистің сырайы кӱн чахайағы чіли чари тӱскен, ӧрін парған осхас **ууӌаның ибдезіне.**_ - лицо Таис зацвело как жарки – видно, обрадовалась **тому, что бабушка дома**.
_анаң, минзер кӧні кӧріп, чооғын пастирға **тимдезін** сизіндірген._ - потом, прямо смотря на меня, намекала **[на то], что готова** начать разговор.
_кізілер оларның **хайдазын** пілбезіннер тіп сағынған._ - Он не хотел, чтобы кто-то узнал **о том, где он**.

Хотя вот попался вроде с подлежащим пример, но странноватый (из Библии):
_Аның полызарға **тимдезі** хайдағ даа киректе кӧп хати сыналған._ - Его усердие (= его **нахождение в готовности** помогать) много раз было испытано во многом.

Не стоит ли запретить последовательность Loc1-Pos2 при отсутствии Case2 (т.е. в позиции подлежащего)? Хотя тоже довольно адхоковое решение.

**Comment by veramal** [comment]
А вот, похоже, принципиальная невозможность:
_мин дее, Сірер дее ізіктің пу сариндазыбыс._ - и я и вы — мы оба находимся по эту сторону дверей
сариндазыбыс имеет в т.ч. верный разбор: сари-нда-зыбыс сторона-Loc-1pl (мы (есть) - на стороне)
а также неверный: сари-нда-зы-быс сторона-Loc1-3pos-1pl (мы (есть) - его нахождение на стороне
Предлагаю запретить последовательность Loc1-Pos2 в одной словоформе с личными окончаниями.

**Comment by adybo** [comment]
Ну очень адхоковое, ведь смотри, как попался б-м сложный текст, так в нем и подлежащее выскочило!

  
>Среда, 10 ноября 2021, 18:07 +03:00 от veramal ***@***.***>:
> 
> 
>Возвращаемся к основному вопросу. Нет, в принципе, никаких принципиальных невозможностей (кроме семантической) тому, чтобы  пазыбыстаң трактовалось как "то, что ты в нашей голове". Однако в имеющихся примерах субстантивированные локативы употребляются как дополнения, а не как подлежащие:
>Че  хайдазын кем пілтір аның. - Но  где она , кто знает?
>Таистің сырайы кӱн чахайағы чіли чари тӱскен, ӧрін парған осхас  ууӌаның ибдезіне. - лицо Таис зацвело как жарки – видно, обрадовалась  тому, что бабушка дома .
>анаң, минзер кӧні кӧріп, чооғын пастирға  тимдезін сизіндірген. - потом, прямо смотря на меня, намекала  [на то], что готова начать разговор.
>кізілер оларның  хайдазын пілбезіннер тіп сағынған. - Он не хотел, чтобы кто-то узнал  о том, где он .
>Хотя вот попался вроде с подлежащим пример, но странноватый (из Библии):
>Аның полызарға  тимдезі хайдағ даа киректе кӧп хати сыналған. - Его усердие (= его  нахождение в готовности помогать) много раз было испытано во многом.
>Не стоит ли запретить последовательность Loc1-Pos2 при отсутствии Case2 (т.е. в позиции подлежащего)? Хотя тоже довольно адхоковое решение.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Anna Dybo

**Comment by adybo** [comment]
Что за -зыбыс? это диалектное вроде -зым?

  
>Среда, 10 ноября 2021, 18:12 +03:00 от veramal ***@***.***>:
> 
> 
>А вот, похоже, принципиальная невозможность:
>мин дее, Сірер дее ізіктің пу сариндазыбыс. - и я и вы — мы оба находимся по эту сторону дверей
>сариндазыбыс имеет в т.ч. верный разбор: сари-нда-зыбыс сторона-Loc-1pl (мы (есть) - на стороне)
>а также неверный: сари-нда-зы-быс сторона-Loc1-3pos-1pl (мы (есть) - его нахождение на стороне
>Предлагаю запретить последовательность Loc1-Pos2 в одной словоформе с личными окончаниями.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Anna Dybo

**Comment by adybo** [comment]
Небось это -зы и есть 3Pos в фнкции субстантиватора?

  
>Среда, 10 ноября 2021, 18:12 +03:00 от veramal ***@***.***>:
> 
> 
>А вот, похоже, принципиальная невозможность:
>мин дее, Сірер дее ізіктің пу сариндазыбыс. - и я и вы — мы оба находимся по эту сторону дверей
>сариндазыбыс имеет в т.ч. верный разбор: сари-нда-зыбыс сторона-Loc-1pl (мы (есть) - на стороне)
>а также неверный: сари-нда-зы-быс сторона-Loc1-3pos-1pl (мы (есть) - его нахождение на стороне
>Предлагаю запретить последовательность Loc1-Pos2 в одной словоформе с личными окончаниями.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Anna Dybo

**Comment by veramal** [comment]
См. таблицу. Здесь мы, а не я, если кто не заметил.

**Comment by adybo** [comment]
Так я и говорю, диалектное зыбыс оттуда же, откуда зым. При именном сказуемом. Бывает такое? А зым бывает при именном сказуемом?

  
>Среда, 10 ноября 2021, 18:41 +03:00 от veramal ***@***.***>:
> 
> 
>См. таблицу. Здесь мы, а не я, если кто не заметил.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Anna Dybo

**Comment by adybo** [comment]
В корпусе все примеры на сочетание какого-нибудь падежа с диалектным зым или зыбыс, кромевот этой твоей стороны,  — это разборы харындазым или харындазыбыс (мой/наш) брат. Я всегда думала, что это окончание не живет с именным сказуемым (при именном в этих диалектах, по-моему, все же пын). Нет?

  
>Среда, 10 ноября 2021, 18:41 +03:00 от veramal ***@***.***>:
> 
> 
>См. таблицу. Здесь мы, а не я, если кто не заметил.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Anna Dybo

**Comment by veramal** [comment]
В Казановке зым, бына вообще нет

ср, 10 нояб. 2021 г., 19:56 adybo ***@***.***>:
