### ISSUE TITLE
предложение убрать Gen1

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#186]
Фактически Gen1 встречается в лексемах _пістіңнер_ ‘наши’ и _сірерніңнер_ ‘ваши’, во всех остальных случаях только создает ненужную омонимию в разборах. Эти лексемы можно ввести в словарь.

**Comment by adybo** [comment]
Вероятно, также что-нибудь типа миніңнер (мои еще не приходили?)  Петр іңнер (А Петровы родичи все ленивые), и под.? В других языках так.
Это все уже про связь частотности словоформы с семантикой слова все-таки. Притяжательные местоимения можно ввести в словарь, а имена собственные и термины родства (сватьины)  все-таки скорее нельзя.

**Comment by veramal** [comment]
Ассоциативная множественность на именах тут иначе выражается: либо pl
(Петялар), либо через местоимение (Петя ноо). А через генитив только у этих
местоимений. Если окажется, что бывает и с генитивом, можно ведь снова его
ввести.

**Comment by veramal** [comment]
Эльвира считает, что кроме пістіңнер примеров с внутренним генитивом нет.

**Comment by adybo** [comment]
Уж наверное, и для 2 го и для 3 лиц? Это же просто притяжательные местоимения.

**Comment by veramal** [comment]
Грамматика дает сконструированный пример на 2pl:
_Сірерніңнер ам даа килбеен ме?_ - Ваши еще не приехали?
Эльвира считает, что это звучит искуственно, но мы оставим. В 3 лице, думаю, мешает уже имеющийся _ЛАр_ (встроенный в _олар_). Но если встретится, можем добавить в словарь.
Просто притяжательные местоимения выражаются формой Gen.3pos: _оларни_, _пiсти_ и пр.

**Comment by tuffnatty** [comment]
Закомментировал в парсере Gen₁ и тест на _пістіңнер_, нужно добавить его в словарь

**Comment by tuffnatty** [comment]
Еще вычистить Gen₁ из правил 16.3, 16.7

**Comment by veramal** [comment]
В словарь добавила, в таблице и правилах зачеркнула (пока стирать не стала).

**Comment by tuffnatty** [comment]
@veramal Можно закрыть?

**Comment by veramal** [comment]
Да

вт, 24 мая 2022 г. в 16:42, Phil Krylov ***@***.***>:
