### ISSUE TITLE
двойной падеж: Loc1 + All

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#187]
_Сірер дее сағам сағыссырастазар._ - Так и вы теперь имеете печаль (букв. в печали).

_сағыссырастазар_ имеет неверный разбор (верный тоже имеет):
сағыссырас-ТА-САр
забота-Loc₁-All

Хотим ли мы с этим бороться?

**Comment by adybo** [comment]
О! а как с этим бороться, запретить двойные падежи?

**Comment by veramal** [comment]
Явно не все, т.к. all-abl2 нужно оставить.

**Comment by veramal** [comment]
Просмотрела примеры, где парсер выделяет два падежа подряд. Кроме all-abl2 (зартын) есть такие случаи:
- лексикализовавшиеся Loc + Dat
_Пӱӱнгį тоҕысты **таңдā** kалдырба._ - Сегодняшней работы не оставляй до завтра.
таңдаа < таңда 'завтра' + ГА Dat < таң 'заря' + Loc + Dat

_ырахтаа парбин_ ‘далеко не уходя’ 
ырахтаа < ырахта 'вдалеке' (есть в словаре!) + ГА Dat < ырах 'далекий' + Loc + Dat

- лексикализовавшиеся  Loc + Loc, в основном в местоимениях _пу_ и _ол_ (_мындада, андада_ 'тогда') - но у них есть и другие пары, которых нет больше нигде (напр., анчага (ол+Prol+Dat)). Есть один пример из Библии, где вроде как два падежа, но я бы не стала ему сильно доверять:

_Сағам Мин пу чир **ӱстӱндеде** чирнің Чарии Мин полчам._ - Доколе Я в мире, Я свет миру.

По-моему, это попытка осмыслить _чир ӱстӱнде_ как вершину зависимой предикации ('Доколе я в мире') и навесить на нее Loc как показатель обстоятельственного предложения с временным значением. Т.е. это как _аның ибдезіне ӧрінген_ 'обрадовался тому, что он дома' (см. #185), только без зы, потому что не ядерный падеж. Но мне что-то сомнительно такое словотворчество. Спрошу Эльвиру.

В общем, оставила бы я только зартын, а всё остальное убила бы.

**Comment by adybo** [comment]
Может, ты и права. Непременно там посреди должен быть какой-то  демотиватор изменятель синтаксической роли, кажется, и нулевой по идее не смотрится.

**Comment by veramal** [comment]
Да нет, с  точки зрения "доказательной медицины" все логично. Ведь причастия могут быть в локативных падежах без всяких субстантиваторов, в 3 лице особенно: _ол парганда, мин килгем_ 'когда он ушел, я пришел'. А в случае помещения _мин пу чир ӱстӱнде_ "я - (нахожусь) на этой земле" в роль сирконстанта происходит коллапс выражения лица. Т.к. в финитном употреблении возможен только вариант _ӱстӱндебiн (ӱстӱндезiм)_, но в нефинитном он не подходит - надо бы _ӱстӱндем_ (по аналогии с _мин парганымда, ол килген_ 'когда я ушел, он пришел'). Форме _ӱстӱндемде_ я бы больше поверила. Но, видимо, так не летит.

**Comment by adybo** [comment]
Это потому что  тюркское настоящее «причастие» вообще издревле полифункционально, оно и имя действия (!), оно и причастие в смысле атрибут.
а эта вот штука с  ӱстӱнде, по-моему, должна бы быть, если уж как с причастием, ӱстӱндемде, действительно.

**Comment by veramal** [comment]
Безусловно. И имя деятеля зачастую выражено тем же причастием.

**Comment by adybo** [comment]
Ну имя деятеля-то это вероятно подъем.

**Comment by veramal** [comment]
Резюме: т.к. библейский пример нас не очень убеждает, а все прочие случаи лексикализованы, оставляем в непосредственном соседстве только два падежа: All1 + Abl.arch (_-зартын_). Дописала в правило 16.5. Т.к. в нем 2 части, каждая из которых сильно разрослась, отделила часть про Poss2 в п. 16.7 (т.к. 16.6 уже занят).

**Comment by veramal** [comment]
Эльвира подтвердила грамматичность библейского примера, так что сочетание Loc1 + Loc2 я дописала в правило 16.5 как допустимое.

**Comment by tuffnatty** [comment]
Внес в парсер
