### ISSUE TITLE
отсечь омонимию Foc и Indir

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#188]
Правило 23 сейчас выглядит так: 23. "Пок-тель Foc может встретиться: а) в словоформах с пометой Nomen; б) в глаголах, у которых есть временные показатели Past ГА(н), Fut А(р) и Hab ЧА(ӊ). "
Есть предложение добавить в конец "и отсутствует отрицание Neg ПА". Иначе формы типа _сынмаандыр_ 'не умещалась, оказывается' получают каждый раз два разбора - Neg.NF ПААн + Indir ТЫр и Neg ПА + Past ГАн + Foc ТЫр. При этом не встретилось контекстов, в которых реализовалось бы второе значение (с первым значением в корпусе сейчас 23 примера, в устной речи также употребляется).

**Comment by adybo** [comment]
Да, можно, но давайте про это запишем и покрасим.

**Comment by veramal** [comment]
Записала.

**Comment by tuffnatty** [comment]
А мне кажется, если добавить Foc в правило 11 (список аффиксов, несовместимых с Neg), будет то же самое, но компактнее, и получится зависимость от правого контекста, а не от левого, а такая ситуация парсеру больше нравится (можно раньше соптимизировать лишние гипотезы).

**Comment by adybo** [comment]
>Вторник, 16 февраля 2021, 16:00 +03:00 от Phil Krylov <notifications@github.com>:
>А мне кажется, если добавить Foc в правило 11 (список аффиксов, несовместимых с Neg), будет то же самое, но компактнее, и получится зависимость от правого контекста, а не от левого, а такая ситуация парсеру больше нравится (можно раньше соптимизировать лишние гипотезы).

Да!

**Comment by tuffnatty** [comment]
Внес это изменение в документ.

**Comment by tuffnatty** [comment]
И в парсер
