### ISSUE TITLE
переименовать Iter в Ipf или Dur3

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#189]
По совокупности примеров кажется, что показатель АдЫ(р) довольно редко выражает итератив, т.е. повторяющееся действие, и считать это базовым значением показателя неправильно. Скорее в нем есть значение длительности, непрерывности, постоянства. Ср:
_Чахсы кізее прай кізі **хынадыр**._ - Хорошего человека все любят. (В.Г. Шулбаева. Сыын мӱӱзі)
_школа позының ӱгренӌілерінең **сабланадыр**_ - школа славится своими учителями (Н.Ф. Трошкин.)
_Хатығ наахтығ ир чахсы Ырлап, кӧглеп **килчадыр**_ - напевая, с песней ехал С крепкими скулами* достойнейший из мужей. (Ай-Хуучин, Строки 114-115). 

Есть, впрочем, и итеративно-хабитуальные контексты:
_Арығлан, сілігленіп, Хан Мирген Алтын стол кистіне **одырыбызадыр**._ - Умывшись, прихорошившись, Хан-Мирген Обычно за золотой стол садится (Ай Хууӌын, Строки 56-57)
_— Пӱӱр хайди **улидыр**?_ - — Как волк воет? (Сказки)
_Хайзыбысты **чиидір**, хайзыбысты **палығлидыр**, хайзыбысты ӧдіре тут **парыбызадыр**._ - Кого-то из нас съедают, кого-то ранят, кого-то до смерти задавливают. (несказ.проза)

Бывает и просто настоящее время:
_— Полдырзар, ноға полбасха, — тіп **тапсидыр** олах._ - — Если возьмёте, почему не быть, — так говорит мальчик. (сказки)

Так что общее значение - имперфектив, отсутствие идеи достижения предела. Возможно, стоило бы имперфективом назвать скорее чАт, а адыр - дуративом. Но если мы переименуем их так сейчас, то запутаемся, мне кажется. И еще есть некоторое неудобство в том, что Ыбыс прекрасно себя чувствует вместе и с чАт, и с Адыр в одной словоформе, а последовательность Perf-Ipf вроде как противоречит здравому смыслу. 
Или можно считать, что Адыр - это тоже дуратив (третий). В общем-то в этом есть некоторая правда и диалектное распределение, т.к. примеры ЫбЫс + Адыр встречаются у Катанова (а там во всех текстах много черт, которые сейчас мы наблюдаем только на севере) и у кызыльцев, а ЫбЫс + чАт - у сагайцев и в Библии (которую тоже сагайцы переводили). Два дуратива в одной словоформе мы уже видели (у сагайцев: Dur1 ит + Dur чат), поэтому формы с -чададыр тоже не сильно рушат картину (хотя встречаются гораздо чаще). Да и настоящим временем первый дуратив тоже бывает чаще, чем собственно видом. Интересно, что у кызыльцев и другие последовательности дуративов встречаются:
Ат + Адыр:
_Адар таң ат параатса, Алып кізі **турададыр**,_ - Когда заря занималась, Богатырь вставал, (Алтын Арығ, Строки 8543-8544)
Адыр + Адыр:
_Хайда-хайда харачхай хус Харахтаң чіт **парадырадыр**._ - Далеко-далеко птица ласточка — Из глаз исчезает. (Ай Хууӌын, Строки 6447-6448) 
Но что они хотели этим сказать, я не понимаю.

**Comment by adybo** [comment]
Имперфектив, сочетающийся с перфективом, это странно
На мой вкус, это не дуратив (ну и не итератив), а обычное действие, как там оно будет по латыни.
Хабитуалис или узитатив
 
узитатив — Разновидность хабитуалиса со значением иметь обыкновение постоянно совершать названное глаголом действие

**Comment by veramal** [comment]
Хочется  его, конечно, обозвать Present simple, на узитатив не тянет по
описанию. А хабитуалис тоже уже есть, с уклоном в прошлое.

**Comment by veramal** [comment]
Поступило предложение переименовать в Gener (generic). Есть альтернативное предложение назвать это Hab.pres, а старый хабитуалис на чанг -  Hab.past, но это не всегда будет отражать реальность (чанг  в виде причастия тоже любит быть в зоне настоящего).

**Comment by adybo** [comment]
Да, вот именно! Давайте генер

**Comment by veramal** [comment]
Переименовала в описании, осталось переименовать в парсере и табличке поиска.

**Comment by tuffnatty** [comment]
Переименовал в парсере
