### ISSUE TITLE
неверный разбор Pl1-Pl2

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#191]
В словоформе может быть только 1 ЛАр, меж тем для словоформы истерлер получаем вот что:

v истерге ‛слышать’ ис ист
--------Ар-----ЛАр--------
--------Fut-----Pl₂--------
n ис 1 ‛имущество’
---------ЛАр----ЛАр--------
---------Pl₁----Pl₂--------
n ис 2 ‛материя’
---------ЛАр----ЛАр--------
---------Pl₁----Pl₂--------
(и еще 5 значений ис)

Первый разбор верный, остальные нет.
В Библии, впрочем, попались такие примеры:
_Фригий, Памфилий, Египет **чирлеріндегілербіс**_ - мы - жители (земель) Фригии, Памфилии и Египта (_чир-лер-і-нде-гі-лер-біс_ земля-Pl1-3pos1-Loc1-Attr-Pl-1pl)
Сірернің, ідӧк Лаодик паза Иерополь **саарлардағыларның** ӱчӱн - (забота) о вас и о находящихся в Лаодикии и Иераполе (_саар-лар-да-ғы-лар-ның_ сторона-Pl1-Loc1-Attr-Pl-Gen)

Есть сомнения, что все носители согласятся с этим. Но нужно поставить ограничение хотя бы на непосредственное соседство Pl1 и Pl2. Написала новое ограничение 16.7.

**Comment by adybo** [comment]
Да, непосредственного точно не может быть, хотя бы потому, что помыслить теоретически эти два в прямом падеже я могу только предположив, что второй — предикативный, а первый — множественная 3 л принадлежность, и тогда их будет разделять -и-, потому что эта принадлежность все-таки лары.

**Comment by veramal** [comment]
Ограничение сдвинула в п. 16.8.
Т.к. тут еще речь об именовании падежей, заметила неточности: в посессивном склонении Gen и Acc должны начинаться с маленькой _н_, а не с большой. В описании поправила, теперь надо поправить в парсере и в табличке поиска вместе с прочими падежами. У аккузатива сейчас вооще что-то странное в табличке: Acc НЫ, Acc1 НЫ, Acc2 Н, Acc.dial ТЫ, Acc.dial1 ТЫ, Acc.dial Т. Должны остаться 3 формы: Асс НЫ, Acc.dial ДЫ и Acc.poss Н. У посессивного аккузатива нет диалектной формы (к счастью, парсер Acc.dial Т вроде не выделяет).

**Comment by tuffnatty** [comment]
> Т.к. тут еще речь об именовании падежей, заметила неточности: в посессивном склонении Gen и Acc должны начинаться с маленькой _н_, а не с большой. В описании поправила, теперь надо поправить в парсере и в табличке поиска вместе с прочими падежами. У аккузатива сейчас вооще что-то странное в табличке: Acc НЫ, Acc1 НЫ, Acc2 Н, Acc.dial ТЫ, Acc.dial1 ТЫ, Acc.dial Т. Должны остаться 3 формы: Асс НЫ, Acc.dial ДЫ и Acc.poss Н.

> У посессивного аккузатива нет диалектной формы (к счастью, парсер Acc.dial Т вроде не выделяет).

Если так сделать, ломается #128, где мы ее добавляли. Кстати, в той же переписке про Т/Д вроде договорились, что Т(Ы), а не Д(Ы) - опять в табличке и здесь вижу Д, а как так получилось - не помню.

**Comment by tuffnatty** [comment]
Кстати, в Case1 тоже Gen.poss должен быть с маленькой?

**Comment by veramal** [comment]
Gen.Poss - 2 заглавных, т.к. это склейка Gen и Poss.
Никтеримди - д.б. Acc.dial дЫ (со строчной) в посессивном склонении, форма
без Ы тут непредставима. Значит, 4 формы аккузатива всего.

**Comment by tuffnatty** [comment]
> Gen.Poss - 2 заглавных, т.к. это склейка Gen и Poss.

Я спрашивал не про написание тега, а про его содержимое. В Case1 должен различаться посессивный и простой Gen?

> Никтеримди - д.б. Acc.dial дЫ (со строчной) в посессивном склонении, форма без Ы тут непредставима. Значит, 4 формы аккузатива всего.

Так работает, а можно сначала в документ внести соответствующее исправление?

**Comment by veramal** [comment]
В Case1 генитива вообще не должно быть - он встречается только с одним местоимением. А склейка с 3pos живет в слоте Poss2 (15). Поставила в документе пока Gen1 в скобки на случай, если захотим вернуть. В таблице он в двух вариантах уже был.
Добавила диалектный посессивный Acc _дЫ_.

**Comment by tuffnatty** [comment]
Привел парсер в соответствие с документом
