### ISSUE TITLE
ноты

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#192]
Любопытно, что в нашем словаре есть лексема для нот "си", "соль" и "фа", но нет для остальных. Убить их?

**Comment by adybo** [comment]
А сильно мешает?

**Comment by veramal** [comment]
Ну си мешает в косвенных формах от син. Надо либо ми заводить в пару, либо убить.

**Comment by adybo** [comment]
Эх. Вдруг композиторы хакасские чего напишут

**Comment by veramal** [comment]
Си убила, проявится при обновлении словаря.
