### ISSUE TITLE
неверные разборы с Ptcl2

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#193]
чоғылох
n чох 2 ‛отсутствующий’
--------------(з)Ы--LА----ОК-
--------------3pos--Cont₂----Ass₃

хараладыр
n хара ‛чёрный’
----------------LА----ТЫр-
----------------Cont₂----Foc-

Надо запретить Ptcl2 быть непосредственно рядом с Ptcl3 и фокусом, минуя лично-числовые показатели. Написала про это новое ограничение 34.

**Comment by veramal** [comment]
Оп, а вот опять в Библии насочиняли:
_Аннаңар кізіні пос итчеткен чахығнаң **амоғох** чарғыладар кізі чіли чоохтанчат паза хылынчат._
Так говорите и так поступайте, как имеющие быть судимы по закону свободы.

Интересно, что слова _амох_ в словаре нет, хотя оно весьма частотно. Т.е. при реализации нового ограничения это разбираться не будет. Но не жалко.

Есть другая сложность: по идее логичнее было бы сформулировать, что за Ptcl2 всегда следуют показатели лица и числа, а не то, что после Ptcl2 нельзя сразу Ptcl3 или фокус. Этом мешает один пример из грамматики (судя по всему, искусственный):
_Хайди ол кізі андағ чирде хорыхпаӌаң **полдыни**?_ - Как тот человек в таком месте не боялся (обычно)? 

Предлагаю считать его опечаткой, т.к. все остальные авторы пишут _ни_ отдельно: 
_Мының алнында минің хараам хайда ла **полды ни**_ - До этого где же были мои глаза (Н.Ф. Трошкин)

**Comment by veramal** [comment]
В общем, исправила 34 и 27, чтобы этот единственный пример не считался правильным.

**Comment by adybo** [comment]
Да!

**Comment by tuffnatty** [comment]
Если так сделать, ломаются тесты с Affirm: _полтырохчых_, _сығыбоғысчых_

**Comment by veramal** [comment]
_сығыбоғысчых_ ломается отдельно - там не Part2, а Part1
_полтырохчых_ - это #129 . Переформулировала 34 правило, чтобы он тоже разбирался

**Comment by tuffnatty** [comment]
Добавил в парсер
