### ISSUE TITLE
проект переименования NF обратно в Conv

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#195]
Нашли примеры, говорящие о том, что после ЫбЫс и чАт тоже возможно интерконсонантное опущение Ып. На Ыбыс немало в корпусе по запросу, а на чАт там одни императивы. Но вот в устном нашелся один пример:
speaker_name: Таисия Суровна Кулемеева
place of residence at the time of recording: Казановка (Аскизский р-н)
_Анаң ибге   килгенде   чатханнаң   **ойнапчат**  салӌаң._ - Потом домой пришел,  стал играть на    чатхане тот мотив.

Основной вопрос в том, как бы этот ноль красиво назвать. Если делать топорно, то NF будет Convп1, а Nf0 будет Conv1п0.

**Comment by adybo** [comment]
Да просто для ып-деепричастия такое же правило, как для внутреннего

**Comment by veramal** [comment]
Ну не совсем такое же, т.к. после первого ып может быть много чего, а после второго - только ОК. Но красивое название тоже нужно.

**Comment by adybo** [comment]
Разве ал- не может быть после второго ып?

**Comment by veramal** [comment]
ал не бывает внутри словоформы по правилам орфографии

**Comment by adybo** [comment]
Зачем внутри? Это же был снаружи?

**Comment by veramal** [comment]
ойнапчадып ал, а не ойнапчадыбал

**Comment by adybo** [comment]
Так у тебя в примере тоже было перед пробелом и салчанг.

**Comment by veramal** [comment]
Да. Я и пишу, что после второго Conv возможен только ОК, кроме пробела.

**Comment by adybo** [comment]
А, ну да, конечно. Но правило-то от этого не меняется (ок соответствует условию).

**Comment by veramal** [comment]
Примеры на _ЫбЫс_ перед NF, бывает только перед вспомогательным_тур_, сейчас в корпусе всего 12 примеров:
_Чоохтаныбыс турарға кирегӧк… -_ Иногда выговариваться надо. (И. Топоев, Хайхастығ чатхан)
_пірее чирде хыйын парыбыс турар_ - где-то перекосится (В.Г. Шулбаева Сыын мӱӱзі)
_Прай соолабыс турғандағ_ - Как будто вся загудела (Ай-Хуучин, Строки 4492-4493)
_киме салғахтарзар кір парыбыс турған_ - лодка покрывалась волнами (Наа молӌағ, Мф 8:24)
_Ол, полған на ағырығ кізізер холларын салып, имнебіс турған._ - Он, возлагая на каждого из них руки, исцелял их. (Лк 4:40)
_Постарыңда ниме пар, аны чох кізілерге пирібіс турзаңар_ - То, что у вас есть, давайте тем, у кого этого нет (Лк 11:41)

Интересно, что формы на -_ыбызып_ перед глаголом _тур_ встретились только в 3 случаях. В двух из них тур употреблен в лексическом значении и аналитической конструкции не усматривается:
_Тудына кірген кӱӌӱктерін Тастағлабызып, турыбысхан:_ - Щенят, которых с собой принесла, Подкинула [роженице] и встала: (Ай Хууӌын)
_Ол, хазыр чоохтаныбызып, турып, пастыра халған._ - Она возмутилась, встала и пошла прочь. (Алисаның Хайхастар Чирінзер чорығы)

Третий пример несколько сомнителен:
_Хысхырып, хихлап, Чилбіген сӱрісип (?сӱрібiзiп) турадыр._ - Клича-крича, Челбэген следам за ним погналась. (Алтын-Табатай)

**Comment by veramal** [comment]
С другой стороны, формы на на -_ыбызып_ перед глаголами _ал_ и _одыр_ не встречаются (на последнее есть пример только с неаналитической конструкцией: _Анаң Ол, пічікті чабызып, храмдағы нымысчаа аны пирібізіп, одыр салған._ - И, закрыв книгу и отдав служителю, сел (Лк 4:20)

С другими вспомогательными глаголами на согласные есть отдельные примеры аналитических конструкций, в составе которых есть ЫбЫс + NF0, в диалектных записях.
сал:
_Мині сӱрізіп, ырабыссаларох  (ырабыс саларох)_ - Когда, за мною гонясь, далеко уйдут (Пӱдӱрчӱннең тӱлгӱ, сказки)
пар:
_хайдыг-да кизинең умус тӱкченде, тастабыс парбысхан_ - в мусорную яму какого-то человека бросив — ушёл. (Ӱс харындас аңнап парханаңары)
 _тіп, Алтын кӧлде тастабс парбсхан._ - сказав, он его в Алтынкуль бросил. (Кӱтен Пулухнаң Ах Кӱмӱк)
кил:
_базарга садыбыс килдім_ - на базаре продав, приехал. (Тӧргінчі) - не слишком аналитическая, при этом нет Ып, но все же не перед именем
хал, пир, сых, чат, чӧр - нет примеров

В аналогичных примерах на -ыбызып аналитические конструкции не усматриваются, за исключением разве что этого примера:
Строки 6934-6935
_Син тудызар айна - чабалы Алнымда хаабызып чӧр чи анаң._ - Тебе бы со злейшим из демонов схватиться – Вот [он] борется со мной. (Алтын Арығ, Строки 6934-6935)

**Comment by veramal** [comment]
Итог: после ыбыс у нуля и Ып разные функции. В значении NF используется только нулевой алломорф, а Ып встречается только перед запятой используется только в деепричастном значении. Примером с отрицательным деепричастием Бин после Ыбыс и Чат не встретилось. Вторую позицию для NF вводить не будем, т.к. в ней может находиться только пустой алломорф.

**Comment by adybo** [comment]
ок

  
>Вторник, 1 июня 2021, 16:17 +03:00 от veramal ***@***.***>:
> 
> 
>Итог: после ыбыс у нуля и Ып разные функции. В значении NF используется только нулевой алломорф, а Ып встречается только перед запятой используется только в деепричастном значении. Примером с отрицательным деепричастием Бин после Ыбыс и Чат не встретилось. Вторую позицию для NF вводить не будем, т.к. в ней может находиться только пустой алломорф.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Можно пока убрать, думаю.
