### ISSUE TITLE
дистрибутив КлА неверная морфология

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#196]
Сейчас, например, _тiле_ имеет такой разбор:
v тирге ‛сказать’ ті
лА---------------------
Distr---------------------

Однако его быть не должно, т.к. после гласной возможен только вариант КлА.

**Comment by adybo** [comment]
Значит, неправильно написано правило распределения алломорфов

**Comment by tuffnatty** [comment]
Такого правила в документе нет.

**Comment by veramal** [comment]
Это общее правило: " Согласный в скобках, стоящий в начале морфа, проясняется, если предыдущий морф кончается на гласный, и опускается, если предыдущий морф кончается на согласный." Но в нем действительно было указание только про _н_ - стерла.

**Comment by tuffnatty** [comment]
Сделал так. А не надо ли в документе в табличке "Правила выбора глагольных аффиксов дистрибутива. Морфонемные", ниже, поменять _хла_/_кле_ на _ла_/_ле_ тогда?

**Comment by veramal** [comment]
Нет, все же немного не так. К и н ведут себя по-разному. н всегда опускается после согласной, а К опционально. Но оба проясняются после гласных. Можно добавить в тест _ӧлглееннер / ӧллееннер_ 'поумирали', __тарағлааннар__ 'разошлись'. В документе исправила. Таблицы мы давно уже не редактируем, вроде как они устарели.

**Comment by veramal** [comment]
Вот еще тут скорее в копилку: качинским глаголам с основой на -ч не так-то просто присоединить КлА. Опущение К после согласных вроде бы сагайская черта, а кластеры _чхл, чкл_ не очень удобны в произношение. Попалось у Катанова такое:
_Ағаа арағамаң **чачығлапча**, атсары алдыра._ - Коня, посвящаемого ему, кропят водкой.
Вообще он пишет _гыла_ без выпадения _Ы_, но здесь можно видеть метатезу _ыгла_ после основы _чач_ 'кропить'.

**Comment by adybo** [comment]
Ага

**Comment by veramal** [comment]
Просьба исправить морфонологию в соответствии с документом! Сейчас парғла, например, не разбирается.
"Согласный н в скобках, стоящий в начале морфа, проясняется, если предыдущий морф кончается на гласный, и опускается, если предыдущий морф кончается на согласный. Согласный К в скобках проясняется, если предыдущий морф кончается на гласный. Согласный н в скобках, стоящий в конце морфа, опускается при сочетании с некоторыми другими морфами – это описано в разделе II «Ограничения на сочетаемость аффиксов»"

**Comment by veramal** [comment]
Вот это место дает большое количество неразобранных словоформ. _тiле_ сейчас через Distr не разбирается, но и _парғла_ не разбирается, хотя должно.

**Comment by tuffnatty** [comment]
а как же в парғла проясняется (К), если перед ним согласный?

**Comment by tuffnatty** [comment]
или, если опущение (К) после согласного опционально, то где про это в документе?

**Comment by veramal** [comment]
После гласного проясняется, как и написано. Про после согласного ничего не
написано, т.к. возможны оба варианта. Могу дополнить описание, раз из
текущего не ясно.

**Comment by veramal** [comment]
дописала

**Comment by tuffnatty** [comment]
Спасибо! Переделал, сейчас перепарщу. Но
1) морфонема с опциональным выпадением получается больно хитрая, поэтому [в парсере] разделил Distr на два варианта, из которых тот, что с выпадением, запрещен после гласной;
2) второй вариант, выходит, не КлА, а ГлА, т.к. озвончается после гласной: тохтағлабоғысханнар ?

**Comment by veramal** [comment]
Нет, К озвончается в интервокале, как и все глухие (Т, П, С). А Г в
интервокале выпадает.

**Comment by tuffnatty** [comment]
А где написано, что ғ в тохтағлабоғысханнар находится в интервокальной позиции? В документе есть зачеркнутое:
> Морфонемы П, Т, С, К, Ч реализуются через фонемы звонких согласных в том случае, когда справа и слева от них находится гласная.

**Comment by veramal** [comment]
А, ну да, это не интервокал. Да, тогда выходит ГлА, хотя помнится, с ней тоже были какие-то проблемы. Сейчас  поищу.

**Comment by veramal** [comment]
См. по теме #130 , #159.
Из первой рекламации следует, что тут, видимо, все же Г, а не К, т.к. после основ на Г нет двойной согласной (_сигле_-, а не _сигле_-). Ср.: _Хоостар **сиглирі** ир кізінің тоғызы нимес._ 'Узоры рисовать — не мужское дело.' (сиг-лир-i чертить-Distr+Fut-3pos). Правда, если разделить на лА и ГлА, будет два омонимичных разбора в каждом таком случае.
Во второй рекламации, впрочем, предлагается морфонема G из-за внутренней архитектуры. Но тут, видимо, неактуально.

**Comment by adybo** [comment]
К тоже озвончается. Г отличается тем, что обязательно выпадает между гласными

**Comment by veramal** [comment]
Раз уж лА выделился в отдельный показатель, пусть он будет DistrDial тоже (вместе с лаГла в таблице аффиксов). В литературной норме есть есть ГлА.

**Comment by tuffnatty** [comment]
можно закрывать?

**Comment by veramal** [comment]
Один из тестовых примеров дает 4 разбора вместо 2 на ровном месте.
Непонятно, почему и как:
[image: image.png]

вс, 2 окт. 2022 г. в 15:52, Phil Krylov ***@***.***>:

**Comment by tuffnatty** [comment]
картинка не загрузилась

**Comment by veramal** [comment]
[тарағлааннар](https://khakas.altaica.ru/grammar/#)
v тарирға 1 ‛расчёсывать’ тара
ГлА--------ГАн-----ЛАр--------
Distr--------Past-----Pl--------
v тарирға 2 ‛расходиться’ тара
ГлА--------ГАн-----ЛАр--------
Distr--------Past-----Pl--------
v тарирға 1 ‛расчёсывать’ тара
ГлА--------ГАн-----------ЛАр--
Distr--------Past-----------PredPl--
v тарирға 2 ‛расходиться’ тара
ГлА--------ГАн-----------ЛАр--
Distr--------Past-----------PredPl--

**Comment by tuffnatty** [comment]
не вижу, как это связано с морфологией дистрибутива, и не вижу, почему разборы с PredPl или Pl должны быть запрещены.

**Comment by veramal** [comment]
А, всё, дошло - это из-за двух Pl. Тогда нормально, да.
