### ISSUE TITLE
запретить Part2 в императиве

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#197]
Сейчас есть неверные разборы такого типа: 
_**чӧптеебіс**_
n чӧп 1 ‛совет’
----------------ТАА--ПЫс---
----------------Add₂--1pl---
Семантика при таком разборе получается 'хоть мы и являемся советом' (не органом, а сказанным словом.
(_правильный разбор:_  ‛советовать’ чӧпте+ГА-Past-+ПЫс-1pl)

С ними непонятно, что делать, т.к. есть примеры с именными употреблениями типа _парохтар_ 'тоже имеются'. Но и к чистой основе глагола сейчас такое крепится:
_**сыхтаалар**_ 
v сығарға 1 ‛выходить’ сых
----------------ТАА---ЛАр--
----------------Add₂---PredPl--
(_правильный разбор_:  ‛рыдать’ сыхта + АлАр---Imp.1pl.Incl.dial)
Дополнила правило 34 требованием присутствия показателя времени.

**Comment by adybo** [comment]
Может быть, не бывает императива с предикативным множ.?

**Comment by veramal** [comment]
Бывает, множественное 3 л всегда одинаковое: ползыннар - пусть они будут

**Comment by tuffnatty** [comment]
Поправил правило в парсере, разборы с _сығарға_ больше не выводятся

**Comment by veramal** [comment]
Примеры с ОК на именном сказуемом вполне бывают и в ненужных контекстах не появляются
С ТАА + личные окончания не нашлось примеров, где разбор был бы правильным. 
С LA есть примеры, положу сюда:
_Тур, мин дее **кізілебін**_ - встань; я тоже [всего лишь] человек (Деян 10:26)
_Анзы, сірернең хада Хан - пигібіс Христос Иисуста чуртапчатханыма кееркезім осхас, сын **киречілезім**._ - **свидетельствуюсь** в том похвалою вашею, братия, которую я имею во Христе Иисусе, Господе нашем.
_че сірер мында **ӱзӧлеңнезер**_ - а вас только трое (Алиса, Глава VІІ)
_Ханаттығ аттығ кізі **Сірерлезер** бе, Ханнығ Хылыс?_ - Разве только у тебя, Ханныг-Хылыс, Есть крылатый конь? (Алтын Арығ,  Строки 7592-7595)
_тасхар,, **мындалабын**! “— тидір._  - говорит на улице: «Я здесь!» (Катанов-Радлов)
В большинстве случаев разбор через Cont _LA_ неверный, например: _аарлалар_ (*аар 'пчела'-Cont2-PredPl, аарлал 'очищаться'-Fut), но от него не получится избавиться.
Пока дополнила правило 34 запретом ТАА присоединяться к именным основам, должен и _чӧптеебіс_ теперь не разбираться через Ptcl2.

**Comment by adybo** [comment]
Вот чего там зим окончание? когда в первом примере бин? Мне казалось, что -зим при именах не очень бывает. Может тут как-то затесалось киречи-ле- продуктивное «свидетельствовать»? В русском-то глагол.

**Comment by veramal** [comment]
Скорее, киречілезім - это существительное на -с от глагола на -ла. К чистой основе -зiм тоже не очень лепится.

**Comment by adybo** [comment]
Да, это так. Свидетельство-мое? Либо все же сагайский тут победил и к именному предикату через частицу подъехал.

**Comment by veramal** [comment]
В заготовке статьи так: "Ptcl2 ТАА не присоединяется к именным основам.
Пояснение. Примеров именных сказуемых с внутренней частицей ТАА нам не встретилось (вообще примеры именных сказуемых с частицами довольно редки). Допущение же такой возможности порождает множество параллельных разборов, и до тех пор, пока не найдется убедительного примера подобного употребления, мы решили ее отключить."
Сейчас это условие записано в правиле 34.

**Comment by tuffnatty** [comment]
Добавил условие про ТАА, чӧптеебіс и сыхтаалар больше не разбираются с Ptcl2.

**Comment by veramal** [comment]
Хорошо.
