### ISSUE TITLE
сомнительное сочетание: причастие + аллатив без субстантиваторов

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#198]
Если поискать ГАн+All с нулями между ними, в корпусе почти ничего не находится. Немногочисленные примеры, выпадающие на этот запрос, попадают туда за счет омонимии или лексикализованности основ, например:
_Ол, **турлаанзар** парчадып, школа хыринда тохтабысхан._
Она проезжала к себе **на стоянку**, да остановилась возле школы.
турлағ-(з)Ы-(н)САр - это верный разбор
логовище-3pos-All
тур-лА-ГАн-САр - а это неверный
стоять-Distr-Past-All

_Сизінзе, Ах Кролик аның **хараанзар** кӧні кӧрчеттір._
Оказалось, что сбоку от нее Белый Кролик, который искательно заглядывает ей в глаза.
хараанзар = харах-(з)Ы-САр 'глаз-3pos-All' | ошибочно хара-ГАн-САр 'всматриваться-Past-All'

Или:
**Мыннаң парған тилекейзер, кӱнзер, прай чайаанзар палғалыс.**
Отсюда шла связь ко вселенной, солнцу, всей планете.
Здесь _чайаан_ в принципе не потеряло внутреннюю форму чайа 'создавать'+ГАН уже давно ведет себя как существительное со специфическим значением 'создатель (мира)' / 'созданное = природа'. Есть такие же _чатхан_ 'чатхан', _туган_ 'hодня' и нек. др.

Если же не задавать нули между, то находится пара библейских примеров с настоящими причастиями. Оба они субстантивированы с помощью Pl и обозначают имена деятелей:
_ол, чалӌыларын **виноград ӧскірчеткеннерзер** ызып, виноградтаң позының ӱлӱзін ағыл килерге чахаан._
он послал своих слуг **к виноградарям** взять свои плоды;
_харындастарны нандыра, оларны **пеер ысханнарзар**, амыр хоных алғап, позыдыбысханнар._
они с миром отпущены были братиями **к Апостолам** (букв. к пославшим их сюда).

Если же такой поиск (All с нулями) задать для футурального причастия на Ар, на выходе больше полусотни примеров - и все разобраны неверно. Либо это омонимия с существительным (_чирзер_ - в землю / чi 'есть' + Ар + All), либо, чаще всего, с 2pl (поларзар - верный разбор быть+Fut+2pl, неверный - быть+Fut+All). У причастия на ГАн этой омонимии нет, т.к. ГАн+All = ганзар, а ГАн+2pl = газар.

Предлагаю запретить непосредственное соседство причастий с аллативом. Т.к. аллатив - новый падеж, он не успел приобрести тех дополнительных значений для сентенциальных зависимых, что другие падежи.

**Comment by adybo** [comment]
То есть, ты думаешь, причастия редко бывают актантами в направительном падеже (для предикации он действительно ничего себе не развил). А в дательном? А в родительном?

**Comment by veramal** [comment]
В дательном и родительном все ок. А в аллатив только через мн.ч. или
посессив можно попасть причастиям.

**Comment by adybo** [comment]
Т.е. действительно с особыми еще признаками субстантивации

**Comment by adybo** [comment]
Нужно было бы кстати сделать в словаре следующую правку в поле Deriv
Каузативный суффикс =ТЫр переделать на =ДЫр
Каузативный суффикс =(Ы)Т переделать на =т
эм=ДЫр=т-

**Comment by veramal** [comment]
Почему? У Д есть аллофон н, у каузатива его нет

**Comment by adybo** [comment]
Ок, ты права, оставить ТЫр, но второй каузатив сделать маленьким т и без вставной гласной.

**Comment by veramal** [comment]
Это верно. Вроде я ему убирала вставную гласную когда-то

**Comment by adybo** [comment]
Везде сидит вроде

**Comment by veramal** [comment]
А вот смотри у Катанова:
Kызраk позраk мӱнӱттӱгзӓң - ездишь ты верхом на рыжей кобылице
Это не каузатив (Ы)т от мюн разве?

**Comment by adybo** [comment]
Нет, не может быть, потому что тюг это лыг, который к каузативу непосредственно не лепится. Это какое-то имя по глаголу мюн- (типа мюнют «верховое животное» или «верховность»?)

**Comment by veramal** [comment]
Добавила ограничение 35 для аллатива. Проблема с каузативом не имеет к этом отношения, сейчас вынесу в другую ветку.

**Comment by tuffnatty** [comment]
Закрываем?

**Comment by veramal** [comment]
да
