### ISSUE TITLE
Dur composition rule wrong

### ISSUE THREAD

**Issue by tuffnatty** [tuffnatty/suddenly#2]
> > > `12`. Показатель Dur чА(Т) заполняется только, если заполнена хотя бы одна из позиций 2, 4, (т.е. Form1 или Perf). - это правило запрещает форму адалчатхан из одного из первых предложений романа про утес
> > 
> > Понедельник, 14 декабря 2015, 17:06 +03:00 от Шеймович Александра:
> > В грамматике действительно любое ча, чат (ча, чадыр, чатхан) по правилам присоединяется к "полной или усеченной форме деепричастия на -ып" (с. 201, 216)
> 
> Я понял. Правило 12. Показатель Dur чА(Т) не может быть заполнен, если при этом непосредственно перед ним обнаруживается морфема, оканчивающаяся на гласную.

**Comment by adybo** [comment]
Да, и это надо сказать про несколько показателей. Про все, которые после Form на самом деле.

**Comment by veramal** [comment]
И это не совсем так. Ведь -п потому-то никак не сольешь с презенсами в один показатель, что между ними бывают частицы: пар-даа-ча - идет же, узу-п-ла-ча - постоянно спит. 
Т.о., правило 12: "Показатель Dur чА(Т) не может быть заполнен, если при этом непосредственно перед ним обнаруживается морфема, оканчивающаяся на гласную - кроме морфем из позиции Ptcl 1".
NB: форма парча пока тоже не разбирается.

**Comment by adybo** [comment]
По-моему, парсер пока не учитывает спецформы от пар и кил.

**Comment by veramal** [comment]
с правилами про -п разобрались
