### ISSUE TITLE
Набросок правила для разведения Pl и PredPl

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#20]
0)	Вопрос: Нужно ли PredPl разрешать присоединяться к чистой основе имени? По смыслу да, но в большинстве случаев этот разбор лишний. Мне кажется, лучше не плодить омонимию зазря и запретить.
1)	PredPl может стоять после: а) пок-теля времени (позиция 7 + TIр + ЧIК), б) пок-ля падежа или посессивности, в) некоторых лиц (1pl, Imp.3).
2)	Pl присоединяется ко всем именам, у глаголов – только к причастиям  (Past, Fut, Neg.Fut, Hab, ?Cunc, ?Assum, ?Opt, ?Affirm) с посессивным показателем.

**Comment by adybo** [comment]
Предлагаю разбирать как PredPl любой ЛАр перед точкой. Фил, это возможно?

**Comment by veramal** [comment]
Вообще-то не любой: аттар - это только лошади (предикативные или нет), но не стрелять-PredPl. Так что морфологические ограничения все равно нужны.

**Comment by adybo** [comment]
Да, точно. Не любой, т.е. к чистой основе оно может лепиться только к именам, а к глаголам - только при заполненной позиции 8! (или где там у нас время).

**Comment by veramal** [comment]
Тогда с морфологией так:
PredPl может стоять после: а) пок-теля времени (позиция 7 + TIр + ЧIК), б) пок-ля падежа (18) или посессивности (16), в) некоторых лиц (1pl, Imp.3), г) чистой именной основы.

Pl присоединяется ко всем именам, к глаголам – только при наличии причастных показателей (Past, Fut, Neg.Fut, Hab, Cunc, Assum, Opt, ?Affirm). С посессивностью я погорячилась, и без нее тоже есть.

Про Affirm мы пока не знаем, бывает ли причастием, давайте считать, что бывает.

Про синтаксический фильтр думаем.

**Comment by adybo** [comment]
Давайте

**Comment by asheimovich** [comment]
Ты на гуглдок в ограничения вписала?25.11.2016, 13:46, "veramal" <notifications@github.com>:Тогда с морфологией так:
PredPl может стоять после: а) пок-теля времени (позиция 7 + TIр + ЧIК), б) пок-ля падежа (18) или посессивности (16), в) некоторых лиц (1pl, Imp.3), г) чистой именной основы.
Pl присоединяется ко всем именам, к глаголам – только при наличии причастных показателей (Past, Fut, Neg.Fut, Hab, Cunc, Assum, Opt, ?Affirm). С посессивностью я погорячилась, и без нее тоже есть.
Про Affirm мы пока не знаем, бывает ли причастием, давайте считать, что бывает.
Про синтаксический фильтр думаем.

**Comment by veramal** [comment]
Да, таблица 8, стр. 26.

**Comment by veramal** [comment]
Только про партыр, это не писала пока.

**Comment by asheimovich** [comment]
1. "Ограничения" - это "II. ОГРАНИЧЕНИЯ НА СОЧЕТАЕМОСТЬ АФФИКСОВ". Это я про множественное спрашивала.
2. Про -тыр. Разве в правилах выбора фонетических вариантов можно писать про глагольную основу? Это же вообще лексическое ограничение. А куда это писать и как дать понять парсеру про выпавшее -п...

**Comment by veramal** [comment]
Не лексическое, а морфологическое. Про выпавшее -п ему знать не надо, надо только отследить, что впереди нет аффиксов словоизменительных. Писать больше некуда, вроде как.

Обновила ограничения про множественное число, можно делать.

**Comment by adybo** [comment]
Морфологическое, да. Но после хла будет как после чистой основы тоже, кстати. Я уже теряю нить, а ты, Вера, эти обновления в описании грамматики на гугле фиксируешь?

**Comment by veramal** [comment]
Фиксирую. После хла будет п, никуда не деться.

**Comment by veramal** [comment]
PredPl и Pl сейчас работают.
