### ISSUE TITLE
поиск не справляется, когда много результатов

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#203]
Например, если искать все употребления Cv.p, минуту думает и выдает "Соответствия не найдены". Хорошо бы, если результатов больше 2 тыс, допустим, поиск выдавал общую статистику и выводил первую тысячу результатов.

**Comment by veramal** [comment]
Что-то пока вообще лег.

**Comment by tuffnatty** [comment]
Вроде сейчас справляется
