### ISSUE TITLE
невидимая морфема

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#206]
Вроде боролись с такими разборами, но что-то еще не все убили:
сии - один из разборов
n си <+rus> ‛си’
--------------(Ы)ң-(н)А------
--------------2pos.sg-Dat------

2pos.sg _(Ы)ң_ должен выделяться только в том случае, если _ң_ не поглощается в результате действий сандхи. Если это сложно сделать сначала, то может быть, убивать где-то в конце процесса?

**Comment by tuffnatty** [comment]
закрываем?

**Comment by veramal** [comment]
да
