### ISSUE TITLE
1Sg ым + Gener АдЫр

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#207]
_нанадырым_ - нет разбора

Должен быть нан-адыр-ым 'возвращаться-Gener-1sg'.
В правиле 20 про Gener сказано, что к форме _АдЫр_ присоединяется полный вариант 1Sg _ПЫн_, к форме _АдЫ_ - краткий вариант _(Ы)м_. Теперь видно, что бывает иначе.
Дописала возможность сочетания _АдЫр + Ым_ в голубое поле при смешанном наборе в правиле 20. Вообще в этом поле изначально было зафиксировано только сочетание _Ар+Ым_, которое встречается, но в парсере его лучше не реализовывать - формы типа _парарым_ гораздо чаще являются причастными (_Ым_ понимается как посессивный показатель), и омонимия разборов тут будет только запутывать  (где-то это обсуждалось). 
Но _АдЫр + Ым_ и _чАдЫр + Ым_ ничему не помешают - нужно сделать, чтобы они сочетались.

**Comment by adybo** [comment]
Ну  я все время говорила, мне кажется, что надо ставить свободную сочетаемость для обоих наборов, кроме  -ды и -са, которые только с «кратким». Потому что в диалектах варьирование большое.

**Comment by veramal** [comment]
Причастиям лучше не ставить.

**Comment by adybo** [comment]
Да, в непредикативном использовании

**Comment by tuffnatty** [comment]
закрываем?

**Comment by veramal** [comment]
да
