### ISSUE TITLE
чидiп - неверный разбор через Iter + CvP

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#209]
Для _чидiп_ должен работать разбор _чид-iп_ - достигать-CvP. И не должен  _чi-ады-п_ есть-Gener-CvP. Это не единственная словоформа с таким разбором, но наиболее частотная. Дописала в правило 14.1, что Gener перед CvP может быть только в полной форме АдЫр. То же верно и для СvА.

**Comment by tuffnatty** [comment]
закрываем?

**Comment by veramal** [comment]
да
