### ISSUE TITLE
Разбор приставок

### ISSUE THREAD

**Issue by tuffnatty** [tuffnatty/suddenly#21]
@veramal:
>Приставки типа "кип-" и "ап-" со значением Magn не выделяются парсером, даже если в слове есть дефис.

**Comment by tuffnatty** [comment]
В документе не упоминаются приставки ( Можно, конечно, попытаться их обнаруживать интуитивно, но лучше бы описать, к чему они могут приставляться и при каких условиях.

**Comment by veramal** [comment]
Да, т.к. вроде мы решили не заморачиваться разбирать их как морфемы, а разбирать как слова из словаря. Приставляются избирательно к некоторым именам, это редупликация, непродуктивная. Главная особенность - пишутся через дефис (ап-арах, нап-наа и т.п.). И вот этот дефис, видимо, сейчас им мешает где-то. Было бы круто, если бы вход с приставкой вытаскивался из словаря только в том случае, когда на входе есть дефис (просто "ап" не имело бы разбор через приставку, а "ап-" имело бы) - но это не обязательно.

**Comment by adybo** [comment]
Дефис вообще считается за что? Приставки сейчас записаны в словаре с дефисом на конце как отдельные слова. Если парсер будет находить кусок слова, кончающийся на дефис, и искать его в словаре как отдельное слово, то он найдет как раз эти приставки.

**Comment by veramal** [comment]
Актуально: приставки записаны в словаре с дефисом (ап-), парсер в таком виде их не опознает.
Кроме того, проблема дефиса касается большого числа композитов, в которых есть несамостоятельный элемент - он не имеет шансов быть распознанным.

**Comment by veramal** [comment]
Это тоже: приставки записаны в словаре с дефисом (ап-), парсер в таком виде их не опознает. Кроме того, проблема дефиса касается большого числа композитов, в которых есть несамостоятельный элемент - он не имеет шансов быть распознанным. (Можно записать только вторую его часть в словаре, но опять же с дефисом.)

**Comment by tuffnatty** [comment]
Нужно потестировать теперь, с новым токенизатором

**Comment by veramal** [comment]
пока так: "ап-" разбирается как Magn, однако в словоформе не работает.
ап-айас разбирается, т.к. есть в словаре, ап-ағырығ - нет

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 23 июл. 2020 г. в 15:00, Phil Krylov <notifications@github.com>:

**Comment by tuffnatty** [comment]
В корпусе разбирается (ап- можно найти в корпусе).
В окошке пока не работает алгоритм токенизации, чтобы сработало как в корпусе, нужно расставлять пробелы вручную, т.е. в данном случае написать "ап- ағырығ".

**Comment by veramal** [comment]
Да, приставки с дефисом, которые есть в словаре, сейчас ищутся в корпусе. На запрос "ап-" выдается и слитное "ап-арыг", и раздельное "ап-амыр". Приставки, которые еще не вошли в последнюю версию словаря, с дефисом сейчас не ищутся (раньше искались): на запрос "сып-" ничего не находится, на "сып" находится.

**Comment by veramal** [comment]
Вроде можно считать, что проблема приставок сводится к добавлению нужных вариантов в словарь, а инструментарий сделан.
