### ISSUE TITLE
CvА +Ass ОК

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#210]
Нужно сделать так, чтобы СvA могло соседствовать с ассоциативом только в полной форме. Таких примеров, впрочем, тоже немного (в пределах десятка), но они есть: _Инейлерін тойға **алаох**-килгеннер_ - жен своих на  свадьбу взяв тоже, приехали (сказка Атығӌы Парачап).
Сейчас последовательность CvА +Ass ОК находится 1600 примеров, большую часть которых составляют _ідӧк_ и _пазох_.

**Comment by veramal** [comment]
Вот это тоже изрядно мешается.

**Comment by tuffnatty** [comment]
надо, наверное, добавить правило

**Comment by veramal** [comment]
Дописала в морфонологию в п. II.5 (с. 57).

**Comment by tuffnatty** [comment]
Можно закрывать?

**Comment by veramal** [comment]
Да.
