### ISSUE TITLE
неверный разбор All+PredPl

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#211]
_Ол Петкее маң пирбинче, че **харбазыбыссалар**, хаӌан даа ниндір салча._ - Он вообще Петке не спускал обиды, но всегда сам оказывался битым. (букв. Он Петьке не давал передышки, но **когда они схватывались**, никогда не побеждал (?)).

_харбазыбыссалар_ имеет, помимо правильного, такой разбор:
v харарға ‛стареть’ хар
--------ПАс------(Ы)бЫс-СА----ЛАр--
--------Neg.Fut------1pos.pl-All.dial1----PredPl--

Это происходит от того, что аллатив не был запрещен в предикативном употреблении. Вписала его в правило 29 к прочим падежам.

**Comment by tuffnatty** [comment]
закрываем?

**Comment by veramal** [comment]
да
