### ISSUE TITLE
плохая морфонология : Gener + Imp.2pl

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#212]
У слов типа _чидер_ есть верный разбор: _чит_- достигать + _Ар_ Fut.
А есть неверный: чі- есть + АдЫ Gener + (Ы)ңАр Imp.2pl
Кажется неправильной морфология, при которой _ыңа_ дает краткое _а_. Специальные случаи, когда это действительно так, записаны отдельно: _полдаар/полдар_ 'вы были' ( < пол-ды-ңар)

**Comment by veramal** [comment]
Здесь есть и морфологическая ошибка: нужно запретить императивные показатели после Gener, а также дуративов. Сейчас запишу это в документ. Однако проблему с морфологией это не отменяет.

**Comment by veramal** [comment]
С аналогичной ошибкой разбирается чидiп. 
верный разбор чит + CvP (Ы)п, неверный чi + Gener Ады + (Ы)п
Про это есть правило 14.1

**Comment by tuffnatty** [comment]
Дубль #209?

**Comment by veramal** [comment]
Да.

**Comment by tuffnatty** [comment]
Нет, не вполне дубль. Тут применялось стяжение из п.II.4, а оно не должно применяться при императиве

**Comment by tuffnatty** [comment]
Можно закрывать?

**Comment by veramal** [comment]
Да.
