### ISSUE TITLE
хорошо бы сделать настоящую редупоикацию

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#215]
Сейчас слова типа _хып-хызыл_ 'очень красный' анализируются через композит из двух словоформ: _хып_- и _хызыл_. Это плохо, во-первых, тем, что теоретически _хып_- может присоединяться не только к подходящим словам с началом _хы_-, но и любым другим. Во-вторых, иметь отдельную лексему на каждый вариант V- и CV- неудобно.
Можно ли реализовать настоящее правило редупликации, как оно действует в языке? От именных основ (со значением признака, но мы не будем сортировать) образуется форма (на самом деле новая лексема, но тоже неважно) со значением усиления признака. Для этого нужно скопировать первую букву слова (если это гласный) или первые две буквы (если это согласный+гласный или долгий гласный) или первые три буквы (если это согласный + долгий гласный), к получившейся цепочке приписать "_п-_" и поставить перед основой. От других типов основ такая форма не образуется.

**Comment by tuffnatty** [comment]
https://khakas.altaica.ru/corpus/?word1_distance=&word1_wordform=&word1_wordform_lookup=iexact&word1_lexeme_auto=&word1_lexeme_auto_lookup=iexact&word1_features_auto=1&word1_semgloss_auto=&word1_semgloss_auto_lookup=iexact&translation_ru=&context_width=&page=1

Если убрать из словаря отдельные лексемы с редупликацией, результатов станет больше

**Comment by veramal** [comment]
Из словаря надо будет убрать, пожалуй, да. Но присутствие таких лексем не увеличивает количество примеров с найденной редупликацией, а увеличивает лишь количество разборов (см. пример с _хап-харасхыдаңар_ из Алисы). А сейчас Magn (_тап | сып | хап | чіп | кӧп | тып | чип | уп | чоп | ап_) по какому принципу собран? Это ведь явно не все, вот в Сыын мююзи есть _топ-тоғылахтар_, который разбирается только через словарь.
Еще найденные результаты выявили, что если Magn делать таким, как сейчас описывают правила, то через него ошибочно разбираются примеры с полной редупликацией: _кӧп-кӧп, чіп-чіп, хап-хап_ и т.д. Видимо, надо дополнить эти правила запретом на образование Magn от имен вида CVп.

**Comment by tuffnatty** [comment]
> Но присутствие таких лексем не увеличивает количество примеров с найденной редупликацией, а увеличивает лишь количество разборов (см. пример с _хап-харасхыдаңар_ из Алисы).

Уменьшает, т.е. в этом примере из-за того, что в словаре нашлось хап-харасхы, не стал рассматриваться харасхы с редупликацией (а только харасхыда). Мне кажется, так лучше будет (если убрать из словаря лишнее и оставить только нетривиально переводимые идиомы). Можно рассматривать в любом случае, но тогда теряется возможность override'а словарем.

> А сейчас Magn (_тап | сып | хап | чіп | кӧп | тып | чип | уп | чоп | ап_) по какому принципу собран? Это ведь явно не все, вот в Сыын мююзи есть _топ-тоғылахтар_, который разбирается только через словарь.

Вот как раз наблюдается эффект: лексема нашлась в словаре > гипотеза с Magn не стала рассматриваться > в таблицу аффиксов не попала.

> Еще найденные результаты выявили, что если Magn делать таким, как сейчас описывают правила, то через него ошибочно разбираются примеры с полной редупликацией: _кӧп-кӧп, чіп-чіп, хап-хап_ и т.д. Видимо, надо дополнить эти правила запретом на образование Magn от имен вида CVп.

И еще что-то не видно удвоенных гласных, но из-за слабого ограничения парсится чип-чиит (хотя д.б. чиип-чиит?)

**Comment by veramal** [comment]
Чип-чиит правильно, еще с долгой есть тӧп-тӧӧй в словаре. Выходит, для долгих не нужно отдельного условия. Лексемы удалила.

**Comment by adybo** [comment]
Вер, давай уберем? Только надо смотреть, чтоб какую-нибудь сильную фразеологизацию, если вдруг есть, не потерять.
  
>Суббота, 28 мая 2022, 23:00 +03:00 от Phil Krylov ***@***.***>:
>Если убрать из словаря отдельные лексемы с редупликацией, результатов станет больше

**Comment by adybo** [comment]
Наверное, долгота не редуплицируется.

**Comment by veramal** [comment]
Почистила словарь.
