### ISSUE TITLE
аттар - 3 т вместо двух

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#216]
аттар теперь имеет в т.ч. такие разборы:
v атарға 1 <+no-envoice> ‛стрелять’ ат
-т-------ТЫ----------(Ы)ңАр---
-Caus-------RPast----------2pl.br---
v атарға 2 <+no-envoice> ‛рассветать’ ат
-т-------ТЫ----------(Ы)ңАр---
-Caus-------RPast----------2pl.br---

Причем по 2 штуки, т.к. окончания mix пока просто переименованы, но не убраны. Но здесь обращаю внимание на то, что последовательность ат+т+ТЫ не может быть получена из аттар, т.к. на нее нужно три буквы т, а здесь две. Интересно также, что аналогичный разбор без каузатива (ат+ТЫ+(Ы)ңАр) не предлагается.

**Comment by tuffnatty** [comment]
Починил вроде

**Comment by veramal** [comment]
Врода да
