### ISSUE TITLE
исправить 2pl.br (Ы)ңАр на 2pl.br ңАр

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#217]
Т.к. это окончание встречается только после аффиксов, кончающихся на гласную, то Ы не проявляется, правильнее ее убрать.

**Comment by adybo** [comment]
Да, разумеется!

**Comment by tuffnatty** [comment]
в табличке ничего не поменялось

**Comment by veramal** [comment]
Поменяла.

**Comment by tuffnatty** [comment]
готово

**Comment by adybo** [comment]
Ура

  
>Понедельник, 3 октября 2022, 19:22 +03:00 от Phil Krylov ***@***.***>:
> 
> 
>Closed  #217 as completed.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you commented. Message ID:  <tuffnatty/suddenly/issue/217/issue_event/7508923691 @ github . com> 
 
 
--
Anna Dybo
Отправлено из Почты  Mail.ru
