### ISSUE TITLE
Neg.NFSh ПААн на конце словоформы

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#218]
Добавила в п. 4 ограничение: Neg.NFSh ПААн не должен быть на конце словоформы. 
Мы запрещаем этот показатель на конце словоформы для избегания омонимии разборов в чрезвычайно частотных словоформах типа _полбаан_. Для хакасского языка верным анализом является отрицательная форма обычного прошедшего времени: ‘был’ (_пол-ба-ган_ быть-Neg-Past). В нашем корпусе ни разу не встретилось деепричастное или NF-употребление аффикса ПААн перед пробелом. А в шорском языке для форм типа _полбаан_ действительно возможны два анализа: как формы прошедшего времени и как деепричастной формы (_пол-баан_ быть-Neg.Cv).

**Comment by tuffnatty** [comment]
Добавил
