### ISSUE TITLE
Стяжение 2pl

### ISSUE THREAD

**Issue by tuffnatty** [tuffnatty/suddenly#22]
@veramal: Не сделаны сандхи вот эти: стяжение 2pl: Выпадение сонанта ң из личного афф. 2pl ңАр в интервокальной позиции после Cond СА и RPast ТI [не всегда]: пас-са-ңар > пас-сар ‘если будем писать’, пас-па-за-ңар > пас-па-зар ‘если не будем писать’, пас-ты-ңар > пастар 'вы недавно написали'.

**Comment by veramal** [comment]
Актуально. Есть написание с одной гласной (пассар) и с двумя (пассаар).

**Comment by adybo** [comment]
Это условное наклонение?

**Comment by veramal** [comment]
В том числе условное.

**Comment by adybo** [comment]
В условном это сандхи, а  в других - добавить серию личных окончаний.

**Comment by veramal** [comment]
Вот это надо сделать обязательно. Копирую текст на всякий случай:

Не сделаны сандхи вот эти: стяжение 2pl: Выпадение сонанта ң из личного афф. 2pl ңАр в интервокальной позиции после Cond СА и RPast ТI [не всегда]: пас-са-ңар > пас-сар ‘если будем писать’, пас-па-за-ңар > пас-па-зар ‘если не будем писать’, пас-ды-ңар > пасдар 'вы недавно написали'. 
В условном встречается также написание с двумя гласными (пассаар).

**Comment by tuffnatty** [comment]
пассаар не задокументировано в документе.

**Comment by tuffnatty** [comment]
пастар, пассар сделал. пассаар нет в документе

**Comment by veramal** [comment]
Есть, я вчера дописала.

**Comment by tuffnatty** [comment]
Сделал.

**Comment by veramal** [comment]
Странно получилось: для RPast формы с глухим вариантом разбираются (пастар), а со звоким - нет (чоохтадар). У Cond оба варианта работают.
