### ISSUE TITLE
не работает Cont

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#23]
парлаҷа / парлача не разбирается - возможно, из-за морфонемы L. дописала правило ее распределения в раздел о фонетике

**Comment by tuffnatty** [comment]
Добавил морфонему L. Теперь парлаҷа работает

**Comment by veramal** [comment]
Ок, чтобы работало орфографически правильное парлача, нужно сделать глухое ч в интервокале - это описано в другом баге здесь.
