### ISSUE TITLE
чередование конечных -ст\-с в основе

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#29]
истiп, специализі - не работают, т.к. не внедрены сандхи про чередование конечных -ст\-с в основе. Основа, отличающаяся от основы словарной формы, выписана в словаре в поле ALTERNATEN.

**Comment by veramal** [comment]
Это тоже надо сделать: истiп, специализі - не работают, т.к. не внедрены сандхи про чередование конечных -ст-с в основе. Основа, отличающаяся от основы словарной формы, выписана в словаре в поле ALTERNATEN.

**Comment by tuffnatty** [comment]
Починил, но надо а) перестроить словарь и б) запретить изып, специалисти

**Comment by veramal** [comment]
истіп работает, систіп - нет

**Comment by tuffnatty** [comment]
Сделал, получился интересный эффект:
n специалист <+rus> ‛специалист’
специалис
----------------ти-----
----------------Gen.3pos-----

**Comment by adybo** [comment]
Это все анализы, или один? Потому что это один из возможных

**Comment by veramal** [comment]
Вроде сейчас без эффекта.

**Comment by tuffnatty** [comment]
специалисти разбирается как специалис+ти.
специалисті не разбирается из-за неработающей переднерядности _и_ в русских заимствованиях

**Comment by veramal** [comment]
Ну да, но специалисти - несуществующая форма. Шансов, что такие формы омонимичны чему-то существующему, очень мало, мне кажется. Пусть живет.

**Comment by adybo** [comment]
У меня в тексте написано, что в русских заимствованиях в непервом слоге и считается передним, как и в своих словах в первом слоге


>Четверг, 30 ноября 2017, 17:08 +03:00 от Phil Krylov <notifications@github.com>:
>
>специалисти разбирается как специалис+ти.
>специалисті не разбирается из-за неработающей переднерядности  и в русских заимствованиях
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo
