### ISSUE TITLE
форма партырлар не разбирается

### ISSUE THREAD

**Issue by tuffnatty** [tuffnatty/suddenly#3]
@adybo:

> форма партырлар не разбирается, причем не вижу к этому препятствий. Должен разбирать - идти-Indir-Pl

**Comment by tuffnatty** [comment]
> партыр тоже не разбирается, кстати. из-за кривого правила о конверье на -п, с которого началась дискуссия (т.е. парсер хочет, чтобы было парыптыр)

**Comment by veramal** [comment]
Ань, а какая у нас стратегия вообще? Мы выкапываем в текстах по максимуму сразу, или ждем, что Фил сначала поправит вот это и 3pos?

**Comment by veramal** [comment]
еще один из крупных багов: 
айдаңар. Один из разборов такой:

i ай ‛1)’
---------------даңар----
---------------DELIB----

Почему invar присоединяет падежи?

**Comment by tuffnatty** [comment]
@veramal:  давайте заводить отдельные Issue для нового бага с айдаңар и других, а то никакой стратегии не будет, а будет то же, что и в почте :-(

#3 я поправлю, как только получу точную формулировку. А про 3pos и вовсе не понял

**Comment by veramal** [comment]
ок. про 3pos было в вордовском файле с багами, но неважно, сейчас заведу ему отдельное

**Comment by veramal** [comment]
а, 3pos разбирается, хорошо

**Comment by tuffnatty** [comment]
1. партыр: пар + Indir ТІр дает пардыр (т.к. Т после звонкого согласного дает д), который и разбирается соответствующим образом: http://khakas.corpora.tk/suddenly/?parse=пардыр
2. партырлар не разбирается пока что по той же причине, но:
3. пардырлар не разбирается из-за 
![image](https://cloud.githubusercontent.com/assets/315636/12004060/dfd0e166-ab60-11e5-8652-11117e2064cf.png)

**Comment by adybo** [comment]
Этот аффикс, индир, оказывается, с т простым, а не  т большим: полтыр, хонтыр. Про него только надо писать специальное исключение, что после отрицания (кумулятивного с form 1, т.е. -бин-) он все-таки дыр, т.е. он озвончается не в фонетических условиях, а в морфологических. 
Еще про него надо в правилах сочетаемости тоже написать, что он не бывает после гласных, т.к. после гласных вставится -п или же, если после отрицания, то с форм1. Не знаю, что будет, если он будет после -ча-, а потом отрицания, вероятно, тоже бин? Тогда это уже будет конв с отрицанием, а не форм? Не знаю, что будет, если перед тыр будет частица даа или лаа. Вера, ты знаешь?7

**Comment by adybo** [comment]
Если после бин он все-таки дыр, то может пусть остается Тыр? Зачем писать лишнее правило? Все равно напишется куча оговорок, но лучше к одному правилу про один формант.
Про "надо написать":  если я буду писать, ты потом все равно еще допишешь и перепишешь. Проще тебе самой и написать и покрасить в любой цвет, написав слово НОВОЕ. Я же с этой целью тебе табличку высылала, чтоб ты пользовалась.

25.12.2015, 21:47, "Anna Dybo" <adybo@mail.ru>:

**Comment by veramal** [comment]
Вместе с ча будет чат-тыр / бин-чат-тыр. Форма чадыр - это ча + дыр, который Iter. С частицами примеров не попадалось - скорее всего, и не попадутся.

**Comment by adybo** [comment]
Так он фонетически всегда тыр, кроме этой позиции после отрицания. Тогда придется писать еще много правил, почему он почти всегда после звонких тыр.

**Comment by adybo** [comment]
Нет, а вот если отрицание будет после ча, я имею в виду? Отрицание в принципе бывает после ча, и почему бы такой форме не оформиться еще и индирективом.

**Comment by veramal** [comment]
А когда отрицания после ча бывает?

25 декабря 2015 г., 23:16 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
кӧп чоохтанма, хоорам-хаӌан позыңа читчетпезін много (лишнего) не говори, когда- нибудь против тебя не обернулось бы.
ЧИДЕРГЕ /чит-/ I 1) достигать чего-л.

**Comment by veramal** [comment]
Ух ты, это из словаря?
Но на самом деле вид отрицания диктуется временным/модальным показателем.
Тут он ба, потому что императив, а при тыр будет бин.
И, Аня! Этот пример против тезиса о том, что ча и чат - всего лишь
позиционные варианты. Потому что ча имеет власть над отрицанием, а чат - не
имеет.

26 декабря 2015 г., 0:26 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Что такое "имеет власть"? 
Ча бывает в конце просто, нет? Либо конец, либо показатели предикативности, либо -дыр, который никак не может клеиться к чат. 

Да, при тыр обязан быть бин, потому что тыр требует перед собой деепричастия (либо форм, либо конв в нашей терминологии). Но бывает ли? В словаре нету.

**Comment by adybo** [comment]
Вид отрицания - это бин ведь не отрицание, а отрицание с деепричастным показателем. Кому нужен дееприч. показатель, тот и берет его. Он у нас разбирается как кумулятивный.

**Comment by veramal** [comment]
Имеет власть - значит, определяет вид аффикса отрицания.

Про ча не поняла.

Вот как про него в граматике говорят, с. 218-219: узу-бин-дыр '(он) не спал
(оказывается)’, кӧр-бин-дір '(он) не видел (оказывается). В сагайском
диалекте: узу-баан-дыр(< у зу -б а -ған -ды р ), кӧрбеендір (
<кӧр-бе-ген-дір).
В Казановке последний вариант точно: saška alɨs-pan-dɨr-daa     Сашка даже
не изменился. В Трошкине, кажется, первый.


26 декабря 2015 г., 1:40 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
Ну, неважно. Если считать ча и чат одной сущностью, то выходит, что в одних случаях ему нужен деепричастный показатель, в других нет. Тут, кста, принципиально, как выглядит форма, аналогичная читчетпезін от основы на гласную. (Ну, для философии скорее, анализ для всего можно написать).

**Comment by veramal** [comment]
Да, наоборот тоже бывает: кӱс _хаппинчатса_, сӱменен' аларга кирек - _если не хватает_
сил, нужно прибегнуть к хитрости;

**Comment by adybo** [comment]
Ну да. Вид аффикса отрицания - т.е. будет он без ничего или с деепричастной (причастной) затычкой - определяется тем, что идет дальше. Если это дальше - бывший вспомогательный глагол, который вообще-то когда-то цеплялся к деепричастию - то надо затычку.
То, что отрицание перфектного (дее)причастия на -п ходит как отрицательный перфект на -ган - с древнетюркских времен - это такой же прикол, как то, что отрицание причастия будущего времени на -р ходит как отрицательное причастие желательности-будущести на -с (оно в неотрицательной форме сохранилось в чувашском), а также отрицание заглазного перфекта на -мыш ходит как отрицательное (заглазное) перфектное причастие на - дук. Так уж они пораспределились в общетюркском.

**Comment by adybo** [comment]
Ну как, ему всегда нужен деепричастный показатель. Он же вспомогательный глагол всегда. Просто если перед ним нечто на согласную, то, когда оно цепляет это -п, то это -п падает. 

Конечно нечто типа ода-п-чат-па-зын

**Comment by adybo** [comment]
Ну да, конечно! 
Там какие-то суровые разницы, но мы их пока не видим.

**Comment by veramal** [comment]
Думаю, суровая разница в том, что чат не может вот так вот взять и присоединить к себе окончание. Потому что превратится в тыкву, то есть в ча.

А что там про отрицательный конверб: бин - это оттуда же, откуда баан?

BTW, есть еще и третий -дыр - который бывает как окончание 3sg типа. Который тоже не работает. Щас напишу про него отдельно.

**Comment by adybo** [comment]
Да ведь чат и ча одно и то же ;-) Просто тип границы разный, поэтому разные фонетические правила. Это Барулин для турецкого описывал в своем диссере кандидатском -  несколько слоев клитик, и на границах слоев правила сандхи разные.
Ну да

**Comment by adybo** [comment]
Да, бин оттуду же. Буква "и" в непервом слоге - только из стяжений.

**Comment by veramal** [comment]
Ну да, значение разное, форма разная, правила разные - но этимологу-то один
хрен, понятное дело :)

26 декабря 2015 г., 3:13 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Где же значение разное? Найди случай, когда ча можно заменить на чат и от этого изменится значение. Первое правило дескриптивиста.

**Comment by veramal** [comment]
Встречаются в одной словоформе:
Ізіг чайғы кӱннерде суғ амыр, эрінч'ек *ахчатча* (НД)
'В летние жаркие дни вода течет спокойно, лениво’;

**Comment by adybo** [comment]
Очень мило. Такой формы по грамматике вообще не может быть, если я не ошибаюсь. Вера, я ошибаюсь?
Тогда надо в столбик temp вставить еще показатель ча Praes. Dixi.

**Comment by veramal** [comment]
Это пример из грамматики. С. 84.

26 декабря 2015 г., 14:19 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
Но вообще, конечно, редчайший случай, в тырнете примеров не найти.

26 декабря 2015 г., 14:52 пользователь Vera Maltseva <malt.wh@gmail.com>
написал:

**Comment by adybo** [comment]
иркезін сағынып, ипчі кізі иклеп чӧрчетче тоскуя о своём ребёнке, женщина напевает грустную песню. Второй пример, из словаря. Значит, бывает. Но бумажной грамматикой не описывается. И Баскаковским очерком, как я понимаю. Тогда оставляем дуратив чат и добавляем презенс ча во времена, делать нечего. Но дуратив отставляем ча(т), иначе не прокатят вот эти
V- ыбыс - ча - дыр Iter (- чых ) 
v -ыбыс-чад-а-дыр Iter (-чых)

**Comment by adybo** [comment]
В тырнете вообще сложно найти что-то по-хакасски, выходящее за пределы простой диалогической речи, я думаю.

**Comment by veramal** [comment]
Что-то перевод далек от смысла в этом примере, ну да ладно.
В тырнете как раз много учебников распознанных, а форумов не очень.
Не вписывается только чадыр - но ему деваться некуда, надо от чаттыр
отличаться. Грамматика его считает качинским диалектизмом.
Надо тогда переписать правила, чтоб было про ча(т) и про ча.

26 декабря 2015 г., 15:39 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
Тогда дыр тоже можно считать презенсом, как в грамматике, всем легко будет. Собственно, непонятно, почему дыр сейчас живет в отдельном слоте, а не во временном.
С пари/кили сложнее из-за париган.

**Comment by adybo** [comment]
Например вот поэтому в отдельном
v -ыбыз-а-дыр Iter (-ган)

**Comment by veramal** [comment]
Йоу. Плюсквармперфект какой-то, а не паст.

27 декабря 2015 г., 0:58 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
В общем, дырган. как и ирган.

**Comment by veramal** [comment]
Но вообще-то, конечно, во всех этих причастиях настоящего времени - чатхан, дырган, иган - ган выступает не как сдвиг в прошлое, а как номинализатор. Время-то остается настоящее - только нефинитное.

**Comment by veramal** [comment]
Тут было много всего, но сейчас еще не разбирается из-за 2 багов: начальная морфонема в Indir и лар для предикатов.

**Comment by veramal** [comment]
разбираем партыр
Правило вариантов для TIр - морфологическое: при присоединении к основе всегда глухой вариант тыр/тiр, после любых аффиксов - по обычным правилам. Сейчас допишу в таблицу вариантов условие, и можно чинить. Если для этого надо отдельную морфонему заводить, пусть ДIр будет, например.

**Comment by adybo** [comment]
Да, это потому, что при присоед. к основе оно реально после *-п

**Comment by veramal** [comment]
Написала в таблице с вариантами Indir в гуглдоке фиолетовым.

**Comment by veramal** [comment]
по-прежнему партыр - очень частотная форма, которая не разбирается
После звонких в основе глухое: пар-тыр, сом-тыр.
После звонких в аффиксах (подходящих только два: Neg.Conv и Past) звонкое: пар-бин-дыр, пар-ба-(г)ан-дыр.
В остальном как обычное Т.

**Comment by tuffnatty** [comment]
Реализовал так (мне не хочется в морфонемы добавлять знания о том, относится ли предыдущий звук к основе):

**Непосредственно после неглухой согласной основы выбирается Indir тІр.
В остальных случаях Indir ТІр.**

партыр, сомтыр, парбиндыр, парбаандыр работают. парбаандыр разбирается также как Neg-Past-Foc, а Foc тоже может не озвончаться после звонкой основы? В таблице Т, а не D.

**Comment by adybo** [comment]
По-моему, слово "основы" из этого правила можно выкинуть

**Comment by veramal** [comment]
Упоминание про основу нельзя выкинуть: сомтыр, но парбиндыр/парбаандыр.
Foc озвончается как обычно: кемдыр.
Так что все верно.

**Comment by tuffnatty** [comment]
да. так мое предложение - выкинуть морфонему D, а вместо этого написать в
правилах сочетаемости, что после звонкой основы тIр, а в остальных случаях
ТIр.

**Comment by veramal** [comment]
По идее морфонемы нужны для того, чтобы все алломорфы собрать воедино одной записью.

**Comment by tuffnatty** [comment]
Но есть правила 8.1, 9.2, 9.3, 26, которые, как мне кажется, ничем не лучше. А реализацию это (отсутствие у морфонемы "знания" о том, основа ли слева) значительно упрощает.

**Comment by adybo** [comment]
И теоретически морфонема не должна различать, основа перед ней или аффикс!

**Comment by adybo** [comment]
Это правда, но по идее морфонема не может зависеть от глубже чем морфонологического окружения. Например, гласную в воз-/вез- ты не можешь записать единой морфонемой.

**Comment by veramal** [comment]
Да вообще-то теоретические установки для меня тут не важны., главное, чтоб работало.
