### ISSUE TITLE
сандхи в многосложных на -К

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#30]
чӱрее (чӱрек+3pos) - нет разбора
Не работают стяженные посессивные формы от многосложных основ с конечным -к (описание есть в сандхи). Тут нужно не ориентироваться на словарь, а сделать общее правило (слов типа "чӱрек" гораздо больше, чем слов типа "абрек").

**Comment by veramal** [comment]
Чтобы "абрек" не стягивался зазря, можно слова с пометой russ исключить из действия правила.

**Comment by veramal** [comment]
чӱрее (чӱрек+3pos) - нет разбора. Нужно сделать как возможный вариант для всех слов, у которых нет пометы rus.

**Comment by tuffnatty** [comment]
Сделал. Но не запретил для rus.

**Comment by tuffnatty** [comment]
Запретил для rus. Теперь сенее не разбирается как сенек+3pos, это хорошо?

**Comment by veramal** [comment]
Это хорошо. Только сейчас имеем по 2 копии каждого разбора. А основу хузух --> хузуғ можно не переделывать, или по-другому не получается?

**Comment by tuffnatty** [comment]
Да, 2 копии как раз из-за заполненных ALTERNATEN с озвончением, берутся оба варианта основы, а выпадение х/к обрабатывается без оглядки на ALTERNATEN. Наверное, следует запретить восстанавливать основу из WORD, если хоть какие-то слоты заполнены и заполнено ALTERNATEN? Или запретить выпадение х/к при незаполненном ALTERNATEN? Как правильно?

**Comment by veramal** [comment]
Запрещать точно не надо. Если выполняется без оглядки, тогда ее вообще, может, заполнять не надо для этих случаев, а заполнять только для беглых гласных? 
А может все-таки основа выглядеть как "хузух", а не "хузуғ" после парсера?

**Comment by tuffnatty** [comment]
Беглые гласные тоже вроде автоматом обрабатываются, без выписывания основы.

**Comment by adybo** [comment]
Я сейчас ввела в текст про многосложные так, чтобы для всех было оба варианта разбора (это диалектное)


>Четверг, 30 ноября 2017, 16:37 +03:00 от veramal <notifications@github.com>:
>
>Это хорошо. Только сейчас имеем по 2 копии каждого разбора. А основу хузух --> хузуғ можно не переделывать, или по-другому не получается?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Я это в нынешнем тексте переделала


>Четверг, 30 ноября 2017, 17:10 +03:00 от veramal <notifications@github.com>:
>
>Запрещать точно не надо. Если выполняется без оглядки, тогда ее вообще, может, заполнять не надо для этих случаев, а заполнять только для беглых гласных?
>А может все-таки основа выглядеть как "хузух", а не "хузуғ" после парсера?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Там же есть минимальные пары.


>Четверг, 30 ноября 2017, 20:00 +03:00 от Phil Krylov <notifications@github.com>:
>
>Беглые гласные тоже вроде автоматом обрабатываются, без выписывания основы.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Сейчас не анализируется _чӱреебіске_ , при этом _чӱреебіс_ и _кӱнібіске_ работают.

**Comment by tuffnatty** [comment]
_чӱреебіске_ - **чӱрек** имеет помету poss, поэтому для него датив выбирается из посессивного набора (правило 17).

**Comment by veramal** [comment]
Значит, надо ввести поправку: при наличии 1pl.poss или 2pl.poss выбирается
непосессивный тип склонения.

2017-12-05 5:30 GMT+03:00 Phil Krylov <notifications@github.com>:

**Comment by veramal** [comment]
Поправила в правиле 17: "набор аффиксов посессивного склонения выбирается ... **непосредственно** после основ с пометой poss".

**Comment by tuffnatty** [comment]
Реализовал.
