### ISSUE TITLE
заводтар

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#31]
Не работает словоизменение русских слов с конечными несонорными звонкими. В словаре прописана глухая основа, но пока не у всех. Можно ориентироваться на помету russ - вроде бы она охватывает весь словарь. Конечные согласные Б, В, Д, Ж и З можно считать глухими, т.к. ими кончаются только русские слова (а Г не так).

**Comment by asheimovich** [comment]
rus не во всем словаре пока. примерно до П. Постараюсь закончить вскорости. Еще мы зачем-то хотели, чтобы там безударная гласная о считалась за а (забыла пример).
 и И за I шло - очкизін чтоб разбирались? Или этого мы не хотим?

**Comment by veramal** [comment]
Нет, там совсем другие проблемы. И лучше все в кучу не мешать, даже если похоже.
Тем более тогда проще сделать В, Д, Ж и З глухими по морфонологии.

**Comment by asheimovich** [comment]
Это то, что может зависеть от пометы rus.

**Comment by veramal** [comment]
Ладно, сейчас напишу про них тоже отдельно.

**Comment by adybo** [comment]
Хотим, чтоб разбиралось, это надо написать про русские слова. А то оно думает, что там нарушен синармонизм (и второго слога нейтральное, а о заднее)

**Comment by veramal** [comment]
Про очки я пока не писала.  _очкизін_ не разбираются не потому, что это русское слово, а из-за того, что они написаны по сагайской морфонологии. А нам бы сначала с литературной разобраться.

**Comment by veramal** [comment]
Проблема заводтар - тоже важная. Помета rus.

**Comment by tuffnatty** [comment]
Реализовал. В словаре проставлены основы со звездочками для таких слов, но парсеру они не нужны, если только не предполагается разбирать _завоттар_, _скандинаптар_. А если нужны вам, то почему у **завод I** стоит `завот`, а у **завод II** - `завот*`?

**Comment by adybo** [comment]
Нет, оба одинаковые

**Comment by veramal** [comment]
Есть еще случаи с ь после глухого: _тетрадьтаң_. (тетрадь есть в словаре, анализируется)

**Comment by adybo** [comment]
Да, надо внести обращение с мягким знаком

**Comment by tuffnatty** [comment]
_тетрадьтаң_ разбирается.
