### ISSUE TITLE
неотчуждаемая принадлежность

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#32]
істінде - нет разбора
Не работает (посессивное) склонение у слов с неотчуждаемой принадлежность. Они ловятся словарной пометой poss в поле FORM.

**Comment by veramal** [comment]
У icтi работает номинатив, а у кöксі и того нет. Видимо, из-за того, что у второго в полях word и Headword стоит кӧгіс, а не кöксі (хотя статья кӧгіс есть отдельно).

**Comment by asheimovich** [comment]
А помета poss там есть?
А в спец. файл пишешь? Конечно, я и сюда могу заходить, но файл тоже пусть будет. Я жду, когда ко мне вернется словарь.

**Comment by veramal** [comment]
Есть. Да, пишу.

**Comment by veramal** [comment]
И вот это тоже очень частотное: істінде - нет разбора
Не работает (посессивное) склонение у слов с неотчуждаемой принадлежность. Они ловятся словарной пометой poss в поле FORM.

**Comment by tuffnatty** [comment]
Починил, но надо перестроить словарь

**Comment by tuffnatty** [comment]
заработало

**Comment by veramal** [comment]
сейчас опять не работает

**Comment by veramal** [comment]
Почему-то в генитиве и в аблативе работает, а в других падежах нет:
алтынаң
n алт <+poss> ‛низ’
----------------ы-наң----
----------------3pos-Instr---

алтының
n алт <+poss> ‛низ’
----------------ы-ның----
----------------3pos-Gen₂----
