### ISSUE TITLE
полдаачатса

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#33]
полдаачатса - нет разбора
Не было учтено, что ч в Dur не подвергается интервокальному озвончению.

**Comment by veramal** [comment]
Сюда же: презентное глухое ч в интервокале тоже пока не работает - пардаача, парлача.

**Comment by adybo** [comment]
Написали, что ч никогда не озвончается, а озвончение применяется к фонемам а не к морфонемам.

**Comment by veramal** [comment]
Где написали, что никогда? В сандхи написано как есть.

**Comment by adybo** [comment]
Там все по ч зачеркнуто и написано, что не озвончается (и про все согласные изменена трактовка: это уже не морфонемы), а про после частицы предлагается, если это существенно, решение в комменте

**Comment by veramal** [comment]
Нда, действительно, можно не учитывать - встретилось только два примера:
«Мин пілбиндееҷем андағ ниме»,— тіп, ахтығ позын сығарыныбысхан Икен.	«Я такое и не знаю даже»,— сказал Икен, показав свою честность. (МС (нет расшифровки имени) - ГХЯ)

Ол нимелерні сірер пілбиндееҷе поларзар. 	Может быть, вы и не знаете всего этого. (Чебодаева)

Будем считать опечатками?

**Comment by adybo** [comment]
Давайте пока считать опечатками.

**Comment by tuffnatty** [comment]
Исправил.
