### ISSUE TITLE
падежные формы в качестве предикатов

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#34]
Сейчас у нас допускается сочетание любых падежных показателей с лично-числовыми. Между тем, это явно не так: Эльвира говорит, что предикатами могут быть только локатив и датив. Предлагаю написать ограничение, поскольку порождается много лишних разборов.

**Comment by adybo** [comment]
Нельзя пометить ограничение концом клаузы? точка, запятая, точка с запятой, двоеточие, воскл. и вопр. знаки.

**Comment by veramal** [comment]
Не поняла, что именно предлагаешь. Ограничение типа: "перед Person и PredPl из значений Case допустимы только локатив и аблятив". Куда тут воткнуть знаки препинания?

(Тем более, уже обсуждали, что финитный предикат далеко не всегда рядом со  знаком препинания.)

**Comment by veramal** [comment]
Сделано в другом месте.
