### ISSUE TITLE
муңар: распределительные числительные

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#35]
У числительных есть разделительные формы. Первая из них очень похожа на множественное число, но не оно: 

"-ар/-ер (после основ на согласные), -лар/-лер (после основ на гласные); пір 'один’ — пірер 'по одному’, алты 'шесть’— алтылар 'по шести’, читі 'семь’ — читілер 'по семи’, тогыс 'девять’ — тоғызар 'по девяти’, хырых 'сорок’ — хырығар 'по сорок’. 

Вторая - вербализация в наречной форме от первой:
-арлап/-ерлеп (после основ на согласные), -ларлап/-лерлеп (после основ на гласные) (< -ар + -лап/-ер + -леп, -лар + -лап/-лер + -леп, в которых -лап/-леп исторически восходит к сложному аффиксу, состоящему из -ла/-ле, образующего глагол от имени, + -п — аффикса деепричастия): пір
'один’ — пірерлеп 'по одному’, 'в количестве одного’, пис 'пять’ — пизерлеп 'по пять’, 'впятером’, алты 'шесть’ — алтыларлап 'по шесть,’ 'в количестве шести’, 'вшестером’, он 'десять’ — онарлап 'по десяти’, 'десятками’." (ГХЯ:120).

Она редко, но все же встречается в реальности, вот из газетных подборок: 
_машиннай залдағы **онарлап саннығ** моторлар_ - 'многочисленные (т.е. 'десятками считанные') моторы машинного зала'
(изысканный пример на части речи, по-моему)

Сейчас они не разбираются парсером. Будем заводить морфемы или вгоним все это в словарь?Формы образуются от всех числительных, но их все же немного.

**Comment by asheimovich** [comment]
Я бы в словарь... Это единицам, десяткам и числам типа сто, тысяча надо сделать?

**Comment by veramal** [comment]
Да. И миллиону с миллиардом не помешает.

**Comment by adybo** [comment]
Местоимения мы вогнали в словарь. Вероятно, с этими надо поступить так же. Иначе надо будет строить отдельные парадигмы для слов с сем. пометой Numer. Надо только не забыть загнать формы не только от числит., но и от колич. слов - по скольку, по стольку, помногу, помалу, что еще?

**Comment by veramal** [comment]
"Надо только не забыть загнать формы не только от числит., но и от колич. слов - по скольку, по стольку, помногу, помалу, что еще?" - не попадалось. Есть примеры?

**Comment by asheimovich** [comment]
И если загонять буду я, то проверить, как будут порождены эти формы - орфографию.

**Comment by adybo** [comment]
Пока нет, но во всех Тю яз так! Надо поискать.

**Comment by veramal** [comment]
Аль, ну вот этот топик про распределительные. Вы собирались их все в словарь, а их столько же, сколько зын от числительных. (Там корней-то всего штук 20).

**Comment by asheimovich** [comment]
20 конечно же можно загнать в словарь.

**Comment by veramal** [comment]
Добавила.
