### ISSUE TITLE
пызо vs государство

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#36]
В хакасских словах конечное О считается долгой гласной и не подвергается стяжению (напр., с дативом: пызоға). В русских словах c конечным О бывает по-разному: **_министерствоға** тоғырланып_ 'противясь министерству' (газеты), **_государстваа_** 'государству', _Чииттернiң **творчестваа** тартылчатханы улуғ._ 'Тяга молодежи к творчеству велика.' (грамматика), _Анзы **производстваа** улуғ туза ағылӌаң._ 'Это приносило большую пользу в производстве. ' (газеты). 

Стяженные формы сейчас не разбираются. Внесла вышесказанное в описание сандхи в дативе.
Заимствования ищутся пометой russ в словаре.

**Comment by tuffnatty** [comment]
сделал. "государство" в словаре отсутствует, но там есть такой NOMEN с пометой rus: "заочно". Теперь оно восстанавливается и из заочноға, и из заочнаа.
