### ISSUE TITLE
полдылар, ползалар

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#39]
Сейчас PredPl не разбирается в сочетании с RPast и Cond, хотя ограничений нет.

**Comment by tuffnatty** [comment]
> 12. Непосредственно после показателя недавно прошедшего времени (RPast) может следовать только краткий лично-числовой показатель (Person) или показатель аффирматива (Affirm);

**Comment by tuffnatty** [comment]
> 13. Непосредственно после показателя условного наклонения (Cond) может следовать только краткий лично-числовой показатель (Person);

**Comment by veramal** [comment]
Добавила условия на PredPl в 12 и 13.

**Comment by tuffnatty** [comment]
Исправил.
