### ISSUE TITLE
ÿреен - стяжения гласных

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#4]
ÿреен - должен быть вариант ӱре+past, не должно быть ӱре+conv2+temp, как сейчас

**Comment by adybo** [comment]
Никак такой формы не может быть. Показатель Conv2 -A, как и показатель Fut -Aр, после морфемы, оканчивающейся на гласную, должны давать стяжение с предыдущей гласной в виде -и, -ир. Но я почему-то не нахожу, где у нас про это записано.

**Comment by adybo** [comment]
Аня, я пока не въехала, как отвечать на конкретную реплику. но у меня уже есть просьба:
если вдруг сразу не находишь, где какое-то правило записано, сразу не надо писать новое (во избежание дублей с вариантами). Сначала давай сообща искать.
Конечно, ты м.б. уже нашла. Я вообще пишу.

20.12.2015, 02:49, "Anna Dybo" <adybo@mail.ru>:

**Comment by adybo** [comment]
Не, пока не нашла и вообще, побужденная Моникой, к завтре перевожу, дописывая, летний доклад про заимствования в среднетюркском на англ. Но локально я с вами.

**Comment by veramal** [comment]
Видимо, нигде - формы будущего от основ на гласную тоже не разбираются. Например, санир - нет разбора, д.быть сана+ар.

Про Form 2 вижу правило 6: "Непосредственно после показателя позиции 6 Form2 А может следовать только показатель Iter дIр." Правильная формулировка: "Непосредственно после показателя позиции 6 Form2 А должен следовать показатель Iter дIр или показатель Irr чых."

**Comment by asheimovich** [comment]
Вера, хочу сказать об устройстве правил. Правила сандхи надо искать не там, где лежит, к примеру, правило 6 - правило сочетаемости. Сандхи (часть VI) у меня начинаются на с. 35.
Аня, а про стяжение в "и" это не 1.3.3.1.5. ? Это у меня на с. 36
1.3.3.1.5. В глаголах правила слияния с фонетическими преобразованиями для афф. буд. вр. -ар, афф. деепричастий -а и -абас и аффикса формообразования -а.
Афф. -ар/-ер, -а/-е, -абас/-ебес не имеют вариантов, начинающихся на согласную. При присоединении афф. -ар/-ер, -а/-е, -абас/-ебес к основе на гласную происходит стяжение двух кратких гласных в нейтральную и без долготы: узир ‘он будет спать’ < узу-й-ар, санибас ‘считая’ < сана-й-абас, сöлибес ‘говоря’ < сöле-й-ебес, сани ‘считая’ < сана-й-а, тöзи ‘расстилая’ < тöзе-й-е (-й- – исторический).

**Comment by asheimovich** [comment]
Не пойму, отправился ли последний коммент...
Вера, хотела сказать, что правила сандхи не надо искать там, где правила сочетаемости (напр., 6) лежат. Они в части VI.
Аня, а про стяжение в "и" это не 1.3.3.1.5. ?
В глаголах правила слияния с фонетическими преобразованиями для афф. буд. вр. -ар, афф. деепричастий -а и -абас и аффикса формообразования -а.
Афф. -ар/-ер, -а/-е, -абас/-ебес не имеют вариантов, начинающихся на согласную. При присоединении афф. -ар/-ер, -а/-е, -абас/-ебес к основе на гласную происходит стяжение двух кратких гласных в нейтральную и без долготы: узир ‘он будет спать’ < узу-й-ар, санибас ‘считая’ < сана-й-абас, сöлибес ‘говоря’ < сöле-й-ебес, сани ‘считая’ < сана-й-а, тöзи ‘расстилая’ < тöзе-й-е (-й- – исторический).

**Comment by veramal** [comment]
Ясно, я по глоссам искала, поэтому не нашла. Это оно, да. Кажется, все, что написано в части VI, парсером сейчас не учитывается.

**Comment by asheimovich** [comment]
Вот степень реализации этих правил - больное место.

**Comment by veramal** [comment]
А почему?

**Comment by adybo** [comment]
Принято.

Про - Ар точно писала, но могло в процессе потеряться.

**Comment by veramal** [comment]
с сандхами в Past вроде сейчас все ок
