### ISSUE TITLE
дистрибутив -гла

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#41]
турғла - нет разбора, вместо этой формы парсер считает верной турхла
Почему, я не поняла.

**Comment by veramal** [comment]
Поняла. Из-за сочетание зархы (All1-Attr)  К после сонорных (_р,л, м,н_) реализуется в виде _к_, а не в виде _г_.  Но это противоречит тому, что у нас написано в фонетическом разделе (стр.15). По правилам К звонкая после всех звонких, а все встретившиеся на сегодняшний день сочетания зар+хы входят в словарь. (К тому же они еще не сингаомонируют, так что лучше их убрать в словообразование, если честно.)

**Comment by veramal** [comment]
Тут вот надо поменять морфонологию: у К после сонорных (р, л, м, н) должны быть звонкие аллофоны (а сейчас глухие).

**Comment by adybo** [comment]
Согласна


>Понедельник, 23 октября 2017, 15:18 +03:00 от veramal <notifications@github.com>:
>
>Тут вот надо поменять морфонологию: у К после сонорных (р, л, м, н) должны быть звонкие аллофоны (а сейчас глухие).
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Ну так на самом деле части речи нет, под частью речи понимается компот из грамматического класса леммы и семантики, частично влияющей на частотность синтаксического поведения леммы


>Понедельник, 23 октября 2017, 18:21 +03:00 от Vera Maltseva <malt.wh@gmail.com>:
>
>Конечно. Но надо ее отобразить, желательно отдельно от других характеристик.
>
>23 октября 2017 г., 17:18 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>Часть речи - характеристика леммы.
>>
>>
>>>Понедельник, 23 октября 2017, 16:27 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>
>>>
>>>Нет, задать запрос в поисковик. 
>>>Ну вот, допустим, есть поле "лемма", есть "грамматические характеристики". А как выбрать часть речи, если она в семантике? Это пользователю неудобно, надо, чтобы части речи были под рукой.
>>>
>>>
>>>Без вирусов.  www.avast.ru
>>>
>>>23 октября 2017 г., 16:14 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>В смысле, в тексте? Обращается к словарю и выдает все формы от лексем, которые содержат количтество в семтеге
>>>>
>>>>
>>>>>Понедельник, 23 октября 2017, 16:02 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>>>
>>>>>
>>>>>Нет, чтобы можно было в поисковике легко решить задачу "найти все числительные".
>>>>>
>>>>>23 октября 2017 г., 15:58 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>>>Отсортируй по значению подстроки поля
>>>>>>
>>>>>>
>>>>>>>Понедельник, 23 октября 2017, 15:35 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>>>>>
>>>>>>>
>>>>>>>Я не против семантики в целом. Но она же будет вываливаться вся целиком, а надо, чтобы части речи можно было отдельно посмотреть - как в рускорпоре. 
>>>>>>>
>>>>>>>
>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>
>>>>>>>23 октября 2017 г., 15:30 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>>>>>Да зачем новое поле? И числительные, и местоимения - безусловно имена. Помета - в семантике. У признаковых слов помета - в семантике. Прогнать все "прилагательные" словаря на способность работать вершиной NP без и с изафетом - дело будующего, если кто прогонит, можно будет выделить новое поле под синтаксис.
>>>>>>>>
>>>>>>>>
>>>>>>>>>Понедельник, 23 октября 2017, 15:17 +03:00 от Шеймович Александра < asheimovich@yandex.ru >:
>>>>>>>>>
>>>>>>>>>
>>>>>>>>>Новое поле? Голосование? :)
>>>>>>>>>
>>>>>>>>>
>>>>>>>>>23.10.2017, 15:14, "Vera Maltseva" < malt.wh@gmail.com >:
>>>>>>>>>>Да, с числительными вот фигово. Часть из них существительные, часть прилагательные, часть неизменяемые - а хочется, чтобы пользователь нашел все пометы про числительные в одном месте. Местоимения так же.
>>>>>>>>>>
>>>>>>>>>>
>>>>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>>>>
>>>>>>>>>>23 октября 2017 г., 14:53 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>>>>>>>>Я ж говорю, есть части и части.
>>>>>>>>>>>
>>>>>>>>>>>
>>>>>>>>>>>>Понедельник, 23 октября 2017, 14:47 +03:00 от Шеймович Александра < asheimovich@yandex.ru >:
>>>>>>>>>>>>
>>>>>>>>>>>>
>>>>>>>>>>>>Я полностью за то, чтобы части речи в Part
>>>>>>>>>>>>Список содран с ruscorpora. Систематически к хак. словарю не применялся. Вот на самом деле файл со всеми на данный момент нашими семтагами, сделан из рускорпоры и из Крылова. Этот список фигурировал в статье. После звездочек - уже мои записки для памяти.
>>>>>>>>>>>>Аня уже наверняка захочет переписать :)
>>>>>>>>>>>>
>>>>>>>>>>>>
>>>>>>>>>>>>23.10.2017, 14:40, "Vera Maltseva" < malt.wh@gmail.com >:
>>>>>>>>>>>>>Да, но вроде части речи решили все же в part сейчас. Но это полезный список все равно, спасибо.
>>>>>>>>>>>>>
>>>>>>>>>>>>>
>>>>>>>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>>>>>>>
>>>>>>>>>>>>>23 октября 2017 г., 14:36 пользователь Шеймович Александра  < asheimovich@yandex.ru > написал:
>>>>>>>>>>>>>>Числительные и местоимения (и междометия) позиционировали, а прилагательные - нет. Есть семтаг  qual ( Качество ), он без всякого разделителя употребляется. А вообще у нас текст про семтакги. Который, конечно, уже можно переписывать.
>>>>>>>>>>>>>> 
>>>>>>>>>>>>>>ГРАММАТИЧЕСКИЕ ПРИЗНАКИ
>>>>>>>>>>>>>>Часть речи
>>>>>>>>>>>>>>*  Числительные  num
>>>>>>>>>>>>>>1. количественные  num  ⊃ card
>>>>>>>>>>>>>>2. порядковые  num ⊃ ord
>>>>>>>>>>>>>>3. собирательные  num ⊃ collect
>>>>>>>>>>>>>>*  pron
>>>>>>>>>>>>>>1. личные  pron ⊃ pers (я, он)
>>>>>>>>>>>>>>2. возвратные  pron ⊃ ref (себя)
>>>>>>>>>>>>>>3. притяжательные  pron ⊃ poss (мой, его, свой)
>>>>>>>>>>>>>>4. вопросительные/относительные  pron ⊃ rel (кто, который, когда)
>>>>>>>>>>>>>>5. указательные  pron  ⊃ dem (этот, такой)
>>>>>>>>>>>>>>6. неопределенные  pron ⊃ indet (некоторый, некогда)
>>>>>>>>>>>>>>7. отрицательные  pron ⊃ neg (никакой, ничей)
>>>>>>>>>>>>>>8. кванторные (определительные)  pron ⊃ spec (всякий, каждый, любой)
>>>>>>>>>>>>>>*  Postpos
>>>>>>>>>>>>>>*  Conj
>>>>>>>>>>>>>>*  частица  Ptcl (в поле перевода –  Ptcl )
>>>>>>>>>>>>>>вопросительные частица Qpart (в поле перевода –  Interrog )
>>>>>>>>>>>>>>подтвердительные частица Confpart (в поле перевода – Confpart)
>>>>>>>>>>>>>>возвратные частица Reflpart
>>>>>>>>>>>>>>уподобительная частица Equpart
>>>>>>>>>>>>>>уступительная частица Concpart
>>>>>>>>>>>>>>модальные частицы Mpart
>>>>>>>>>>>>>>усилительно-выделительная частица Emph (в поле перевода –  Magn )
>>>>>>>>>>>>>>*  Neg
>>>>>>>>>>>>>>*  Interj
>>>>>>>>>>>>>>Это все семтаг
>>>>>>>>>>>>>> 
>>>>>>>>>>>>>>
>>>>>>>>>>>>>>
>>>>>>>>>>>>>>23.10.2017, 10:11, "Anna Dybo" < adybo@mail.ru >:
>>>>>>>>>>>>>>>Я думаю, что это семтеги, во всяком случае мы так это позиционировали, для семантич. классов (местоимения, числительные, прилагательные), а для синтаксических, т.е. не по частотности, а по управлению - это союзы и послелоги - в уточнения в поле о частеречной принадлежности.
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>Воскресенье, 22 октября 2017, 23:18 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>А это верно, что у нас семтеги сплошняком сделаны только для буквы А?
>>>>>>>>>>>>>>>>Хочу зафигачить куда-нибудь при каждом слове указание на словарные части речи, как то: числительные, местоимения, междометия, частицы - сплошняком. И в глобальной перспективе хорошо бы прилагательные, которые не существительные, тоже пометить. Это все лучше в семтаги  или завести отдельное поле?
>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>-- 
>>>>>>>>>>>>>>>Anna Dybo
>>>>>>>>>>>>>
>>>>>>>>>>>
>>>>>>>>>>>
>>>>>>>>>>>-- 
>>>>>>>>>>>Anna Dybo
>>>>>>>>>>
>>>>>>>>
>>>>>>>>
>>>>>>>>-- 
>>>>>>>>Anna Dybo
>>>>>>>
>>>>>>
>>>>>>
>>>>>>-- 
>>>>>>Anna Dybo
>>>>>
>>>>
>>>>
>>>>-- 
>>>>Anna Dybo
>>>
>>
>>
>>-- 
>>Anna Dybo
>


-- 
Anna Dybo

**Comment by adybo** [comment]
Словарную помету в ХРС увидеть несложно, парсер ее и сейчас выкидывает при слове; Вера хочет, чтобы пометы обозначали не грам. класс, а тот компот, который принято писать.


>Понедельник, 23 октября 2017, 19:23 +03:00 от Шеймович Александра <asheimovich@yandex.ru>:
>
>Я так понимаю, речь идет не о том, что на самом деле под ней понимается (это мы можем сделать, как считаем нужным), а как увидеть словарную помету, приписанную в ХРС?
>
>
>23.10.2017, 19:18, "Anna Dybo" < adybo@mail.ru >: 
>>Ну так на самом деле части речи нет, под частью речи понимается компот из грамматического класса леммы и семантики, частично влияющей на частотность синтаксического поведения леммы
>>
>>
>>>Понедельник, 23 октября 2017, 18:21 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>
>>>Конечно. Но надо ее отобразить, желательно отдельно от других характеристик.
>>>
>>>23 октября 2017 г., 17:18 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>Часть речи - характеристика леммы.
>>>>
>>>>
>>>>>Понедельник, 23 октября 2017, 16:27 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>>>
>>>>>
>>>>>Нет, задать запрос в поисковик. 
>>>>>Ну вот, допустим, есть поле "лемма", есть "грамматические характеристики". А как выбрать часть речи, если она в семантике? Это пользователю неудобно, надо, чтобы части речи были под рукой.
>>>>>
>>>>>
>>>>>Без вирусов.  www.avast.ru
>>>>>
>>>>>23 октября 2017 г., 16:14 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>>>В смысле, в тексте? Обращается к словарю и выдает все формы от лексем, которые содержат количтество в семтеге
>>>>>>
>>>>>>
>>>>>>>Понедельник, 23 октября 2017, 16:02 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>>>>>
>>>>>>>
>>>>>>>Нет, чтобы можно было в поисковике легко решить задачу "найти все числительные".
>>>>>>>
>>>>>>>23 октября 2017 г., 15:58 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>>>>>Отсортируй по значению подстроки поля
>>>>>>>>
>>>>>>>>
>>>>>>>>>Понедельник, 23 октября 2017, 15:35 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>>>>>>>
>>>>>>>>>
>>>>>>>>>Я не против семантики в целом. Но она же будет вываливаться вся целиком, а надо, чтобы части речи можно было отдельно посмотреть - как в рускорпоре. 
>>>>>>>>>
>>>>>>>>>
>>>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>>>
>>>>>>>>>23 октября 2017 г., 15:30 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>>>>>>>Да зачем новое поле? И числительные, и местоимения - безусловно имена. Помета - в семантике. У признаковых слов помета - в семантике. Прогнать все "прилагательные" словаря на способность работать вершиной NP без и с изафетом - дело будующего, если кто прогонит, можно будет выделить новое поле под синтаксис.
>>>>>>>>>>
>>>>>>>>>>
>>>>>>>>>>>Понедельник, 23 октября 2017, 15:17 +03:00 от Шеймович Александра < asheimovich@yandex.ru >:
>>>>>>>>>>>
>>>>>>>>>>>
>>>>>>>>>>>Новое поле? Голосование? :)
>>>>>>>>>>>
>>>>>>>>>>>
>>>>>>>>>>>23.10.2017, 15:14, "Vera Maltseva" < malt.wh@gmail.com >:
>>>>>>>>>>>>Да, с числительными вот фигово. Часть из них существительные, часть прилагательные, часть неизменяемые - а хочется, чтобы пользователь нашел все пометы про числительные в одном месте. Местоимения так же.
>>>>>>>>>>>>
>>>>>>>>>>>>
>>>>>>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>>>>>>
>>>>>>>>>>>>23 октября 2017 г., 14:53 пользователь Anna Dybo  < adybo@mail.ru > написал:
>>>>>>>>>>>>>Я ж говорю, есть части и части.
>>>>>>>>>>>>>
>>>>>>>>>>>>>
>>>>>>>>>>>>>>Понедельник, 23 октября 2017, 14:47 +03:00 от Шеймович Александра < asheimovich@yandex.ru >:
>>>>>>>>>>>>>>
>>>>>>>>>>>>>>
>>>>>>>>>>>>>>Я полностью за то, чтобы части речи в Part
>>>>>>>>>>>>>>Список содран с ruscorpora. Систематически к хак. словарю не применялся. Вот на самом деле файл со всеми на данный момент нашими семтагами, сделан из рускорпоры и из Крылова. Этот список фигурировал в статье. После звездочек - уже мои записки для памяти.
>>>>>>>>>>>>>>Аня уже наверняка захочет переписать :)
>>>>>>>>>>>>>>
>>>>>>>>>>>>>>
>>>>>>>>>>>>>>23.10.2017, 14:40, "Vera Maltseva" < malt.wh@gmail.com >:
>>>>>>>>>>>>>>>Да, но вроде части речи решили все же в part сейчас. Но это полезный список все равно, спасибо.
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>23 октября 2017 г., 14:36 пользователь Шеймович Александра  < asheimovich@yandex.ru > написал:
>>>>>>>>>>>>>>>>Числительные и местоимения (и междометия) позиционировали, а прилагательные - нет. Есть семтаг  qual ( Качество ), он без всякого разделителя употребляется. А вообще у нас текст про семтакги. Который, конечно, уже можно переписывать.
>>>>>>>>>>>>>>>> 
>>>>>>>>>>>>>>>>ГРАММАТИЧЕСКИЕ ПРИЗНАКИ
>>>>>>>>>>>>>>>>Часть речи
>>>>>>>>>>>>>>>>*  Числительные  num
>>>>>>>>>>>>>>>>1. количественные  num  ⊃ card
>>>>>>>>>>>>>>>>2. порядковые  num ⊃ ord
>>>>>>>>>>>>>>>>3. собирательные  num ⊃ collect
>>>>>>>>>>>>>>>>*  pron
>>>>>>>>>>>>>>>>1. личные  pron ⊃ pers (я, он)
>>>>>>>>>>>>>>>>2. возвратные  pron ⊃ ref (себя)
>>>>>>>>>>>>>>>>3. притяжательные  pron ⊃ poss (мой, его, свой)
>>>>>>>>>>>>>>>>4. вопросительные/относительные  pron ⊃ rel (кто, который, когда)
>>>>>>>>>>>>>>>>5. указательные  pron  ⊃ dem (этот, такой)
>>>>>>>>>>>>>>>>6. неопределенные  pron ⊃ indet (некоторый, некогда)
>>>>>>>>>>>>>>>>7. отрицательные  pron ⊃ neg (никакой, ничей)
>>>>>>>>>>>>>>>>8. кванторные (определительные)  pron ⊃ spec (всякий, каждый, любой)
>>>>>>>>>>>>>>>>*  Postpos
>>>>>>>>>>>>>>>>*  Conj
>>>>>>>>>>>>>>>>*  частица  Ptcl (в поле перевода –  Ptcl )
>>>>>>>>>>>>>>>>вопросительные частица Qpart (в поле перевода –  Interrog )
>>>>>>>>>>>>>>>>подтвердительные частица Confpart (в поле перевода – Confpart)
>>>>>>>>>>>>>>>>возвратные частица Reflpart
>>>>>>>>>>>>>>>>уподобительная частица Equpart
>>>>>>>>>>>>>>>>уступительная частица Concpart
>>>>>>>>>>>>>>>>модальные частицы Mpart
>>>>>>>>>>>>>>>>усилительно-выделительная частица Emph (в поле перевода –  Magn )
>>>>>>>>>>>>>>>>*  Neg
>>>>>>>>>>>>>>>>*  Interj
>>>>>>>>>>>>>>>>Это все семтаг
>>>>>>>>>>>>>>>> 
>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>23.10.2017, 10:11, "Anna Dybo" < adybo@mail.ru >:
>>>>>>>>>>>>>>>>>Я думаю, что это семтеги, во всяком случае мы так это позиционировали, для семантич. классов (местоимения, числительные, прилагательные), а для синтаксических, т.е. не по частотности, а по управлению - это союзы и послелоги - в уточнения в поле о частеречной принадлежности.
>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>Воскресенье, 22 октября 2017, 23:18 +03:00 от Vera Maltseva < malt.wh@gmail.com >:
>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>А это верно, что у нас семтеги сплошняком сделаны только для буквы А?
>>>>>>>>>>>>>>>>>>Хочу зафигачить куда-нибудь при каждом слове указание на словарные части речи, как то: числительные, местоимения, междометия, частицы - сплошняком. И в глобальной перспективе хорошо бы прилагательные, которые не существительные, тоже пометить. Это все лучше в семтаги  или завести отдельное поле?
>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>Без вирусов.  www.avast.ru
>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>-- 
>>>>>>>>>>>>>>>>>Anna Dybo
>>>>>>>>>>>>>>>
>>>>>>>>>>>>>
>>>>>>>>>>>>>
>>>>>>>>>>>>>-- 
>>>>>>>>>>>>>Anna Dybo
>>>>>>>>>>>>
>>>>>>>>>>
>>>>>>>>>>
>>>>>>>>>>-- 
>>>>>>>>>>Anna Dybo
>>>>>>>>>
>>>>>>>>
>>>>>>>>
>>>>>>>>-- 
>>>>>>>>Anna Dybo
>>>>>>>
>>>>>>
>>>>>>
>>>>>>-- 
>>>>>>Anna Dybo
>>>>>
>>>>
>>>>
>>>>-- 
>>>>Anna Dybo
>>>
>>
>>
>>-- 
>>Anna Dybo


-- 
Anna Dybo

**Comment by tuffnatty** [comment]
Починил
