### ISSUE TITLE
не работает запрет Neg+Neg.Fut

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#42]
харбир имеет разбор 
харарға ‛стареть’ хар
------ба-ар---------------
------Neg-Fut₂---------------

А почему Fut2? Вроде в схеме одно будущее (неотрицательное).

**Comment by tuffnatty** [comment]
Fut2 - потому что есть Fut1 а и Fut2 ар, так уж реализованы конечные в скобках.
В чем состоит проблема, не понял - Neg.Fut в разборе нет, ограничение 11 не нарушено.

**Comment by veramal** [comment]
Да, тут просто Neg+Fut. Это мы еще не запрещали. Написала новое ограничение 10.1.

**Comment by tuffnatty** [comment]
реализовал, но есть замечания (в документе)
