### ISSUE TITLE
буква ё

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#44]
Видимо, нужна буква Ё. В библии Пётр пишется строго через Ё - не потому, что это текст для слабочитающих, а потому что ё дает задний ряд: _Пётрға_. Писалось бы Петр, ожидалось бы _Петрге_.

**Comment by adybo** [comment]
Да, кстати!

**Comment by asheimovich** [comment]
Где нужна ё?
В словаре проставлена вроде. Наверное, не очень последовательно. Но в текстах ее все равно почти нигде нет.

**Comment by veramal** [comment]
В коде парсера - сейчас нет символа. В словарь не нужно, думаю.

**Comment by veramal** [comment]
О, в словаре есть слово _жонглёр_. Пусть парсер его узнаёт.

**Comment by tuffnatty** [comment]
Добавил.
