### ISSUE TITLE
еще из особенностей русских заимствований

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#46]
Есть некоторые заимствованные слова с двумя Н в конце - например, "финн". Если действовать по правилам, то в генитиве, аблативе и творительном у них должно быть три Н подряд. Но на самом деле третья Н опускается, и пишется "финнiң", "финнең".
(Прототипом тут послужил Иоанн, но его нет в словаре. Впрочем, если в будущем научиться отделять окончания в незнакомых словах, то этот момент тоже стоит учесть.)

**Comment by veramal** [comment]
финнең - нет разбора

**Comment by tuffnatty** [comment]
надо бы это в документе описать

**Comment by veramal** [comment]
Дописала в сандхи (стр. 53 внизу).

**Comment by tuffnatty** [comment]
Сделал, теперь ватты разбирается и как ватт+ты, и как ватт+ы
