### ISSUE TITLE
интервокальное неозвончение Т

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#47]
Есть ряд глаголов, в которых Т остается глухим в интервокальной позиции.
АТАРҒА  - стрелять, ПАТАРҒА - вязнуть, ХАТАРҒА - 1) засыхать 2) скручивать, УТАРҒА - выигрывать

Сейчас парсер эти формы не разбирает.

**Comment by adybo** [comment]
@asheimovich Аля! Как только словарь попадет к тебе в руки, найди, пож., все инфинитивы на -тарга, - терге и поставь им в поле form, что ли, помету, что т не озвончается в интервокале. И сообщи Филу, как ты пометила.

**Comment by asheimovich** [comment]
а если он на -РТАРҒА и тп.? Можно не помечать? 
А это точно для всех?

**Comment by asheimovich** [comment]
Но пусть сперва попадет

**Comment by veramal** [comment]
-РТАРҒА помечать не надо, только интервокальные

**Comment by adybo** [comment]
На рт можно не помечать. Для всезх ли - ну, инфинитив как раз интервокал, так что если там озвончается, то наверное и везде

**Comment by tuffnatty** [comment]
А это только с глаголами происходит? Тогда помета не нужна, эту информацию можно вычислить автоматически из инфинитива и основы

**Comment by adybo** [comment]
Да, вроде у имен автоматично озвончается, я расписывала (унифицировалось)

**Comment by veramal** [comment]
У имен есть проблема с заводом  и пр. заимствованиями - но там, наоборот, нужно оглушение не в интервокале, а перед морфами на согласный.

**Comment by asheimovich** [comment]
я бы искала эти глаголы по контекстам "VАРҒА" или "Vт-/" в поле Field1
Если этого достаточно, то и пометы, правда, не надо.

**Comment by adybo** [comment]
Да, про поведение завода и проч. текст в принципе написан, и помета о заимствовании стоит в словаре

**Comment by tuffnatty** [comment]
Исправил

**Comment by veramal** [comment]
Тут надо все-таки изобрести помету, т.к.
1) не все глаголы с конечным Т не озвончаются: _атарга_, но _чадарга_
2) бывают и имена. правда, кроме хат 'баба' я ничего не знаю

**Comment by adybo** [comment]
Я про это написала в тексте и в словаре даем пометки.

**Comment by veramal** [comment]
В тексте мы с Филом не нашли, но я дописала.
В словаре помет сейчас нет. Как и где пометим?

**Comment by veramal** [comment]
приписала неозвончающимся основам на Т помету unvoiced
заимствованиям не прописывала

**Comment by tuffnatty** [comment]
Задействовал в парсере помету вместо автоопределения.
