### ISSUE TITLE
не выполняется запрет на слияние при долгих

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#48]
ниик
n ниң ‛самый’
----------------------ӧк
----------------------Ass

и долгое, ӧ долгое - ң не должно выпадать

**Comment by adybo** [comment]
Оно может думать, что и не долгое (потому что само по себе и первого слога - не блокирует выпадение). Но ок должен блокировать, да

**Comment by veramal** [comment]
В первом слоге даже с краткими ох не сливается.

**Comment by tuffnatty** [comment]
Там есть фраза:
>В односложных основах правило действует и на долгие, и на краткие гласные. 
Надо это как-то уточнить.

**Comment by adybo** [comment]
Не понимаю, какое правило

**Comment by tuffnatty** [comment]
ну вот если в гуглдоке нажать ctrl-f и скопипастить

    В односложных основах правило действует и на долгие, и на краткие гласные

то оно найдется, это описание правил выпадения интервокального Г, а про ң написано:
>Правила выпадения согласного основы такие же, как у морфонемы Г

**Comment by adybo** [comment]
Это замечание - В односложных основах правило действует и на долгие, и на краткие гласные - бессмысленное: кто-то не подумал, что гласные о, о умлаут, и  - считаются фонологически долгими только для непервых слогов. В первом слоге фонологическая оппозиция по долготе не работает.

>Воскресенье, 22 октября 2017, 18:16 +03:00 от Phil Krylov <notifications@github.com>:
>
>ну вот если в гуглдоке нажать ctrl-f и скопипастить
>В односложных основах правило действует и на долгие, и на краткие гласные
>
>то оно найдется, это описание правил выпадения интервокального Г, а про ң написано:
>>Правила выпадения согласного основы такие же, как у морфонемы Г
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Не, тот кто писал, был нормальный - в первом слоге бывает и аа, и ее. Тут почему-то общая часть о том, что выпадения не бывает ПЕРЕД долгими, осталась в тени. Дописала, чтобы было почетче.

**Comment by adybo** [comment]
Бывает ли в первом слоге ААГ? 


>Воскресенье, 22 октября 2017, 19:13 +03:00 от veramal <notifications@github.com>:
>
>Не, тот кто писал, был нормальный - в первом слоге бывает и аа, и ее. Тут почему-то общая часть о том, что выпадения не бывает ПЕРЕД долгими, осталась в тени. Дописала, чтобы было почетче.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Вообще мне сейчас, после упорядочения таких же правил для тувинского, эта часть дико не нравится, хочу переписать.


>Воскресенье, 22 октября 2017, 19:13 +03:00 от veramal <notifications@github.com>:
>
>Не, тот кто писал, был нормальный - в первом слоге бывает и аа, и ее. Тут почему-то общая часть о том, что выпадения не бывает ПЕРЕД долгими, осталась в тени. Дописала, чтобы было почетче.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Нет, ААГ не бывает в однослоге. Бывает ли АА в словаре в однослоге? Да, бывает: наа новый, паа цена, саа усики колоса, чаа лук, хызыл хаа какой-то куст, чаа война, кее каприз, тее тот, частицы и суппл. словоформы не считаем. Зуб даю, что при них следующее г не выпадает. В общем, странная формулировка.


>Воскресенье, 22 октября 2017, 19:13 +03:00 от veramal <notifications@github.com>:
>
>Не, тот кто писал, был нормальный - в первом слоге бывает и аа, и ее. Тут почему-то общая часть о том, что выпадения не бывает ПЕРЕД долгими, осталась в тени. Дописала, чтобы было почетче.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
А как ты ищещь, есть ли ааг? У меня проблема со вставкой спецсимволов в строку поиска.

Формулировка да, запутанная. Можно написать "выпадение Г происходит только между двумя краткими гласными", а потом объяснять, какие из них краткие, а какие долгие.

**Comment by adybo** [comment]
Выпадение Г в интервокальной позиции не происходит, если перед ним стоит долгая гласная, написанная двумя буквами, и это первый слог. Выпадение Г в интервокальной позиции не происходит, если перед ним  или после него стоит долгая гласная, и это не-первый слог.
В общем, дня через 2 дойду до этого места, отточу.
Вот, кстати, кому интересно, для тувинского

г перечеркнутое есть в слове в примере в 1й статье.


>Воскресенье, 22 октября 2017, 20:08 +03:00 от veramal <notifications@github.com>:
>
>А как ты ищещь, есть ли ааг? У меня проблема со вставкой спецсимволов в строку поиска.
>Формулировка да, запутанная. Можно написать "выпадение Г происходит только между двумя краткими гласными", а потом объяснять, какие из них краткие, а какие долгие.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Ну да, а долгая гласная  - это 1) гласная, записанная двумя буквами в любом слоге или 2) о,ё,и в непервом слоге, причем о - скорее в незаимствованных словах (см. топик  пызо vs государство).
 
Кроме того, если основа состоит из двух букв типа VГ, то это Г также не выпадает.

**Comment by asheimovich** [comment]
Это о чем: "г перечеркнутое есть в слове в примере в 1й статье." ?22.10.2017, 22:07, "adybo" <notifications@github.com>:Выпадение Г в интервокальной позиции не происходит, если перед ним стоит долгая гласная, написанная двумя буквами, и это первый слог. Выпадение Г в интервокальной позиции не происходит, если перед ним  или после него стоит долгая гласная, и это не-первый слог.
В общем, дня через 2 дойду до этого места, отточу.
Вот, кстати, кому интересно, для тувинского

г перечеркнутое есть в слове в примере в 1й статье.


>Воскресенье, 22 октября 2017, 20:08 +03:00 от veramal <notifications@github.com>:
>
>А как ты ищещь, есть ли ааг? У меня проблема со вставкой спецсимволов в строку поиска.
>Формулировка да, запутанная. Можно написать "выпадение Г происходит только между двумя краткими гласными", а потом объяснять, какие из них краткие, а какие долгие.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Да, это уже там все записано.


>Воскресенье, 22 октября 2017, 22:50 +03:00 от veramal <notifications@github.com>:
>
>Ну да, а долгая гласная  - это 1) гласная, записанная двумя буквами в любом слоге или 2) о,ё,и в непервом слоге, причем о - скорее в незаимствованных словах (см. топик  пызо vs государство).
>Кроме того, если основа состоит из двух букв типа VГ, то это Г также не выпадает.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Это о Верином вопросе, как я в старлинговском словаре ищу АГ


>Воскресенье, 22 октября 2017, 23:39 +03:00 от asheimovich <notifications@github.com>:
>
>Это о чем: "г перечеркнутое есть в слове в примере в 1й статье." ?22.10.2017, 22:07, "adybo" < notifications@github.com >:Выпадение Г в интервокальной позиции не происходит, если перед ним стоит долгая гласная, написанная двумя буквами, и это первый слог. Выпадение Г в интервокальной позиции не происходит, если перед ним  или после него стоит долгая гласная, и это не-первый слог.
>В общем, дня через 2 дойду до этого места, отточу.
>Вот, кстати, кому интересно, для тувинского
>
>г перечеркнутое есть в слове в примере в 1й статье.
>
>
>>Воскресенье, 22 октября 2017, 20:08 +03:00 от veramal < notifications@github.com >:
>>
>>А как ты ищещь, есть ли ааг? У меня проблема со вставкой спецсимволов в строку поиска.
>>Формулировка да, запутанная. Можно написать "выпадение Г происходит только между двумя краткими гласными", а потом объяснять, какие из них краткие, а какие долгие.
>>—
>>You are receiving this because you commented.
>>Reply to this email directly,  view it on GitHub , or  mute the thread .
>
>
>-- 
>Anna Dybo
>
>
>—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
А в чем тут сейчас grammar bug? Описание я отредактровала.

**Comment by tuffnatty** [comment]
Ну, в парсере я поправил, чтобы справа была всегда краткая. Но в документе все очень запутано, и висят еще комментарии справа, ощущение такое, как будто окончательные формулировки еще не готовы.

**Comment by veramal** [comment]
Сейчас ошибка не повторяется.
