### ISSUE TITLE
новая морфема: симулятив

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#49]
Все-таки -ачых 'делающий вид' не раскладывается на СоnvA+ЧIК из-за морфонологии. Во-первых, у ЧIК во всех прочих сочетаниях Ч озвончается в интервокале, а здесь нет. Во-вторых, просто СonvA имеет отрицание -бин, а здесь будет -баачых. Согласны, что ее стоит отдельно завести?

**Comment by adybo** [comment]
А это вообще словоизменение?

**Comment by veramal** [comment]
Ну конечно - отрицание-то перед ним, и вполне продуктивно.

**Comment by veramal** [comment]
Вот такие формы попались в Библии:
_Сірер кізілер алнында арығ чӱректіг **полаачыхтанчазар**_  - вы выказываете себя праведниками пред людьми.
_Андағ сын нимес илҷілер чой тоғынҷылар, Христостың илҷілері **полаачыхтанчалар**._ - Ибо таковые лжеапостолы, лукавые делатели, принимают вид Апостолов Христовых.
_Худайға тудынаачыхтанарлар_ - будут иметь вид благочестия

Ну то есть типа да, словообразование. А отрицание есть в словообразовательной разметке? Если нету, то лучше все же считать СИ (все-таки ), отрицание вполне композиционально.

**Comment by adybo** [comment]
Ой. А это вообще как устроено? пол- становиться - а?-ачых Симул -та- Опер -н Рефл -ча През-зар 2 pl

тут держать - ын Рефл -а? -ачых Симул -та- Опер-н Рефл -ар Фут - лар Пред Плюр ?

Понедельник,  3 апреля 2017, 13:01 +03:00 от veramal <notifications@github.com>:

**Comment by veramal** [comment]
Ну да. Действительно, обычно долгое аа/ее пишут, только в грамматике одно: 
...пазох **талачых** полыбысхан.	...снова сделала вид, что теряет сознание. (ПЧ)

А вот наоборот, вербализаторы перед ачыхом:
Мині тик ле **улуғлаачых** полчалар
но тщетно чтут Меня (НЗ)

піс **хармахтаачых** полыбызарға чаратхабыс. (Ребята с нашего двора)

**Comment by adybo** [comment]
Ох. Вставлять после чыха вербализатор что ли???

**Comment by adybo** [comment]
хармахтаачых как раз более понятно - том можно думать, что одно а из ЛА-, а второе из ачых

**Comment by veramal** [comment]
Ну, не совсем: при обычном способе было было хармахтичых. Но ичых никогда не бывает - видимо, потому что долгое (ну и я ее слышала - долгая без сомнений, ударение притягивает). Еще встречается форма _пазыраачых_. А грамматика часто считает, что в непервом слоге долгое не на стыке писать некомильфо (ну если это не минимальная пара только, типа _хара - хараа, сала - салаа_). 

Да нет, можно все в словарь загнать, раз уж у нас там все залоги сидят. Вот только тогда придется держать отрицание среди СО. Но можно обойтись малой кровью - записать в словарь только _полаачыхтан_ и _тудынаачыхтан_.

**Comment by veramal** [comment]
Еще могло по аналогии с прилагательными на -_аачы_ перевестись в долгое. В словаре Субраковой почему-то нет ни аффикса, ни слов с ним, хотя в Баскакове некоторые слова есть (но только с отрицанием).

**Comment by adybo** [comment]
ичых было бы, если бы это было деепр + чых, а вроде как нет

**Comment by veramal** [comment]
По морфонологии а+а дает и, за исключением вот этого и императива еще (там тоже долгое по факту).

**Comment by adybo** [comment]
Кстати, да!

**Comment by adybo** [comment]
Это мы так написали, потому что у нас практически все аффиксы на -а на самом деле из *ja-, и они так стягиваются за счет этого j.

**Comment by veramal** [comment]
Ну это были не совсем мы. а Баскаков и Ко)

**Comment by adybo** [comment]
у них-то и морфонем не было

**Comment by veramal** [comment]
Все-таки тут не решили, что делать с симулятивами, образованными от глаголов с отрицанием. Судя по тем словам, для которых выписано словообразование, от отрицательных форм больше ничто не образуется.

**Comment by veramal** [comment]
Решили все-таки сделать морфему Simul ААчЫК (симулятив) в позиции 7. Вроде бы отдельных правил ей не нужно, т.к. эта форма не спрягается, а вот склоняется ли, мы не знаем. Про то, что она съедает гласную перед собой, дописала в сандхи для аффиксов (II.2, стр. 53 внизу).

Словарь тоже считает, что это причастие. Вот из статьи про глагол пол 'быть':
"11) с прич. на ӌых/-ӌік основного глагола выступает в роли вспомогат. глагола со знач. «притворяться»: кӧрбеечік поларға притворяться невидящим (незамечающим); тоғынаачых поларға притворяться работающим;"

**Comment by adybo** [comment]
Надо у Карпова поглядеть, может он уже выделил как приччастие

**Comment by veramal** [comment]
Вряд ли Карпов что-то новое добавит.

9 декабря 2017 г., 1:08 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Нет, у него кой-чего было
