### ISSUE TITLE
ағырап - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#5]
д.б. ағыра+conv1.

Сюда же: форма ағыра имеет вариант разбора ағыра-form2, Это неправильно, после form2 могут следовать только iter и irr.

**Comment by adybo** [comment]
Или конец словоформы

**Comment by veramal** [comment]
вообще-то здесь опечатка, основа ағыр, а не ағыра. так что разбора с деепричастием нет закономерно, но и с form2 надо убить. form2 не может быть на конце словоформы - только conv2 (с ним разбор тоже есть)

**Comment by adybo** [comment]
А, да, правда, не форм.

**Comment by tuffnatty** [comment]
не вижу такого правила про form2. Либо надо уточнить правило 6 Непосредственно после показателя позиции 6 Form2 А может следовать только показатель Iter дIр.

**Comment by adybo** [comment]
Какого правила ты не видишь про форм2? про опущение? У форм 2 не бывает опущения, это только у -п.

**Comment by veramal** [comment]
Фил прав - нет правила. Должно быть примерно так: "Все показатели позиций 2,3,5 (Form1, Form2 и Ptcl1), а также Prosp из позиции 4 не могут стоять у правой границы словоформы".

**Comment by adybo** [comment]
Принято

**Comment by veramal** [comment]
исчезло
