### ISSUE TITLE
новое в морфологии: ох перед PredPl

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#50]
Вот такой пример попался:
_Хай пірее одыртхан ағастар **парохтар** мында_
несколько посаженный деревья имеется здесь
Здесь имеется и несколько посаженных деревьев.

Меняю правило 21 про PredPl, чтобы частица ох могла стоять перед ним.

**Comment by tuffnatty** [comment]
прокомментировал эту правку

**Comment by tuffnatty** [comment]
исправилось

**Comment by veramal** [comment]
Сейчас парохтар опять не работает.
В глаголах так же: парарохтар - нет разбора.
