### ISSUE TITLE
о показателе -тын

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#51]
Сейчас у нас не разбираются формы типа столзартын 'со стороны стола'.
Тын назван Adv2 и записан как ТIн. Но в реальности он, кажется, бывает только после аллатива (современного или древнего: _андартын, чогартын, тискертiн_) и всегда глухой. Не лучше ли написать его тIн в таком случае?
И для ясности не лучше ли его переименовать в Abl2?

**Comment by adybo** [comment]
Согласна про аблатив!

**Comment by asheimovich** [comment]
Это что же будет еще одна позиция для падежа???

**Comment by veramal** [comment]
Нет, зачем, пусть остается на своем месте. Ну или можно переместить в Case2, а зар брать из Case1.
Про тIн вместо ТIн все согласны?

**Comment by adybo** [comment]
Аль, у нас есть эти 2 позиции для падежа

**Comment by adybo** [comment]
Я согласна

**Comment by asheimovich** [comment]
конечно пусть

**Comment by veramal** [comment]
Обозвала Abl2, написала ограничение 30 про него. Оставила на текущей позиции (среди наречий), ему там хорошо. Из ограничения 18 его можно, в принципе, убрать.

**Comment by adybo** [comment]
Давайте в Case 2 посадим

**Comment by asheimovich** [comment]
А давайте его все-таки в Case2!?

**Comment by veramal** [comment]
Да, давайте, логика требует. Тогда у нас в адвербиальной позиции останется только _ли_ (_зын_ упало, _тын_ пропало). Перекрою на днях, ждите.

**Comment by veramal** [comment]
Теперь бывший Adv2 ТIн из поз. 19 стал Abl2 тIн из поз. 18. Ограничение 18 теперь касается только Adv Ли, а про Abl2 тIн написано новое ограничение 30. Можно менять в парсере, чтобы заработал _столзартын_.

**Comment by tuffnatty** [comment]
Если столзартын - это All1, то нарушается ограничение 16, если All2 - то Abl2 в той же позиции невозможно

**Comment by veramal** [comment]
Да, это All1, дописала в 16.

**Comment by adybo** [comment]
Пипл, я же предложила в блоге написать кумулятивный показатель All1.Abl в позиции 2го падежа и не держать в позиции второго падежа двусмысленных нумерочков при названиях падежей.


>Понедельник, 23 октября 2017, 19:23 +03:00 от Phil Krylov <notifications@github.com>:
>
>Closed  #51 .
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Да, только не сказала, кто это должен делать.
