### ISSUE TITLE
ограничение на падежи в предикатах

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#52]
кірізінзер - один из разборов такой:

n кіріс ‛вход’
----------------і--н--зер--
----------------3pos--Acc₂--2pl--

Эльвира считает, что предикатами могут быть только локатив, аблатив и датив. Я бы не стала отсекать возможность аллатива и пролатива (т.к. у него может быть еще сравнительное значение), но вот аккузатив, генитив и творительный надо точно запретить. Написала новое ограничение.

**Comment by adybo** [comment]
А ты уверена, что генетив в посессивном смысле невозможен как предикат? 
типа "эти куры - соседские"

**Comment by veramal** [comment]
"эти куры - соседские" будут с Apos (хончахти). Генитив не умеет быть вершиной кроме как в случае с пістіңнер.

**Comment by adybo** [comment]
Т.е. эти куры - наши - все-таки пістіңнер? Т.е. можно сказать, что это так для личных местоимений?

**Comment by veramal** [comment]
Нет, "эти куры - наши" тоже пiсти. Вот таким макаром он может только стать предикатом, по ГХЯ:

Ол кізі пістіңнердең ме? — Я, пістіңнердең.	
Тот (этот) человек из наших? — Да, из наших.

**Comment by adybo** [comment]
Да,  но тут, конечно, лар не предикативный. Значит не бывает. А писти, кстати, лар может получить?

**Comment by veramal** [comment]
Тут лар не предикативный, но сама форма _пістіңнердең_ - безусловно, предикат.

Пiсти может получить падеж, посессивный лар будет перед Apos, а предикативный лар он не очень любит. Ср.: 

Аның туйғахтары пістің **малларнинаң** пасха. 
Его копыта отличаются от копыт нашего скота. 

**Пістин**, **сірернин** паза **оларнин** пӱӱн не ағылғаннар.
Нашу, вашу и их принесли только сегодня.

На предикативный лар при -ни один пример нашелся:
Чир-чалбахтағы нимелер... Пабадаң ниместер, че **чир-чалбахтилар**.
Ибо всё, что в мире... не есть от Отца, но от мира сего. (Новый завет)

**Comment by adybo** [comment]
Погоди, вот здесь
Аның туйғахтары пістің малларнинаң пасха.
ты про что?

**Comment by veramal** [comment]
Про то, что лар перед ни бывает. А то было непонятно, какой лар тебе нужен - справа или слева. А вот чтобы был актант типа пiстилер - не попадалось пока (видимо, пістіңнер в этой роли).

**Comment by veramal** [comment]
О, еще один пример с предикатом-Apos, с неожиданным ходом мысли:
Часкалығлар Хан Худайны киректепчеткеннер, олар Тигір хан-чирінилер!
Блаженны нищие духом, ибо их есть Царство Небесное.

Т.е. не царство - ихнее, а они, наоборот, царству принадлежат.

**Comment by adybo** [comment]
О, хороший тоже пример

**Comment by adybo** [comment]
Да нет, слева-то понятно, мы же про предикатный вроде лар говорили.

**Comment by veramal** [comment]
Кстати говоря, предикатный-то лар тоже не работает. Сейчас вынесу в  отдельный топик.

**Comment by tuffnatty** [comment]
добавил ограничение.
