### ISSUE TITLE
субстантивация в виде Pl и Pos

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#53]
_**Пістіңнер** андағ оғырластарны уйады чохтарға санаҷаң полтырлар._
**Наши** такое воровство считали бессовестным. (Газеты)

_Ол ӧрiн парған осхас ууӌаның **ибдезiне**._
Она, видно, обрадовалась тому, что бабушка дома. (Чебодаева)

Сейчас -нер трактуется только как PredPl, но при таком раскладе _пістіңнер_ не может быть подлежащим (а когда мы запретим предикат от генитива, то перестанет разбираться). _ибдезiне_ не разбирается, а там должно быть так: 
иб-де-зi-не
дом-Loc-Pos-Dat

Еще бывает двойной посессив, даже не только в местоимениях:
_ээ-зi-м_ 'мой хозяин'- повсеместно вместо _ээм_. Но если тут можно обойтись новым входом в словарь, то вот тут вряд ли:
_**чӱс-паз-ы-лар-ы-ның** ікізін позынзар хығыртыбызып_
сто-голова-3pos-pl-3pos-gen
призвав двух сотников (Новый завет)

Сейчас _пазылары_ трактуется только как Fut  от _пазыл_.

В общем, надо уметь все эти случаи тоже разбирать.

**Comment by adybo** [comment]
По-моему, это у нас не предикативный, а просто второй Pl,  а генетив - первый.

Да, оно должно научиться разбираться с двумя наборами именных слотов, которые именно для таких случаев и делались.

**Comment by veramal** [comment]
По смыслу второй Pl, конечно, по факту пока запрещен.

**Comment by veramal** [comment]
Расширила ограничение 16.

**Comment by veramal** [comment]
Дополнение насчет двойного посессива: слова с неотчуждаемой принадлежностью и с меной основы при посессиве только так и могут породить 3pl.pos: _хыриларында_ - около них, _орнылары_ - их места. (Сейчас первая форма разбирается за счет того, что хыри есть в словаре, вторая - нет.) В теории, конечно, здесь гласная перед -лар - это в синхронии уже часть основы, но парсировать удобнее, выделяя посессивный показатель.

**Comment by adybo** [comment]
да

**Comment by veramal** [comment]
_пістіңнер, ибдезiне_ - разборы появились
с принадлежностью пока проблемы остаются: _орнылары_ не разбирается.

В копилку - встретился аллатив от _пістің_ в грамматике:
Улуғ полған прай чаалар ундул парған, ӱлгӱ кӱзі **пістіңзер** айлан парған. - Все большие сражения позабыты теперь, сила власти оказалась у нас (повернулась к нам). (А. Топанов)

**Comment by adybo** [comment]
К нашим!


>Суббота, 11 ноября 2017, 22:01 +03:00 от veramal <notifications@github.com>:
>
>пістіңнер, ибдезiне - разборы появились
>с принадлежностью пока проблемы остаются:  орнылары не разбирается.
>В копилку - встретился аллатив от  пістің в грамматике:
>Улуғ полған прай чаалар ундул парған, ӱлгӱ кӱзі  пістіңзер айлан парған. - Все большие сражения позабыты теперь, сила власти оказалась у нас (повернулась к нам). (А. Топанов)
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by tuffnatty** [comment]
орнылары заработало. Можно закрывать?

**Comment by veramal** [comment]
Да, вроде все работает.
