### ISSUE TITLE
Apos+PredPl

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#54]
Еще одна мелкая недоработка в ограничениях на PredPl - ему может предшествовать Apos из поз. 17:

_Часкалығлар Хан Худайны киректепчеткеннер, олар Тигір хан-**чирінилер**!_
Блаженны нищие духом, ибо их есть Царство Небесное.

_Чир-чалбахтағы нимелер... Пабадаң ниместер, че чир-**чалбахтилар**._
Ибо всё, что в мире... не есть от Отца, но от мира сего. (Новый завет)

Исправила ограничение 21.

**Comment by veramal** [comment]
При переезде бывшего Apos, ныне Gen.3pos к остальным посессивам должно автоматически разрешиться. Но оставлю пока, чтобы не забылось.

**Comment by tuffnatty** [comment]
Исправил
