### ISSUE TITLE
лишнее под атрибутивом

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#55]
Хараағызы - неверные разборы:

n хараң ‛недошедшая шкура’
------------ы--хы--зы------
------------3pos--Attr--3pos------

n хараң ‛недошедшая шкура’
-------------а-хы--зы------
-------------Dat-Attr--3pos------

Все-таки внутреннего датива не бывает. По крайней мере, в корпусе нет ни одного примера (были только с хараа 'ночь', но это не датив, а номинатив на самом деле). Так что убрала датив из Case1 (и добавила, наоборот, генитив для пiстiңнер).
А посессив внутренний бывает только в связке с падежом (Case1) или числом (Pl2). Написала новое ограничение.

**Comment by tuffnatty** [comment]
исправил
