### ISSUE TITLE
еще один способ написать 3pos

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#56]
В двусложных словах с АК на конце при присоединении посессива некоторые авторы пишут ААКI, а не АКI. Сейчас есть пара таких примеров из Ай-Хуучина и десяток из Чебодаевой.

_Ікі **хараағы** пір дее чоғыл._ - Оба глаза ее ничего не видят. (Ай-Хуучин) 
_ол **араағы** чирі_ – то место. (непонятное слово, но модель та же) (Ай-Хуучин) 
_Ағбанның нымзах, истіг **хуҷаағына** позын тиксі пирібіскен_. - отдала себя полностью в легкое, приятное объятье Абакана. (_хуҷах_ – охапка) (Чебодаева) 
_Истіг, йа, хызым, Ағбанның **идеегінде** чазырхирға._ - Хорошо, да, доченька, ласкаться в объятьях Абакана. (_идек_ - подол) (Чебодаева) 
_Майраның **чÿреегі**, сабылып, чалбыри тÿскен._ - сердце Майры забилось, загорелось. (Чебодаева) 
_**чÿреегің**, тізең, аарлалча, чахсы нимее азылча._ - сердце же (твое) очищается, открывается доброму. (Чебодаева) 
_**Чӱреегім** ағырыбохча, тас нимес._ - Мое сердце тоже болит, не камень. (Чебодаева)

**Comment by adybo** [comment]
Черт-те что. Ай-хуучин - кызыльский, но Чебодаева - сагайская националистка.

**Comment by veramal** [comment]
Довольно много таких случаев непоследовательной орфографии, за всеми не уследишь.
