### ISSUE TITLE
посессивный датив типа -мга

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#57]
А некоторые не стягивают датив, по шорской норме. В ГХЯ есть такое:

Партия **чолынға** часхабысха удур ойлапчабыс.	- По пути, указанному партией, идем навстречу своему счастью. (Н. Доможаков)

Хакастар **ыр-сарынға** хаҷан-пуруннаң сабылған чон. - Хакасы с древних времен любят песню. 

Молҷаан **кӱнінге** килерлер. - К условленному дню приедут.

Надо нам сделать такой вариант.

**Comment by adybo** [comment]
Да!

**Comment by veramal** [comment]
В 1 лице тоже:
**Пабамға** сана иттірткем. - Мой отец сделал лыжи (по моей просьбе).

**Comment by adybo** [comment]
В смысле? Вроде так и должен -м-га?

**Comment by veramal** [comment]
Нет, в лит.норме -ма.

**Comment by adybo** [comment]
Доможаков:
 В 1949 году он успешно защитил кандидатскую диссертацию «Кызыльский диалект хакасского языка». 
А из кого про лыжи?

**Comment by veramal** [comment]
Из авторов грамматики.

**Comment by veramal** [comment]
сынымға - это сюда
Аар **сынымға** кӱс хосчатхан - Тяжелому телу моему (в смысле, которому тяжело двигаться, см. примеры в словаре) силу добавляющий (М. Кильчичаков)

**Comment by adybo** [comment]
А чирдерче?


>Вторник, 24 октября 2017, 22:57 +03:00 от veramal <notifications@github.com>:
>
>сынымға - это сюда
>Аар  сынымға кӱс хосчатхан - Тяжелому телу моему (в смысле, которому тяжело двигаться, см. примеры в словаре) силу добавляющий (М. Кильчичаков)
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Опечатка.

**Comment by veramal** [comment]
И еще пример нашелся:
Пу апсах читон **пизінге** читіре пір дее ағырбаан полтыр. - Этот старик до семидесяти пяти лет ни разу не болел, оказывается.

**Comment by adybo** [comment]
От чслительного, да


>Суббота,  2 декабря 2017, 0:02 +03:00 от veramal <notifications@github.com>:
>
>И еще пример нашелся:
>Пу апсах читон  пизінге читіре пір дее ағырбаан полтыр. - Этот старик до семидесяти пяти лет ни разу не болел, оказывается.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Сами формы не очень частотны, но попадаются и вне шорского диалекта. Как бы не забыть скинуть сюда пример, когда будет под руками.

**Comment by veramal** [comment]
Бутрахты:
А пазох Тувадағы **харындазымға** хада пір ящик алчам. - А снова в Туве живущему брату вместе один ящик беру. 
**Похоронкамға** чыып салам, ладно. - На похоронку свою соберу, ладно.

**Comment by veramal** [comment]
Казановка:
Ну все равно пирер **туңмаларынға**. 
Все равно даст младшим детям в семье.

**Comment by adybo** [comment]
А что бы мы хотели?


>Четверг,  8 февраля 2018, 23:02 +03:00 от veramal <notifications@github.com>:
>
>Бутрахты:
>А пазох Тувадағы  харындазымға хада пір ящик алчам. - А снова в Туве живущему брату вместе один ящик беру.
>Похоронкамға чыып салам, ладно. - На похоронку свою соберу, ладно.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by adybo** [comment]
Это его детям. А что, там хорошо слышно нга, а не нхвоста?


>Четверг,  8 февраля 2018, 23:08 +03:00 от veramal <notifications@github.com>:
>
>Казановка:
>Ну все равно пирер  туңмаларынға .
>Все равно даст младшим детям в семье.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Хотели бы узаконить нестяженный вариант посессивного датива в парсере.
Н-хвоста там по смыслу не может быть, т.к. 3 лицо. Слышно не 100%, но скорее туңмаларынга, чем туңмаларына. Для Казановки нехарактерная форма, конечно, но в Бутрахтах это норма, и слышно вполне.

**Comment by veramal** [comment]
Реализовано через диалектное окончание (н)ГА. Но передний ряд не работает:  _чолынға_  разбирается, _кӱнінге_  - нет.

**Comment by tuffnatty** [comment]
кӱнінге починил
