### ISSUE TITLE
сiрерди: диалектные варианты окончаний

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#59]
В Ай-Хуучине вот такая форма Apos встретилась:

Алдағызы Сірерди ползын! - Будущее да будет Вашим! 
Чолдағызы Сірерди ползын! - Дорога пусть будет Вашей!

Видимо, пока в словарь.

**Comment by adybo** [comment]
Ух ты

**Comment by veramal** [comment]
Ну, вполне ожидаемо, что д-формы вместо н-форм будут проскакивать, но что уже в эпосе, я не думала.

**Comment by veramal** [comment]
А кстати говоря, почему у нас вообще Apos называется так, а не Gen.3pos? Типичная склееная морфема же. Если бы писалась с долгим И, то вообще шла бы по морфонологическим правилам.

**Comment by adybo** [comment]
вообще-то нехорошо чтобы  падеж стоял перед принадлежностью - или это падеж 1 и принадлежность2?

**Comment by veramal** [comment]
Ну конечно, это субстантивация типа ибдезi - до меня только сегодня дошло, на Катиной защите.

**Comment by adybo** [comment]
Ага!  Эта штука ведь и в тувинском есть.

**Comment by tuffnatty** [comment]
См. #102
