### ISSUE TITLE
уғаа - неправильная морфонология

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#6]
много неправильных разборов вида ух/уғ+а+ғы
однако у atr ғ никогда не выпадает, после звонкой согласной и после гласной одинаковые варианты

**Comment by adybo** [comment]
Не должно; но имеется ряд примеров в словаре, когда х все-таки выпадает, поэтому в правилах выпадения после таблиц написана возможность споррадического выпадения. Может быть, это диалектное.

**Comment by veramal** [comment]
а какие примеры конкретно с этим аффиксом? его же не опознаешь, если там согласная выпадет, а гласная ассимилирует

**Comment by adybo** [comment]
С этим конкретно не было, но вот что было:

1.3.3.2. 1.2.  Выпадение конечных заднеязычных глухих в основах на  -х, -к . Это происходит в  многосложных (!) основах в интервокальной позиции и сопровождается последующим стяжением двух обрамлявших его гласных в одну долгую (см. правило 2.2) [не всегда]. Многосложная основа на  -х, -к +  -ы, -i либо теряет указанную конечную согласную и образуется долгая  аа, ее, ии ( ии – если гласная основы была узкой  ы, и, i, у, ӱ ), либо указанная конечная согласная озвончается в  ғ, г и сохраняется:  харах ‘глаз’ +  -ым > хараам / харағым ‘мой глаз’,  хузух ‘орех’ +  -ым > хузиим / хузуғым ‘мой орех’;  iзiк ‘дверь’ +  ым > iзиим / iзiгiм ‘моя дверь’,  пöрiк ‘шапка’ +  -iм > пöриим / пöрiгiм ‘моя шапка’. Формально это те случаи, когда в словаре в поле ALTERNATEN выписана альтернативная запись основы, оканчивающаяся на  -ғ или  -г , а в поле FORM – словоформа на  -ии . Но, поскольку все означенное это точно старый глухой, то нет никаких гарантий, что и с другим старым глухим такого не случится; альтернативное г мы проставили в словаре тем словам, которые реально встретились со стяжением

**Comment by veramal** [comment]
В твоем правиле речь идет о тех случаях, где стык морфем проходит между х/к и ы/i. В суффиксе  -ғы между ними нет границы, поэтому такое правило действовать не должно.

**Comment by adybo** [comment]
А, ты про -г- в гы. Надо его перезвать в кы, и все.

**Comment by veramal** [comment]
сейчас такого нет
