### ISSUE TITLE
-зын и числительные

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#60]
У наречного -зын  на самом деле довольно ограниченая дистрибуция: он присоединяется к некоторому закрытому списку существительных (сезоны, день-ночь, коп, первый-последний - и кажется, все) и ко всем порядковым числительным. Существительные все есть в словаре, а вот числительные от существительных мы не отделяем - поэтому парсер сейчас слова типа "тӧртінҷізін" не разбирает.
Поэтому напрашивается два предложения:
1) разрешить числительным присоединять свой набор СИ-морфем (у них есть и другие - например, разделительные числительные уже где-то обсуждались, а число они присоединять не могут вроде бы)
или 
2) выкинуть -зын из словоформы и загнать все в словарь. Тогда у нас вся специфическая морфология числительных будет СО.

**Comment by asheimovich** [comment]
как все порядковые загонишь в словарь?

**Comment by adybo** [comment]
Братцы, а зачем нам вообще этот адвербиал? Это же просто винительный падеж 3го лица, что плохого, если он будет так разбираться? Он, кстати, именно так рассматривается в ГХЯ в разделе об употреблении вин. пад. в синтаксисе

**Comment by veramal** [comment]
Ань, давай только не все сначала. Это, как ты сама верно говорила, старый инструменталь -н, который теперь стал скорее темпоралом с ограниченными возможностями. Он при этом совпадает с посессивным аккузативом по форме, но не по семантике. Ср.: 
хысхызын - 1 ) зимой (зима=Adv) 2) его зиму (зима-3pos.acc); 1
пастагызын - 1) во-первых (первый=Adv, 2) (вижу из них) первого / того, что во главе (первый-3pos.Acc / голова=Loc=Attr-3pos.Acc)
задачазын - 'его задачу' (задача-3pos.acc), *'задачей, во время задачи'.

Я согласна, что его надо убрать из СИ, но в СО надо оставить с адвербиальным значением.

**Comment by veramal** [comment]
Вычеркнула из словоформы, сделала заметку в файле про словарь

**Comment by adybo** [comment]
Ну вот то, что он стал - он изменил свою сущность реально. Во всех языках, где это древний инструментал - турецкий, древнетюркский и все прочие - он не лепится на форму принадлежности. То, что он в хак. лепится на принадлежность, указывает, что он этим и стал. Почему аккузатив не может значить "во время" - по-моему, ничто не говорит. Семантика аккузатива, конечно, не бывает, иначе почему в др-рус аккузатив работает и прямым доп., и целью движения. Омонимия, которую ты приводишь в пример - вполне возможная многозначность (ср. для рус. инструменталя клянусь зимой).

**Comment by veramal** [comment]
Ты меня сама когда-то убеждала, что это инструментал, и жил он под вывеской Temp.

**Comment by veramal** [comment]
Ну и факт тот, что в темпоральном значении он лексически ограничен.

**Comment by asheimovich** [comment]
А, ну да, вот меня все время смутные воспоминания тревожили. Это ж наш Темп! Ну так все равно в падежах жил. И переселили его от плохой жизни: тогда у нас не было двух позиций для падежей, а теперь есть. Можно обратно в Темпы. Но вроде не очень надо.

**Comment by adybo** [comment]
Да я же говорю. Там исторически был инструментал (под вывеской Temp). Но лично хакасы заменили его на омонимичный, если бы не аффикс принадлежности, аккузатив. И тогда я то же говорила. Ты мне доказала (и я проверила по словарю), что он всегда с принадлежностью (я думала, что нет, потому что в других бывает и без принадлежности, а тогда это не аккузатив, потому что для аккузатива это спецфич. форма при принадлежности)

**Comment by adybo** [comment]
Ну да, не надо, потому что это норм. акк.

**Comment by asheimovich** [comment]
Норм. акк, Но зовется abl?

**Comment by adybo** [comment]
А вот и нет

**Comment by adybo** [comment]
Ну, т.е. ограничен названиями процессов

**Comment by asheimovich** [comment]
Для памяти смотрю файл 14 года: Temp был (I)н. Acc посессивный при этом был Н(I). Стояли они в одной позиции.

**Comment by adybo** [comment]
Это про зын, а не про дын

**Comment by asheimovich** [comment]
ой, пардон, попутала... Это все Temp...

**Comment by veramal** [comment]
Судя по парсеру, Adv1 зын убран. А будет ли он отображаться в словообразовании - уже другой вопрос.
