### ISSUE TITLE
дистрибуция Dur1

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#62]
Dur1 ир/и встречается также с деепричастием на -п и с условным наклонением:

_Учух **париза** — з-з-з — сыылапча, чирге тӱссе — чир хасча._
Летит — ж-ж-ж — жужжит, спустится — землю копает. (загадка, ГХЯ) 

_Левит тее iдӧк, хыринҷа ирт **парирып**, чағын пазып, кӧрiп алып, iдӧк чӧре халған._
Также и левит, бывший на том месте, подошел, посмотрел и прошел мимо. (Библия)

Дописала нужное в ограничение 8.

**Comment by adybo** [comment]
А раньше не встречался? Вроде он должен встречаться везде, где и Dur?

**Comment by veramal** [comment]
1) Когда встретился, тогда и заметили. ГХЯ не заметила, хотя примеры в ней есть. 2) т.к. он редок, ничего нельзя сказать точно.

**Comment by tuffnatty** [comment]
Исправил
