### ISSUE TITLE
парыбох

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#63]
В ограничении 25 было написано, что после деепричастий ничего не бывает. На самом деле после них, конечно. бывает -ох, как и везде. Исправила в тексте.

**Comment by adybo** [comment]
Да, да! А не бывает ли фокусной частицы?

**Comment by veramal** [comment]
Не исключаю, но пока не видела. Описание допускает.

**Comment by veramal** [comment]
Нет, все же -птыр - это только Indir. Если встретится такой пример, где это фокус, тогда разрешим, а пока лучше запретить.

**Comment by adybo** [comment]
Т.е. пока не встретилось. А там еще какие-то деепричастия есть, которые окаменелые падежи от причастий, может, они с фокусом бывают?

**Comment by veramal** [comment]
Может, и есть, пока в фокус лезть не хочется прицельно.

**Comment by tuffnatty** [comment]
парыбох заработал
