### ISSUE TITLE
adv

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#64]
Почему-то оставшийся Adv не работает.
_Ай-Хуучин **пастаанни** ах ибге кіргеннер._ - по примеру Ай-Хуучин в белый дом вошли.

Есть разбор только через аппозитив, но по значению это явно наречие. 
Не вижу, где затык, возможно, ограничение 18 не до конца воплощено.

**Comment by tuffnatty** [comment]
Противоречит ограничению 27.

**Comment by veramal** [comment]
Поправила в 27.

**Comment by tuffnatty** [comment]
Прошу вынести Ass2 из правила 27 в отдельное правило. Тогда 27 будет рассматривать целые слоты и останется глобальным, а новое правило - только конкретную морфему Ass2, и его можно будет прицепить конкретно к ней, а мне - не заводить для Ass2 новый флажок, поле флагов не вылезет из 32 бит, и можно будет еще какое-то время потерпеть с 32.

**Comment by veramal** [comment]
Ок, перенесла в 24.

9 апреля 2017 г., 12:46 пользователь Phil Krylov <notifications@github.com>
написал:

**Comment by tuffnatty** [comment]
Уточнил формулировку правила 24, реализовал, у _пастаанни_ появилось два новых разбораю

**Comment by adybo** [comment]
А какие? Это должно быть от "начинать" + -ган (причастие) и либо Gen.3Pers, т.е. субстантивированное начатое/начавшее, либо "имея отношение к началу", т.е. те же и Adv

**Comment by tuffnatty** [comment]
v пастирға ‛приступать’ паста
-------ған---------ни-----
-------Past₂---------Gen.3pos-----
v пастирға ‛приступать’ паста
-------ған-----------ни---
-------Past₂-----------Adv---
n пастағ ‛начинание’
----------------ы-н-ни---
----------------3pos-Acc₂-Adv---

**Comment by adybo** [comment]
Норм, пусть будет )


>Воскресенье, 22 октября 2017, 18:08 +03:00 от Phil Krylov <notifications@github.com>:
>
>v пастирға ‛приступать’ паста
>-------ған---------ни-----
>-------Past₂---------Gen.3pos-----
>v пастирға ‛приступать’ паста
>-------ған-----------ни---
>-------Past₂-----------Adv---
>n пастағ ‛начинание’
>----------------ы-н-ни---
>----------------3pos-Acc₂-Adv---
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Не, вот это неправильный:
n пастағ ‛начинание’
----------------ы-н-ни---
----------------3pos-Acc₂-Adv---

Адвербиальный показатель не может цепляться ко всем падежам. По крайней мере, к аккузативу не может. Но про это надо посмотреть у Эльвиры.

**Comment by adybo** [comment]
У Эльвиры только после нулевого падежа, но это же в сравн. конструкции только, там по ролям по-другому не выйдет 


>Воскресенье, 22 октября 2017, 19:02 +03:00 от veramal <notifications@github.com>:
>
>Не, вот это неправильный:
>n пастағ ‛начинание’
>----------------ы-н-ни---
>----------------3pos-Acc₂-Adv---
>Адвербиальный показатель не может цепляться ко всем падежам. По крайней мере, к аккузативу не может. Но про это надо посмотреть у Эльвиры.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo
