### ISSUE TITLE
Лыг - только при имени

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#65]
алғастығ - сейчас два разбора:

v алғазарға ‛благословлять друг друга’ алғас
---------тығ-------------
---------Comit-------------
n алғас ‛благословение’
---------тығ-------------
---------Comit-------------

Первый разбор неверен, т.к. Comit может присоединяться только к именным основам. Почему-то этот факт не нашел отражения в описании, добавила условие в ограничение 1.

**Comment by adybo** [comment]
К причастиям-то может

**Comment by veramal** [comment]
Пока не найдено.

**Comment by adybo** [comment]
тайға суу ағыннығ таёжная река стремительна.
сірер аллығ істіліг, кізее чуғаннығ кізізер

**Comment by tuffnatty** [comment]
Внес изменение в реализацию ограничения 1; причастия надо тоже отразить

**Comment by veramal** [comment]
Ань, не вижу причастий: ағын - течение, аллығ - широкий (от ал - передняя часть? но не  от 'брать' точно), істі - внутренности, чуған - толстый.

**Comment by adybo** [comment]
Верно говоришь, а мне надо раньше спать ложиться! Но вот в карачаевском есть специальное глаг. время, которое из -ар + лыг

**Comment by adybo** [comment]
Все же я переправила, перенесла в правило выбора 2 (лучше из общетюркологических соображений)
