### ISSUE TITLE
посессивные предикаты

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#66]
Не все анализы проходят:
хызымзың - есть разборы с "совой" и "девушкой", хызымнар, хызыңбын - нет
хызыбыстар - очень странный разбор выползает, без лексемы:
----ыбыс----------------тар-
----Perf----------------PredPl-

**Comment by tuffnatty** [comment]
@veramal хызымнар, хызыбыстар починил.
хызыңбын - какой должен быть разбор?

**Comment by veramal** [comment]
Никакого, я ошиблась, правильная форма хызыңмын, и у нее сейчас правильные разборы.
