### ISSUE TITLE
чадыр + личные

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#68]
хатхырчадыр - ок, хатхырчадырбын - нет разбора
В ограничении 20 не было прописано сочетание Dur.Iter с личными окончаниями, дописала. Он сочетается с полными формами.

**Comment by tuffnatty** [comment]
Добавил.

**Comment by adybo** [comment]
Дорогие коллеги, пожалуйста, срочно впишите в блог Хакасская_морфология_приложения все, что вы там меняете или же спустите мне список изменений другим путем - пишу срочно главу в казанскую коллективную монографию с описанием парсера.

(это, увы, полезно, потому что тюркские коллеги не понимают, как устроена морфология)

**Comment by adybo** [comment]
Я сначала изменяю там, потом пишу об изменениях сюда (если это явный баг, а
не вопрос для обсуждения).
Кстати, все незакрытые темы здесь по-прежнему актуальны.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

22 октября 2017 г., 12:04 пользователь Anna Dybo <adybo@mail.ru> написал:

**Comment by veramal** [comment]
Почему-то предыдущее написалось от имени Ани, это я на самом деле.

**Comment by adybo** [comment]
А как ты сейчас свои изменения помечаешь там?

**Comment by veramal** [comment]
Фиолетовым.
