### ISSUE TITLE
пілӌеең - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#69]
пілӌееңер при этом ок:
v пілерге ‛знать’ піл
-------ӌең---------іңер-----
-------Hab₂---------2pos.pl-

в других случаях 2pos.sg работает:
пілгенің
пілерге ‛знать’ піл
-------ген---------ің-----
-------Past₂---------2pos.sg

**Comment by tuffnatty** [comment]
исправил
