### ISSUE TITLE
добавить в словарь частицы

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#7]
сейчас большая часть энклитик не разбирается. а те, что разбираются, тоже надо редактировать. они сейчас частично nomen, а должны быть все invar

ба, бе, па, пе, ма, ме - вопросительная. пусть перевод будет Q, а не ли, ладно?
даа, дее, таа, тее, маа, мее - EMPH
ла, ле, на, не - DELIM
да, де - INDEF (пишутся через дефис после вопросительных местоимений)
за, зе - просто PART или 'ведь'

**Comment by veramal** [comment]
еще надо добавить пiрее в атрибутивном значении 'какой-то': пiрее ниме - что-то, пiрее чирде - где-то и т.п.
сейчас есть только наречное значение 'иногда / где-то'. они сейчас nomen, но на самом деле они invar

**Comment by adybo** [comment]
Так это частица типа не-, кое-. Так что сохраняем ее как инвар. А значение ей пишем - не Q, а какое-то типа Indef, только такое уже есть у чего-то

**Comment by veramal** [comment]
нет, Ань - чистый indef - это все же энклитика де. а проклитик не бывает ведь - и если мы ей припишем глоссу, то все будут думать, что она относится к предыдущему слову. и бывает не с местоимениями: пiрее чыл - некоторые годы
ну то есть можно так думать философски, что это проклитика, но технически неудобно

**Comment by asheimovich** [comment]
лучше свои пожелания о добавлении новых входов писать в файл. И вообще я мечтаю о времени, когда каждый будет сам добавлять все необходимое, предварительно согласовав этот вопрос. потому что я не успеваю с нужной скоростью. Пока с заменой ьi на ы разбираюсь. пытаюсь выловить латинское I, но это очень трудно из-за смеси латиницы и кириллицы в базе.
Потом nomen-ы лишние буду убивать и invar прописывать.

**Comment by asheimovich** [comment]
И значение Q я не знаю что такое. В semgloss у меня все по-русски, а словообразованием я пока не занимаюсь. И списки сокращений для derivgloss не забываем писать

**Comment by adybo** [comment]
Ну это, конечно, не клитика в том смысле, что не составляет акцентного слова с местоимением. Но ведь частицы-то не обязательно постпозитивные бывают. Вообще эта проблема возникнет только на пути будущего синтаксического анализа, для которого, вероятно, достаточно будет сделать фильтр на эту препозицию. А уж адъективом эта штука ни в каком виде не является. Т.е. это не определение к местоимению, это просто аналитическая лексема, вроде пишущихся отдельно композитов. Если всем потенциальным членам композитов выписывать специальное значение - то это известная проблема теоретической лексикографии, надо ли выписывать слову вода значение дальний родственник. И вроде как все решили, что не надо.

**Comment by veramal** [comment]
Не бывает - это я к тому, что у нас вроде как левое ветвление, без
префиксов. А почему пiр - адъектив, а пiрее - не адъектив?

22 декабря 2015 г., 2:01 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Во-первых адъективов не бывает. Бывает имя. То, что оно имя, значит, что оно может присоединять опр. аффиксы и не может тоже опр. аффиксы. Имя - это помета словаря, т.е. оно при лексеме, а не при словоформе. 
Пирее - это исторически словоформа от пир. Но раз уж она попала в словарь, она застывшая. Как застывшая падежная словоформа, она, скорей всего, не может присоединять никаких аффиксов, так что лексема пирее именем не является, а является неизменяемым.

**Comment by veramal** [comment]
Я имела в виду синтаксическую позицию, потому что как адъюнкт оно и значит
"иногда", как сейчас записнано, а с точки зрения морфологии оно всегда
invar. Но есть же еще неизменяемые, которые могут быть в атрибутивной
позиции - най, например. Они вряд ли все частицы.

22 декабря 2015 г., 2:18 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
А вот еще есть форма пiреезi, значит "кто-то из них". И это уже будет имя с
падежами. На статус самого пiрее это, в общем, не влияет, кроме того
момента, что цеплять посессивность к частице не очень здорово.

22 декабря 2015 г., 12:23 пользователь Vera Maltseva <malt.wh@gmail.com>
написал:

**Comment by adybo** [comment]
А, вот это интереснее. Видимо, доказывает, что пирее  - имя. А то, что это застывший падеж -  не влияет.

**Comment by veramal** [comment]
Да нет, само прее все равно не может присоединить ни падеж, ни
предикативность, так что оно invar.

23 декабря 2015 г., 2:42 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Да, а как будет "кому-то из них"? небось с окончанием дательного падежа. Что значит "само"? Ты дкумаешь, что пиреези не форма от пирее? Почему?

**Comment by veramal** [comment]
кому-то из них - презiна. а вот прееге не будет

23 декабря 2015 г., 13:07 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Нету, потому что показатель актантности для части местоимений и числительных вообще форма принадлежности. Но я думала описывать это в синтаксисе. А не-актант как склонять?

**Comment by veramal** [comment]
Да, но вроде мы когда-то пришли к выводу считать посессивность в данном
случае словообразовательной - потому что. во-первых, нарушаются сандхи как
в пiрсi, хайзы, во-вторых, это не просто актантность, но и одушевленность
(впрочем, тут словари могут и привирать, но пока корпуса нет, проверить
тяжело). А если это СО, то прее и преезi - отдельные входы в словарь. А
прее как отдельный вход м быть только invar.

23 декабря 2015 г., 17:46 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
в словаре парсера пока не все частицы, но это не совсем его баг

**Comment by veramal** [comment]
частицы добавлены, чтобы работали -да\-де, надо обновить словарь (и, возможно, разобраться с дефисами)
