### ISSUE TITLE
Adv -ли не работает

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#71]
аңмарли , ханни, хысти  - нет разбора через adv

**Comment by asheimovich** [comment]
почти нигде нет. Я его сейчас выписываю и поэтому вижу, что везде, где только возможно поставить Gen.3pos, стоит он.11.11.2017, 22:07, "veramal" <notifications@github.com>:аңмарли , ханни, хысти  - нет разбора через adv

**Comment by veramal** [comment]
Ну да. А где нельзя, нет анализа.

11 ноября 2017 г., 22:10 пользователь asheimovich <notifications@github.com>
написал:

**Comment by asheimovich** [comment]
Есть кое-где, я видела несколько. Вот, напр. пазылғанни. Только не знаю, что это на самом деле11.11.2017, 22:20, "veramal" <notifications@github.com>:Ну да. А где нельзя, нет анализа.



11 ноября 2017 г., 22:10 пользователь asheimovich <notifications@github.com>

написал:

**Comment by veramal** [comment]
А, там в ограничении 18 вот что: "При присоединении к чистой основе адвербиализатор считается словообразовательными, см.выше пояснения к глоссам". Надо бы посмотреть частотность, но на первых 9 страницах примеров из грамматики не разобралось 4 раза (впрочем, 2 примера именно про него). А еще есть и примеры, разобранные через субстантивацию. Т.е. это как с диминутивом.

**Comment by adybo** [comment]
Вообще можно, конечно, чык вставить, в древнетюркский-то вставляли. Ща подумаю, куда


>Суббота, 11 ноября 2017, 22:33 +03:00 от veramal <notifications@github.com>:
>
>А, там в ограничении 18 вот что: "При присоединении к чистой основе адвербиализатор считается словообразовательными, см.выше пояснения к глоссам". Надо бы посмотреть частотность, но на первых 9 страницах примеров из грамматики не разобралось 4 раза (впрочем, 2 примера именно про него). А еще есть и примеры, разобранные через субстантивацию. Т.е. это как с диминутивом.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
_Алешаның туңмазы частых алтынаң **тöрткіли** салылған ах ис сығар киліп, Алешаа пирібіскен._ - Младший брат Алеши, вытащив из-под изголовья сложенную вчетверо белую тряпку, отдал Алеше. (ГХЯ)

В этом примере интересно то, что -ли прикрепляется не к порядковому числительному,  а тащит с собой -КЫ, который вообще-то к числительным  не должен присоединяться. Поэтому вряд ли этот пример агитирует за словоизменение, но интересно, что он есть (и что о нем думают носители, сейчас спрошу).

**Comment by veramal** [comment]
Эльвира говорит, что тöрткіли не говорят сейчас, так что можно считать единичным примером.

**Comment by veramal** [comment]
Что-то мы этот вопрос замяли, а надо бы приткнуть все-таки куда-то адвербализатор Ни - причем хорошо бы так, чтобы и причастия на -Ган с ним разбирались, и чистые именные основы. Засунуть в тот же слот, где ЛЫК, вероятно. Вот в живом тексте встретилось из Трошкино:
_Но іди, ибде іди чоохтанып… мин сағынғанда, артых. Аның ӱчӱн не пос **пілгенни**._
Но так, дома так говорить… по моему мнению, лишнее. Поэтому по-своему [так, как сами знаем].

**Comment by adybo** [comment]
Да, а что, его там нету?


>Пятница, 11 января 2019, 0:31 +03:00 от veramal <notifications@github.com>:
>
>Что-то мы этот вопрос замяли, а надо бы приткнуть все-таки куда-то адвербализатор Ни - причем хорошо бы так, чтобы и причастия на -Ган с ним разбирались, и чистые именные основы. Засунуть в тот же слот, где ЛЫК, вероятно. Вот в живом тексте встретилось из Трошкино:
>Но іди, ибде іди чоохтанып… мин сағынғанда, артых. Аның ӱчӱн не пос  пілгенни .
>Но так, дома так говорить… по моему мнению, лишнее. Поэтому по-своему [так, как сами знаем].
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
Еще одна незакрытая рекламация про adv Ли, ушедшая в сторону.

**Comment by veramal** [comment]
Вроде работало в какой-то момент, сейчас не работает.

**Comment by tuffnatty** [comment]
Вроде исправил?

**Comment by veramal** [comment]
Да, вроде работает.

чт, 23 июл. 2020 г. в 14:57, Phil Krylov <notifications@github.com>:
