### ISSUE TITLE
буква -я

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#72]
1. Если русское слово кончается на _я_, то датив должен быть -_а_, потому что последний звук удлиняется: _комиссияа_ (=_комиссийаа_). Сейчас эта форма не разбирается.
А если на _ю_, то стяжения нет: _менюға_ (правда, там должен выбираться задний ряд из-за того, что _ю=йу_, а не _йӱ_, а сейчас выбирается передний, но это другая проблема).

2. В грамматике и некоторых книжках слова, которые в словаре и газете пишутся через _йа_, пишутся через _я: аяс, паяғы_ и т.п. (В словаре _я_, как и _э_, допускается только в начале слова). Если бы парсер автоматически переводил _я_ в _йа_, возможно, и первая проблема отпала бы.

**Comment by adybo** [comment]
Да, та м должно быть написано, что йа = я на самом поверхностном уровне.
Значит, надо писать, что ю, у в русских словах тоже долгие. А кенгуру - кенгуруга?


>Суббота, 11 ноября 2017, 22:19 +03:00 от veramal <notifications@github.com>:
>
>* 
>Если русское слово кончается на  я , то датив должен быть - а , потому что последний звук удлиняется:  комиссияа (= комиссийаа ). Сейчас эта форма не разбирается.
>А если на  ю , то стяжения нет:  менюға (правда, там должен выбираться задний ряд из-за того, что  ю=йу , а не  йӱ , а сейчас выбирается передний, но это другая проблема).
>* 
>В грамматике и некоторых книжках слова, которые в словаре и газете пишутся через  йа , пишутся через  я: аяс, паяғы и т.п. (В словаре  я , как и  э , допускается только в начале слова). Если бы парсер автоматически переводил  я в  йа , возможно, и первая проблема отпала бы.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Не совсем на самом поверхностном, т.к. надо найти в словаре _комиссия_, а не _комиссийа_. Но трактовать его как _комиссийа_.
кенгуруга, да.  
А долгие зачем, для кенгуруох и менюох? Но стягивание с -ох вроде бы опционально у всех.

**Comment by adybo** [comment]
И для кенгуруга. Г не падает после долгого


>Суббота, 11 ноября 2017, 23:29 +03:00 от veramal <notifications@github.com>:
>
>Не совсем на самом поверхностном, т.к. надо найти в словаре  комиссия , а не  комиссийа . Но трактовать его как  комиссийа .
>кенгуруга, да.
>А долгие зачем, для кенгуруох и менюох? Но стягивание с -ох вроде бы опционально у всех.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
кенгуруға сейчас разбирается

**Comment by veramal** [comment]
Впрочем, и кенгураа разбирается. Да пусть его.

**Comment by veramal** [comment]
А тут чего не хватает в грамматике?

**Comment by tuffnatty** [comment]
комиссияа, менюға починил.

**Comment by adybo** [comment]
Описания поведения йотированнных букв; в тексте у меня есть


>Четверг, 30 ноября 2017, 16:47 +03:00 от veramal <notifications@github.com>:
>
>А тут чего не хватает в грамматике?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo
