### ISSUE TITLE
тур и чӧр как именные предикаты

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#74]
Как известно по грамматике, есть глаголы _тур, чӧр_ и _одыр_, которые могут употребляться как именные предикаты, т.е. словоформа "тур" может обозначать настоящее время и присоединять личные показатели. Пока встретились только стечения с PredPl: _турлар, чӧрлер_ (_одырлар_ разбирается, т.к. существует в виде имени 'оказывается'). Про _тур_ и _чӧр_ нужно будет опять же посмотреть, насколько часто они встречаются вне  грамматике.

**Comment by veramal** [comment]
А вот еще сложный случай, геминация корня и омонимичного показателя:
Палыхтың пазы суғ чоғар **чадыр**. - Голова рыбы лежит против течения реки.

**Comment by adybo** [comment]
в смысле, гаплология


>Суббота, 11 ноября 2017, 23:33 +03:00 от veramal <notifications@github.com>:
>
>А вот еще сложный случай, геминация корня и омонимичного показателя:
>Палыхтың пазы суғ чоғар  чадыр . - Голова рыбы лежит против течения реки.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Лицо тоже встретилось:
Ай-ай, хайди аны пілбин **турзың**. - Ай-ай, как тебе не стыдно этого не знать.

**Comment by adybo** [comment]
Ага. Уверена, что эта именная форма - твой неоформленный -ып, иначе глагол именем не сделать (а ып в прошлой жизни причастие, он так функционирует в ДТ и туркменском, напр.)


>Воскресенье, 12 ноября 2017, 12:50 +03:00 от veramal <notifications@github.com>:
>
>Лицо тоже встретилось:
>Ай-ай, хайди аны пілбин  турзың . - Ай-ай, как тебе не стыдно этого не знать.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Ну вот в хакасском это лексикализованная фигня, если верить грамматике.

**Comment by adybo** [comment]
Тогда надо их в словарь загнать как предикатные имена и все дела


>Воскресенье, 12 ноября 2017, 15:51 +03:00 от veramal <notifications@github.com>:
>
>Ну вот в хакасском это лексикализованная фигня, если верить грамматике.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Ввела в словарь.
