### ISSUE TITLE
стяжение условного СА и ОК

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#75]
Почему-то не работает:
парза - ок, парзох - нет разбора
(в других случаях работает)

**Comment by veramal** [comment]
олох - тоже нет разбора через Ass

**Comment by veramal** [comment]
аннаңарох - тоже нет разбора (пардаңарох при этом разбирается как надо, т.е. дело не в аффиксе)

**Comment by adybo** [comment]
Может, глагола в словаре нет?

**Comment by veramal** [comment]
какого глагола, пар? вроде есть :) без -ох все эти штуки разбираются

**Comment by tuffnatty** [comment]
_парзох_ нарушает правило 13. _олох_ - в словаре нет изменяемой основы _ол_. _ аннаңарох_ - в словаре нет изменяемой основы _аннаңар_. Вроде что-то помнится о том, что Ass _ОК_ присоединяется и к неизменяемым, но в документе такого не вижу.

**Comment by asheimovich** [comment]
Есть же в словаре частеречные пометы Invar и Invar1. Последние должны присоединять ох. А прописано ли в документе - не помню :(

**Comment by veramal** [comment]
Дописала Ptcl3 в ограничния 12 и 13. Про Invar1 дописала условие в ограничение 0.

**Comment by tuffnatty** [comment]
Парзох починилось.

**Comment by tuffnatty** [comment]
Сделал обработку Invar1.
