### ISSUE TITLE
частицы перед чат

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#76]
полдааҷатса - есть разбор (это неверная словоформа, но про то есть другая рекламация), полдааҷат - не разбирается

В ограничении 5 не были учтены случаи Dur и Dur.Iter, добавила.
Кстати, хорошо бы Dur.Iter перенести к временам, вроде после него -ган не бывает.

**Comment by adybo** [comment]
тоңадыр 'мерзнет’ (обыч­н о )’ — тоңадырған 'мерзнущий (обы чно)


>Суббота, 11 ноября 2017, 22:59 +03:00 от veramal <notifications@github.com>:
>
>полдааҷатса - есть разбор (это неверная словоформа, но про то есть другая рекламация), полдааҷат - не разбирается
>В ограничении 5 не были учтены случаи Dur и Dur.Iter, добавила.
>Кстати, хорошо бы Dur.Iter перенести к временам, вроде после него -ган не бывает.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Но не тоңчадырған (а итер и дур.итер - это у нас разные аффиксы).

**Comment by tuffnatty** [comment]
Починил полдаачат. Про перенос Dur.Iter к временам лучше отдельный баг завести.

**Comment by veramal** [comment]
Ага.
