### ISSUE TITLE
паразитический разбор 2pos+дат

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#77]
уйғаа  - один из разборов

n уйғу ‛сон’
----------------ң-а----
----------------2pos.sg-Dat----

В принципе он прав, восстанавливая в интервокале заднеязычный по текущим правилам. Но где-то я уже писала, что лучше обходиться и в посессиве дативом в форме -ГА, разрешая в посессиве правило СГ > С не только заднеязычным С, но и носовым.

**Comment by veramal** [comment]
И делая его необязательным: тогда будут разбираться и примеры с дативом на -мга, которые встречаются в литературных текстах (а посессива типа _тагы_ в лит. пока не встречалось).

**Comment by veramal** [comment]
Правда, если так сделать, то вернется проблема посессивного аккузатива.

**Comment by veramal** [comment]
Вот еще паразитические сандхи:
анаңох
n анаң ‛потом’
----------------ы-----ох
----------------3pos-----Ass
n анаң ‛потом’
-----------------ға----ох
-----------------Dat----Ass

От всякой морфемы должна оставаться хоть одна буква (в т.ч. подвергшаяся стяжению - но не выпадению!).  Надо, может быть, отдельно ввести такое правило, тогда все эти разборы отпадут.

**Comment by adybo** [comment]
Ну вот от ып-то не остается ни одной буквы

**Comment by veramal** [comment]
Поэтому мы и хотим для него завести нулевой алломорф.

**Comment by veramal** [comment]
Это исчезло.
