### ISSUE TITLE
посессив перед вокативом  на -ай

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#78]
Встретились примеры в грамматике, где диминутив на -ас стоит после посессивных показателей.

Йо, **азаамай**!   Уғаа тың сыстапча. - Ой, нога моя! Очень сильно ломит. (М. Коков)
О палаҷаам, о, **иркемей**! Хайдағ пазох хыял килді, **оолғымай**. - О дитя мое, о дорогой! Какое опять несчастье пришло, сыночек.
По, **худайымай**, тӱнее хайди тын ағырдым. - О боже мой, не так давно как же я сильно болела.

Но пока непонятно, это авторское  или нет.

**Comment by adybo** [comment]
На ай. Это вообще-то не диминутив, а звательная форма (тоже во всех языках), но во всех языках скорее атайым


>Воскресенье, 12 ноября 2017, 15:47 +03:00 от veramal <notifications@github.com>:
>
>Встретились примеры в грамматике, где диминутив на -ас стоит после посессивных показателей.
>Йо,  азаамай !   Уғаа тың сыстапча. - Ой, нога моя! Очень сильно ломит. (М. Коков)
>О палаҷаам, о,  иркемей ! Хайдағ пазох хыял килді,  оолғымай . - О дитя мое, о дорогой! Какое опять несчастье пришло, сыночек.
>По,  худайымай , тӱнее хайди тын ағырдым. - О боже мой, не так давно как же я сильно болела.
>Но пока непонятно, это авторское  или нет.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Беглый обзор принес один пример с _худайымай_ у Чебодаевой, примеров типа атайым не встретилось.

**Comment by adybo** [comment]
Ага, ну значит надо вставлять в районе кы


>Понедельник, 13 ноября 2017, 15:04 +03:00 от veramal <notifications@github.com>:
>
>Беглый обзор принес один пример с  худайымай у Чебодаевой, примеров типа атайым не встретилось.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Раз это вокатив, посадила в падежи, в посессивный слот, там как раз лишнее место припасено было.

**Comment by veramal** [comment]
Дописала на всякий случай ограничение 33, чтобы было только в конце словоформы.

**Comment by tuffnatty** [comment]
Добавил.

**Comment by veramal** [comment]
Работает.
