### ISSUE TITLE
морфема temp

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#8]
я так понимаю, она предназначена для форм типа хысхы-зы-н 'зимой', хараа-зы-н 'ночью' и т.п.
но, во-первых, она непродуктивна: даже пу чылын 'в этот год' уже не скажут
во-вторых, у нее есть не только темпоральное значение: кöбiзiн 'в основном', пiрсiн 'во-первых' (хотя тут можно за уши и темпоральность притянуть)
а поскольку концов на -ын очень много, то лишних разборов от нее тоже очень много
надо бы ее в словообразование увести

**Comment by adybo** [comment]
В словообразование не выходит, потому что она все-таки попадается на продуктивности (не могу привести примеров, но в Синих Утесах что-то было), а перед ней 3 лицо.

**Comment by veramal** [comment]
если там три примера с такой продуктивностью, то нафиг. пока, кстати, она лезет не только после 3 лица, надо прописать тогда четко. и она всегда будет совпадать с формой 3pos+acc - тогда не проще ли завести одну морфему acc/temp для посессивных?

**Comment by adybo** [comment]
А черт его знает, сколько там примеров. Если их три, их жалко будет потерять, между прочим, т.к. это нетривиальный результат. Если она не только после 3 л., хорошо ли ее совпадать с Acc?

**Comment by veramal** [comment]
Ну, мне только частотные формы встречались, они все после 3-го. После 1-го,
кстати, тоже совпадет. Три примера можно ручками разметить или в словарь
вбить. Или у нас не предполагается снятие омонимии?

22 декабря 2015 г., 2:06 пользователь adybo <notifications@github.com>
написал:

**Comment by adybo** [comment]
Да нет, конечно, предполагается, только кто будет снимать, зависит. тЫ ЗАМЕТИШЬ, ЧТО ДЕЛО НЕЧИСТО И ЭТО СКОРЕЙ ВСЕГО НЕ АККУЗАТИВ. а ЗА ДЕВУШЕК (Эльвиру и Иру Чебочакову) я не поручусь. А уж за остальных тем более.

**Comment by veramal** [comment]
К тому моменту, когда попадется реальный нечистый пример, я задолбаюсь с
дублями - плавали, знаем)

22 декабря 2015 г., 2:20 пользователь adybo <notifications@github.com>
написал:

**Comment by veramal** [comment]
То есть будет морфема в общей куче или нет - отлов ее реального
употребления все равно на человеке при таком раскладе.

22 декабря 2015 г., 12:28 пользователь Vera Maltseva <malt.wh@gmail.com>
написал:

**Comment by adybo** [comment]
ладно, я еще немножечко подумаю и напишу, чем мне это не нравится, и если ты и Аля и Фил скажут, что я неправа, то ок

**Comment by adybo** [comment]
Я имела в виду или

**Comment by veramal** [comment]
вроде разобрались пока
