### ISSUE TITLE
посессив от слов с кластером на конце

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#80]
Встретилось: _курзы_ = курс+ ы (3pos). Парсер считает, что правильной будет форма _курсы_, без озвончения. Со смычными, видимо, так и есть: например, в Хабаре встретилось _транспорты_, но нет _транспорды_ . Но щелевой после сонанта может озвончаться: в словаре записано (-зы) у статьи "курс" и некоторых других (но не всех: напр., в примерах есть _балансы_, а не _баланзы_). Т.к. неясно, насколько словарь отражает узус, то надо бы иметь возможность разбирать и глухой, и звонкий варианты от всех основ.

**Comment by veramal** [comment]
Это чинить вместе с номером 47 (https://github.com/tuffnatty/suddenly/issues/47#issuecomment-346865060)

**Comment by tuffnatty** [comment]
Тем временем #47 починился

**Comment by veramal** [comment]
Ну тут без помет, для rus оба варианта надо сделать доступными для основ на щелевые: -с, -ф, -ш. Это записано в сандхи 1.1.

**Comment by tuffnatty** [comment]
Там (I.1) про интервокал написано, а про кластеры ничего не написано.

**Comment by veramal** [comment]
Да, действительно. Напишем тогда.

**Comment by veramal** [comment]
Вынесла, в I.1.4 - это, строго говоря, не озвончение в интервокале, но менять всю нумерацию ради мелкой фигни не хочется.

**Comment by tuffnatty** [comment]
Реализовал, как в документе - только для -с после сонорных при помете rus.
