### ISSUE TITLE
полдыни: частица -ни перед личным окончанием

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#81]
Ноға ла пілбеҷең **полдыним** пасха кізі кізі полчатханын?  - Почему же я не знал, что другие люди — тоже люди? (газ. «Ленин чолы»)

Ноға ла андар хыял **иттіним**? - Зачем только я сделал (недавно) эту беду? (газ. «Ленин чолы»)

Хайди ол кізі андағ чирде хорыхпаҷаң **полдыни**? - Как тот человек в таком месте не боялся (обычно)?

Надо добавить в описание. Пока кажется, что она придает вопросу значение риторичности.

**Comment by veramal** [comment]
Также в слоте 18 встречается LA - правда, не обязательно в значении континуатива. Но раз ярлык есть, можно им пользоваться.
_Ол кöп кізілерге салылтыр, че сірер мында **ÿзöлеңнезер**»._
Он на столько народу накрыт, а вас только трое. (Алиса)

Еще попадалось в диалектных текстах, но элановским поиском найти не удалось.

**Comment by veramal** [comment]
ÿзöлеңнезер разбирается, а для прочего добавила Part ни в Ptcl2 и написла ограничение 32, т.к. кроме как с ДЫ, нигде не встретилось.

**Comment by veramal** [comment]
Поняла, что форма _полдыни_ не будет разбираться из-за ограничения 27 (Ptcl2 не бывает на конце словоформы). В принципе оно правильное, но чтобы не множить сущности ради 1 примера, сделала исключение для _ни_.

**Comment by tuffnatty** [comment]
Разбору ды+ни мешает ограничение 12

**Comment by veramal** [comment]
Поправила.

**Comment by tuffnatty** [comment]
Внес в парсер, вроде заработало

**Comment by veramal** [comment]
Да, работает.
