### ISSUE TITLE
столынзартын - нет разбора

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#82]
кӱн **кірізінзертін** иде чилнең хада наңмыр читкен. - с запада вместе с ветром потянулся дождь. (С. Чарков)

_кірізінзертін_ не разбирается, т.к. в допустимых сочетаниях падежей не было прописано, что перед All может стоять посессивность. В принципе число и посессивность могут стоять перед любым падежом. Дописала в ограничение 16.

**Comment by veramal** [comment]
Grammar bug - это не отраженное в документе? Тогда здесь оно лишнее, т.к. я написала там.

**Comment by tuffnatty** [comment]
А! Там как-то очень начерно это написано, до меня несколько дней доходило, что может обозначаться круглыми скобками и `+/-` в этой записи. Нельзя ли как-то переформулировать?

**Comment by tuffnatty** [comment]
и поменять смешанную нумерацию подпунктов 16.2. а,б,в,4,5 на полностью буквенную

**Comment by veramal** [comment]
Ага, поправила.

**Comment by tuffnatty** [comment]
Реализовано.
