### ISSUE TITLE
будущее без -р: сочетания с лицами

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#83]
_Піс кöл хыринда тынанабыс нимезе суға кірербіс, нимезе хумда кӱнге **сістенебіс**, нимезе **палыхтибыс**._ - Мы будем отдыхать возле озера, либо купаться, либо на песке загорать будем, либо будем рыбачить.

Fut  в виде А бывает в сочетании не только с 1sg, но и с другими личными окончаниями (2sg, 2pl, 1pl). Это в принципе прописано в ограничении 20: "при наличии показателей: ... для смешанных форм: Pres ЧА, Dur1 в форме и, Past ГА(н), Hab в форме ҶА, **Fut в форме А**". В нынешней реализации прочие упомянутые аффиксы сочетаются со всеми аффиксами из смешанного набора, а Fut А - только с 1sg. 
(Fut Ар при этом сочетается со всеми формами полного набора)

**Comment by tuffnatty** [comment]
А как же ограничение 9.3?

**Comment by veramal** [comment]
А, точно. Оно сделано, чтобы с императивом не путать. Значит, только для 1 лица это верно, а для 2 неверно. Ограничение сейчас поправлю.

**Comment by tuffnatty** [comment]
Поправил
