### ISSUE TITLE
тохтағлабоғысханнар - не реализовано

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#84]
Надо поднабрать примеров.

**Comment by veramal** [comment]
Пора вводить ыбыс, разбитый -ок - в качинском и кызыльском довольно часто попадается.
Сосха болотада килескi полза, **чiбӧкзер [чібӧгізер]**. 
Свинья, если в болоте ящерица будет, также съест. (НФ Трошкин)

_Челбігэн тӧрт ӧскізін **аппарыбоғысчых**._
Челбэген четырёх коз её унес. (сказки)

_Узи-пергэндэ, Тардааң енэй хабын талап, **сығыбоғысчых**._
Когда он заснул, старуха Тардаан, мешок разорвав, так же вылезла. (сказки)

**Comment by adybo** [comment]
Он у нас есть в скобках.


>Суббота, 22 декабря 2018, 14:11 +03:00 от veramal <notifications@github.com>:
>
>Пора вводить ыбыс, разбитый -ок - в качинском и кызыльском довольно часто попадается.
>Сосха болотада килескi полза,  чiбӧкзер [чібӧгізер] .
>Свинья, если в болоте ящерица будет, также съест. (НФ Трошкин)
>Челбігэн тӧрт ӧскізін  аппарыбоғысчых .
>Челбэген четырёх коз её унес. (сказки)
>Узи-пергэндэ, Тардааң енэй хабын талап,  сығыбоғысчых .
>Когда он заснул, старуха Тардаан, мешок разорвав, так же вылезла. (сказки)
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Anna Dybo

**Comment by veramal** [comment]
Сделано.
