### ISSUE TITLE
тыығанҷа: непонятная форма

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#85]
_Нинҷе хатап пірде чобар, пірде öрініс чайылбаан Мария ууҷаның азааның алтындағы чирҷе, пӱӱнгі пик ырыстығ хоных **тыығанҷа**._ - Сколько раз то горе, то радость переживала бабушка Мария, пока не пришла сегодняшняя счастливая жизнь.

последнее слово не разбирается, и я не понимаю, какая у него основа и есть ли в ней опечатка

**Comment by adybo** [comment]
Это, конеччно, тыырга, тынг- и форма кажется ошибочной.

**Comment by veramal** [comment]
Скорее диалектизм: мы же знаем, что ң и ғ аллофонят. А длина гласных у каждого автора своя.

**Comment by veramal** [comment]
Еще встретилась эта основа: _сині, тізең, ам даа тоғыста, нан-пилі **тыығалах** оолағасты чіли, Герасим тіпчелер._ - а тебя, как неокрепшего мальчишку, на работе до сих пор Герасимом называют. (В. Шулбаева. Чуртас салғағында)

**Comment by veramal** [comment]
Похоже, у глагола **тыырға** действительно основа _тыы_-, а не _тың_-. Даже в словарной статье примеры только с долгой основой: _ағырығ соонаң тыығалах_ [он] ещё не окреп после болезни; _арға-мойным тыығалах_ фольк. [я] ещё не возмужал (букв. спина-шея моя не окрепли ещё). С основой _тың_- ни одного примера в корпусе найти не удалось. Внесла изменение в словарь.

**Comment by adybo** [comment]
исторически, видимо,  тың -ы-?

  
>Воскресенье, 2 августа 2020, 18:51 +03:00 от veramal <notifications@github.com>:
> 
> 
>Похоже, у глагола  тыырға действительно основа  тыы -, а не  тың -. Даже в словарной статье примеры только с долгой основой:  ағырығ соонаң тыығалах [он] ещё не окреп после болезни;  арға-мойным тыығалах фольк. [я] ещё не возмужал (букв. спина-шея моя не окрепли ещё). С основой  тың - ни одного примера в корпусе найти не удалось. Внесла изменение в словарь.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Anna Dybo

**Comment by veramal** [comment]
Исторически связано с тынг, конечно. Но мы уже видели, что некоторые основы
на заднеязычные переосмысляются как основы на долгие. Вот тут тот самый
случай, который уже  проник в лит.язык.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 2 авг. 2020 г. в 19:24, adybo <notifications@github.com>:
