### ISSUE TITLE
чадыр после основ на гласную

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#88]
Не был учтен Dur.Iter в ограничении 26, поэтому разбирается неверное _саначадыр_. (а правильная форма - _санапчадыр_, она тоже разбирается). Дописала.

**Comment by adybo** [comment]
Уже же дописывала?

**Comment by veramal** [comment]
Ну вот еще одно место нашлось.

**Comment by adybo** [comment]
Т.е. без -п?

**Comment by veramal** [comment]
Не заткнут еще один фонтан, который позволяет без -п.

**Comment by adybo** [comment]
А может, оно и вообще без п?

**Comment by veramal** [comment]
Ань, оно с -п. Как все прочие формы от -чат.

**Comment by adybo** [comment]
Т.е. с -чат?
Т.е. чадыр все-таки после -п, если основа на гласную?

**Comment by veramal** [comment]
да

**Comment by tuffnatty** [comment]
Исправил
