### ISSUE TITLE
форма парча пока тоже не разбирается

### ISSUE THREAD

**Issue by tuffnatty** [tuffnatty/suddenly#9]
@veramal NB: форма парча пока тоже не разбирается.
@adybo По-моему, парсер пока не учитывает спецформы от пар и кил.

Я починил проверку на пар- и кил-, однако форма парча от этого разбираться не стала, так как есть неоднозначность в правилах:

> `14`. Показатель Dur1 и(р) заполняется только, если позиции 1, 3, 4 не заполнены, а в позиции 0 стоит пар- или кил- (но при этих основах может выбираться с тем же успехом и показатель Dur чА(Т), свободное варьирование).

и

> `12`. Показатель Dur чА(Т) заполняется только, если заполнена хотя бы одна из позиций 2, 4, (т.е. Form1 или Perf).

Может быть, имеется в виду, что правило 14 отменяет правило 12? Тогда это нужно эксплицитно указать.

**Comment by tuffnatty** [comment]
А стали разбираться пари, кили, парир, килир

**Comment by tuffnatty** [comment]
Т.е. я все это написал про пока что действующую редакцию правил, т.к. по проблеме #2 еще нет определенного решения, насколько я понимаю.

**Comment by adybo** [comment]
Вот примерно как устроено.

Про чат правило 12 в формулировке, выведенной в переписке. Т.е. для анализа важно, что дуратив -чат бывает только после согласной или если перед ним заполнена частица, кончающаяся на гласную. Для синтеза важно, что перед ним могут быть только те позиции, которые перед ним, так что это не интересно. Правило про заполненность позиций 2, 4 неправильное, потому что оно стоит, чтоб не вставилось чат после -кыла (а это запрещено, потому что должно быть -кыла-п-ча) или после чистой основы на гласную (типа тара-, потому что должно быть тара-п-ча), но после чистой основы на согласную чат можно вставлять. На самом деле оно бывает после Form на -п, но Form на -п после согласной пропадает вчистую, а мы считаем, что нулей нет, и значит, считаем, что -п в этой фон. позиции не заполняется. То есть этого правила про 2, 4 просто нет, вместо него правило про гласную.

Теперь про дуратив на -ир
Дуратив на-ир бывает только непосредственно после основ пар и кил. Кажется. Кажется, что если там хоть что еще между ними заполнено, то будет чат. Вера, это так? Но и непосредственно после пар и кил тоже может быть и чат. Там будет тонкое семантическое различие, но не сформулировано как следует, какое.

**Comment by veramal** [comment]
Правило 14 к правилу 12 содержательного отношения не имеет - просто у пар и кил две формы дуратива (финитного презенса): общая: парча/килче и особая: пари(р)/кили(р) с личными окончаниями. Между основой и dur2 ничего быть не может. После dur2 в литературном бывает только -ган: париган / килиген. Ну и личные окончания.В Казановке вместо этого париткен/килиткен, а также вот парин недавно всплыл - но это лучше пока не учитывать.

Правило 12 в итоге такое: "Показатель Dur чА(Т) и показатель Indit тыр не могут быть заполнены, если при этом непосредственно перед ними обнаруживается морфема, оканчивающаяся на гласную - кроме морфем из позиции Ptcl 1".

**Comment by veramal** [comment]
презенсы работают
