### ISSUE TITLE
выпадение конечного  ң односложной основы

### ISSUE THREAD

**Issue by tuffnatty** [tuffnatty/suddenly#92]
В документе написано:
>маң ‘досуг’ + -ы > маа ‘его досуг’, НО: аң ‘зверь’ + -ы > аңы ‘его зверь’, 

но способа определить, разрешено/обязательно ли выпадение в данном случае, не приведено.

**Comment by veramal** [comment]
Точно не разрешено, если в основе две буквы. Про остальное надо думать.

**Comment by adybo** [comment]
Написано, что определяется по словарю


>Четверг, 30 ноября 2017, 20:16 +03:00 от Phil Krylov <notifications@github.com>:
>
>В документе написано:
>>маң ‘досуг’ + -ы > маа ‘его досуг’, НО: аң ‘зверь’ + -ы > аңы ‘его зверь’,
>но способа определить, разрешено/обязательно ли выпадение в данном случае, не приведено.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Ну вот по словарю - плохая идея, если по сумме диалектов мы имеем все варианты.

**Comment by adybo** [comment]
проверила ! написано что все варианты

**Comment by adybo** [comment]
Их и всего-то штук - меньше кол-ва гласных, и про бч не даны формы. Так что делаем свободное.


>Четверг, 30 ноября 2017, 22:32 +03:00 от veramal <notifications@github.com>:
>
>А это ты что проверила, свой текст?
>Все же, если в основе меньше трех букв, то сокращается только слово ӧң - цвет.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Anna Dybo

**Comment by veramal** [comment]
Ну в общем да.

**Comment by tuffnatty** [comment]
Реализовал в парсере свободное, но надо это почетче отметить в документе.
