### ISSUE TITLE
поплохело велярным

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#94]
Не разбирается то, что разбиралось раньше:
Слова с Г на конце:
андағ
арығ
иліг
ізіг
 и др.

и с К тоже:
чохырах

и с ң:
аннаң 
чалаң

а также их падежные формы:
арығда
арығзар
арығлар
арығӌа

**Comment by tuffnatty** [comment]
чохырах - нет такого слова, остальные починил.

**Comment by veramal** [comment]
Ага, это имя оказалось.
