### ISSUE TITLE
ис- и сис-

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#96]
Сейчас для данных глаголов не анализируются формы с аффиксами, которые начинаются на Г: _искен, сискей_. Анализируется, наоборот, _исткен, систкей_.

**Comment by tuffnatty** [comment]
Сейчас анализируются и искен (от изерге), и исткен (от истерге)

**Comment by veramal** [comment]
Да, но нужен также искен от истерге.

**Comment by adybo** [comment]
Вот покамест что у меня вроде вышло с упорядочением правил, читать начиная с таблицы (до того - лирика) до пункта 2.2. Дальше не стрясла еще всё (там надо разделить правила, которые действуют с границей между морфемами, и те, которые действуют после уничтожения границ между морфемами - и, конечно, ввести это уничтожение границ и потом в нек. момент понижение регистра для всех оставшихся больших букв).

**Comment by veramal** [comment]
Ну вот надо бы все же посидеть со всем этим на след. неделе.

**Comment by tuffnatty** [comment]
Исправил.
