### ISSUE TITLE
переделка грамматики: NF

### ISSUE THREAD

**Issue by veramal** [tuffnatty/suddenly#99]
Решили разделить аффикс свободного деепричастия и деепричастную основу, от которой образуются синтетические и аналитические формы. Для этого в поз. 2 переименовали Convп в NF, Conv.Neg в NF.Neg, и у NF добавили алломорф 0.
В правиле 4.1 объясняется правило выбора алломорфа для NF. В правиле 4 убрали требование быть не в конце словоформы. Изменено правило 26: теперь перед презенсом и прочими всегда должен быть NF. Позицию Conv1 вычеркнули из правила 27, т.к. NF и NF.Neg могут быть в конце словоформы. 
Убрали морфонему D, т.к. теперь партыр должен получаться за счет того, что между пар и тыр стоит оглушающий ноль. Вот так:
пар-0-тыр
идти-NF-Indir

Осталось понять, вводить ли оглушающий ноль как морфонему. Или можно написать в правилах выбора буквы:
_Морфонема П- выбирает репрезентацию б после звонкой неносовой согласной, п после гласной или глухой согласной **или 0**, м после носовой;_ 
и т.п. - имея в виду, что 0 здесь - алломорф.

**Comment by adybo** [comment]
Ноль удобно убирать, когда убираешь все морфонемы. Репрезентацию 0 ты ведь буковкой не напишешь, а когда убираются морфонемы, как раз и получается орфографическое представление примерно.

**Comment by veramal** [comment]
Напиши, пожалуйста, подробно для парсера, на каких этапах есть ноль, на каких нет, и как он убирается. Я не до конца понимаю, что ты предлагаешь.

**Comment by tuffnatty** [comment]
В целом реализовал, хотя надо уточнить правила (в комментах в документе). Перестало разбираться  узу-ах-ча > узихча 'вот-вот заснет' - NF тут невозможен, т.к. основа на гласную, Prosp  бывает только перед Pres, а Pres - только при наличии NF.

**Comment by veramal** [comment]
Ага, здорово. Исправила 4 и 26.

**Comment by tuffnatty** [comment]
Реализовал.

**Comment by veramal** [comment]
Когда 0 сидит на конце словоформы, ему тоже нужна глосса. Даже больше, чем когда он в середине. Таким образом, у "кил" должно быть два разбора, - старый  и с нулем - а у "сана" один.

**Comment by tuffnatty** [comment]
Надо как-то переписать 4.1, чтобы было яснее, что рассматриваются 3 взаимоисключающих случая, т.к. из "После основы на невыпадающую согласную в конце словоформы для NF возможны оба алломорфа." автоматически не следует, что в этом случае предыдущее ограничение "NF выбирает алломорф 0 после основы или аффикса на согласную, если после него также стоит аффикс" не действует.

**Comment by veramal** [comment]
Переписала.

**Comment by veramal** [comment]
Сейчас для форм с -ып на конце нет разбора через NF (ср. санап и парып - должно быть одинаково).

**Comment by veramal** [comment]
В описании была ошибка: "Изменено правило 26: теперь перед презенсом и прочими всегда должен быть NF. " Забыли, что при перфекте NF обычно не выражается, а при проспективе не выражается никогд. Поэтому сейчас формы типа _парыбысча_ не разбираются. Добавила перфект в правило 26 (проспектив там был).

**Comment by veramal** [comment]
Правило 26 пришлось переписать еще раз, т.к. я забыла, что у индиректива бывает отрицательная форма через ГАН - в этом случае нет ни NF, ни перфекта. Исправила.

**Comment by veramal** [comment]
Еще уточнение: NF0 не может присоединяться к основам на -п (у них всегда происходит стяжение с удлинением гласной: сап-ып > саап).

**Comment by adybo** [comment]
Вроде про это писали

**Comment by veramal** [comment]
Ну вот конкретно при NF0 оказалось не упомянутым.

**Comment by veramal** [comment]
А нет, есть:
"4.1. NF выбирает алломорф (I)П, если: 1) он непосредственно следует за основой, которая оканчивается на (выпадающие, см. ниже) п, г, ғ или ӊ;"
Сейчас для сонорных реализовано, для п парсер допускает два варианта. Дописала почетче, что NF0 может быть после согласной, только если она не выпадает.

**Comment by veramal** [comment]
Сейчас больше всего мешает вот этот баг - а именно, то, что перфект не разбирается перед -ча и -тыр, и -баандыр тоже не разбирается (Neg-Past-Indir).

**Comment by tuffnatty** [comment]
Можно уточнить? Нужны конкретные примеры.

**Comment by veramal** [comment]
Ну ты уже 26 воплотил в жизнь, работает. Но напишу для истории ключевые формы: _парыбыстыр, парыбысча, парбаандыр_ - не работало еще вчера. _Санап, саап_ и _парып_ теперь все имеют по два разбора (через ConvP и через NF). _Парахча, санихча_ - тоже ок. Вроде всё.
